import type { ContentMap } from "./_types";
import { I } from "./_types";

export const BUSINESS_CONTENT: ContentMap = {
  finance: {
    heroTitle: "稳健金融，值得托付",
    heroSubtitle: "专业的财富管理与综合金融服务，守护您的每一份资产。",
    aboutBody: [
      "我们是一家持牌经营的综合金融服务机构，为个人与企业客户提供从财富管理到企业融资的全方位解决方案，管理规模多年保持稳健增长。",
      "以风控为本、以客户为先，团队拥有平均超过十年的从业经验，建立了完善的合规与风险管理体系，把「让客户的钱更安心」作为始终不变的承诺。",
    ],
    features: [
      { title: "持牌合规", desc: "正规持牌经营，资金流向透明可查。", icon: I.shield },
      { title: "专业团队", desc: "资深金融顾问，平均从业十年以上。", icon: I.users },
      { title: "风控为本", desc: "全周期风险识别与对冲，稳健第一。", icon: I.chart },
      { title: "资产配置", desc: "量身定制组合方案，平衡收益与风险。", icon: I.cog },
      { title: "稳健增值", desc: "长期主义投资理念，穿越市场周期。", icon: I.star },
      { title: "私密服务", desc: "客户信息严格保密，一对一专属顾问。", icon: I.heart },
    ],
    services: [
      { name: "财富管理", desc: "量身定制的资产配置与投资组合方案。" },
      { name: "企业融资", desc: "多渠道融资解决方案，助力企业成长。" },
      { name: "风险管理", desc: "全周期风险识别、评估与对冲。" },
      { name: "保险规划", desc: "家庭与企业的全面风险保障设计。" },
    ],
    stats: [
      { value: "18年", label: "稳健经营" },
      { value: "300亿", label: "管理规模" },
      { value: "5万+", label: "服务客户" },
      { value: "AAA", label: "信用评级" },
    ],
    testimonials: [
      { name: "陈先生", role: "企业主", text: "融资方案给得专业又快，帮我们抓住了关键的扩张窗口期。" },
      { name: "林女士", role: "高净值客户", text: "顾问很负责，资产配置稳中有进，几年下来收益和心态都很稳。" },
      { name: "黄总", role: "公司财务负责人", text: "风控体系做得扎实，把钱交给他们打理我们很放心。" },
    ],
    ctaTitle: "让财富，稳健生长",
    ctaSubtitle: "预约专属顾问，获取一份属于你的资产配置方案。",
    contactPhone: "400-888-2001",
    contactEmail: "hello@finance.com",
    contactAddress: "上海市浦东新区陆家嘴环路 1000 号",
    footerSlogan: "以专业守护财富，以诚信赢得信赖。",
  },

  investment: {
    heroTitle: "看得更远，投得更准",
    heroSubtitle: "投资咨询 · 行业研究 · 项目尽调，做你投资决策的专业参谋。",
    aboutBody: [
      "我们是一家专注于投资咨询的专业机构，团队由行业研究员、财务分析师与资深投资人组成，为企业与个人投资者提供独立、客观的投资决策支持。",
      "从宏观趋势研判到具体项目的尽职调查，我们坚持用数据和逻辑说话，帮客户看清机会、识别风险，把每一笔投资都建立在扎实的研究之上。",
    ],
    features: [
      { title: "独立研究", desc: "不带立场的客观研判，只对结果负责。", icon: I.chart },
      { title: "行业洞察", desc: "深耕多个赛道，看得懂趋势与拐点。", icon: I.globe },
      { title: "尽职调查", desc: "财务、法律、业务全维度尽调把关。", icon: I.shield },
      { title: "资深团队", desc: "投行与产业背景兼备的专业班底。", icon: I.users },
      { title: "风险预警", desc: "提前识别潜在风险，守住投资底线。", icon: I.bolt },
      { title: "长期视角", desc: "拒绝短期投机，陪客户做时间的朋友。", icon: I.clock },
    ],
    services: [
      { name: "投资策略咨询", desc: "资产配置与投资方向的专业建议。" },
      { name: "行业研究报告", desc: "细分赛道深度研究与趋势研判。" },
      { name: "项目尽职调查", desc: "标的财务、业务与法律全面尽调。" },
      { name: "并购重组顾问", desc: "并购方案设计与交易全程顾问。" },
    ],
    stats: [
      { value: "15年", label: "投研经验" },
      { value: "1200+", label: "研究报告" },
      { value: "200+", label: "尽调项目" },
      { value: "30+", label: "覆盖行业" },
    ],
    testimonials: [
      { name: "赵总", role: "产业基金合伙人", text: "他们的行业研究有真知灼见，帮我们避开了好几个看似诱人的坑。" },
      { name: "钱女士", role: "家族办公室负责人", text: "尽调做得非常细致，风险点列得清清楚楚，决策有底气多了。" },
      { name: "孙先生", role: "企业董事长", text: "并购顾问全程专业，方案设计帮我们省下了大量谈判成本。" },
    ],
    ctaTitle: "把决策，交给专业研究",
    ctaSubtitle: "告诉我们你的投资方向，让专业团队为你出具研究意见。",
    contactPhone: "400-888-2002",
    contactEmail: "hello@investment.com",
    contactAddress: "北京市西城区金融大街 7 号",
    footerSlogan: "用研究照亮决策，用专业创造价值。",
  },

  loan: {
    heroTitle: "周转有道，理财有方",
    heroSubtitle: "理财贷款 · 资金周转 · 信用规划，让钱更好地为你工作。",
    aboutBody: [
      "我们是一家专注个人与小微企业资金服务的综合机构，对接银行与持牌金融机构资源，为客户匹配利率合理、放款高效的贷款与理财方案。",
      "我们坚持合规经营、明码标价，全程不收取任何前期费用，用专业的信用规划和一对一的顾问服务，帮客户解决周转难题、规划好每一分钱。",
    ],
    features: [
      { title: "正规渠道", desc: "对接持牌机构，资金来源安全合规。", icon: I.shield },
      { title: "极速审批", desc: "材料齐全最快当天放款，周转不等人。", icon: I.bolt },
      { title: "低息优选", desc: "多家比价择优，帮你省下真金白银。", icon: I.chart },
      { title: "方案定制", desc: "按收入与需求量身匹配额度与期限。", icon: I.cog },
      { title: "信息保密", desc: "客户资料严格加密，隐私安全无忧。", icon: I.heart },
      { title: "全程顾问", desc: "一对一专人跟进，办理省心不踩坑。", icon: I.users },
    ],
    services: [
      { name: "个人信用贷款", desc: "凭信用快速借款，额度高、放款快。" },
      { name: "企业经营贷款", desc: "小微企业经营资金周转解决方案。" },
      { name: "房产抵押贷款", desc: "房产抵押融资，额度大、利率优。" },
      { name: "理财规划顾问", desc: "稳健理财配置与负债结构优化。" },
    ],
    stats: [
      { value: "12年", label: "金融服务" },
      { value: "10万+", label: "成功放款" },
      { value: "1天", label: "最快到账" },
      { value: "0元", label: "前期费用" },
    ],
    testimonials: [
      { name: "周先生", role: "小微企业主", text: "资金紧的时候帮我当天就解决了周转，利率也比我自己谈的低。" },
      { name: "吴女士", role: "个体经营者", text: "顾问很耐心，材料怎么准备都讲清楚，办下来比想象中轻松。" },
      { name: "郑先生", role: "上班族", text: "全程没有任何前期费用，明明白白，比那些套路机构靠谱太多。" },
    ],
    ctaTitle: "资金周转，找对人就轻松",
    ctaSubtitle: "免费咨询额度与利率，专业顾问为你定制周转方案。",
    contactPhone: "400-888-2003",
    contactEmail: "hello@loan.com",
    contactAddress: "深圳市福田区深南大道 6011 号",
    footerSlogan: "合规放款，用心规划每一分钱。",
  },

  realestate: {
    heroTitle: "筑就理想生活空间",
    heroSubtitle: "精品地产开发，让每一寸土地都成为美好生活的起点。",
    aboutBody: [
      "我们是一家深耕城市人居的房地产开发企业，业务涵盖住宅开发、商业地产与城市更新，始终以「建造经得起时间检验的好房子」为己任。",
      "从地块研判、产品设计到工程建造与物业服务，我们坚持品质优先、长期主义，用匠心打磨每一个项目，为城市留下有温度、有价值的建筑作品。",
    ],
    features: [
      { title: "匠心品质", desc: "从选材到工艺层层把关，经得起时间。", icon: I.award },
      { title: "稀缺地段", desc: "深耕核心区位，价值自带保障。", icon: I.globe },
      { title: "人居设计", desc: "以居住者为中心打磨每一处空间细节。", icon: I.sparkle },
      { title: "智慧社区", desc: "智能门禁与社区系统，住得更安心。", icon: I.cog },
      { title: "园林景观", desc: "高绿化率园林，推窗即见诗意生活。", icon: I.leaf },
      { title: "贴心物业", desc: "全周期物业服务，守护业主美好生活。", icon: I.heart },
    ],
    services: [
      { name: "住宅开发", desc: "高品质人居社区，匠心营造每个细节。" },
      { name: "商业地产", desc: "城市综合体与写字楼运营管理。" },
      { name: "物业服务", desc: "贴心物业管理，守护业主美好生活。" },
      { name: "资产运营", desc: "存量资产盘活与长期价值经营。" },
    ],
    stats: [
      { value: "20年", label: "开发历程" },
      { value: "60+", label: "精品项目" },
      { value: "30万", label: "幸福业主" },
      { value: "98%", label: "业主满意" },
    ],
    testimonials: [
      { name: "李先生", role: "业主", text: "房子品质看得见，户型方正、园林漂亮，入住几年依旧满意。" },
      { name: "张女士", role: "二次置业业主", text: "正是因为第一套住得舒心，第二套依然选了他们的项目。" },
      { name: "王总", role: "商业租户", text: "综合体运营很用心，客流旺、配套全，生意比预期还好。" },
    ],
    ctaTitle: "遇见你理想中的家",
    ctaSubtitle: "预约品鉴，亲身感受我们对品质人居的每一份用心。",
    contactPhone: "400-888-2004",
    contactEmail: "hello@realestate.com",
    contactAddress: "杭州市拱墅区莫干山路 1418 号",
    footerSlogan: "以匠心营造，为城市筑就理想生活。",
  },

  registration: {
    heroTitle: "创业第一步，从这里开始",
    heroSubtitle: "工商注册 · 代理记账 · 资质办理，让你专心拼事业。",
    aboutBody: [
      "我们是一家专注企业服务的工商代理机构，从公司注册、银行开户到税务报道，为创业者提供一站式开办服务，让繁琐的手续不再成为创业的拦路虎。",
      "依托对工商政策的熟悉与多年的实操经验，我们坚持流程透明、收费合理，已帮助上万家企业顺利落地，做创业路上最值得信赖的「店小二」。",
    ],
    features: [
      { title: "一站办理", desc: "注册、开户、报税一条龙，少跑腿。", icon: I.bolt },
      { title: "政策熟悉", desc: "吃透工商税务政策，避坑又省心。", icon: I.shield },
      { title: "极速下证", desc: "材料齐备最快三天拿照，开业不等。", icon: I.clock },
      { title: "园区资源", desc: "对接多地优惠园区，落地更划算。", icon: I.globe },
      { title: "专属顾问", desc: "一对一服务，全程进度随时可查。", icon: I.users },
      { title: "收费透明", desc: "明码标价无隐形消费，预算可控。", icon: I.chart },
    ],
    services: [
      { name: "公司注册", desc: "核名、注册、刻章、开户一站搞定。" },
      { name: "代理记账", desc: "专业记账报税，财税合规无忧。" },
      { name: "资质许可办理", desc: "各类经营许可与行业资质代办。" },
      { name: "变更注销", desc: "公司变更、迁移与注销全程代办。" },
    ],
    stats: [
      { value: "13年", label: "企业服务" },
      { value: "2万+", label: "成功注册" },
      { value: "3天", label: "极速下证" },
      { value: "99%", label: "客户复购" },
    ],
    testimonials: [
      { name: "陈先生", role: "初创公司创始人", text: "从核名到拿照全程帮我搞定，第一次创业完全没踩坑。" },
      { name: "刘女士", role: "个体老板", text: "代理记账省心又专业，每个月报税我基本不用操心。" },
      { name: "杨总", role: "连锁品牌负责人", text: "多地分公司注册都交给他们，效率高、收费也透明。" },
    ],
    ctaTitle: "把手续交给我们，把事业留给你",
    ctaSubtitle: "免费咨询注册流程与费用，今天就开启你的创业之路。",
    contactPhone: "400-888-2005",
    contactEmail: "hello@registration.com",
    contactAddress: "广州市越秀区东风中路 410 号",
    footerSlogan: "专业代办，做创业路上的贴心管家。",
  },

  accounting: {
    heroTitle: "财税无忧，经营更安心",
    heroSubtitle: "财务会计 · 代理记账 · 税务筹划，为企业管好每一笔账。",
    aboutBody: [
      "我们是一家由注册会计师与资深税务师领衔的财务会计服务机构，为中小企业提供从日常记账报税到财务管理咨询的专业服务，让老板看得懂账、放得下心。",
      "面对不断变化的财税政策，我们坚持合规第一、专业至上，帮企业守住财税底线、用足合法政策红利，把财务从「成本中心」变成经营决策的有力支撑。",
    ],
    features: [
      { title: "持证团队", desc: "注会、税务师领衔，专业有保障。", icon: I.award },
      { title: "合规记账", desc: "规范账务处理，经得起检查。", icon: I.shield },
      { title: "税务筹划", desc: "合法用足政策，合理降低税负。", icon: I.chart },
      { title: "及时申报", desc: "按时报税从不逾期，杜绝罚款。", icon: I.clock },
      { title: "财务分析", desc: "定期出具报表分析，辅助决策。", icon: I.cog },
      { title: "数据安全", desc: "财务数据加密管理，安全保密。", icon: I.heart },
    ],
    services: [
      { name: "代理记账报税", desc: "日常账务处理与按月纳税申报。" },
      { name: "税务筹划咨询", desc: "合规税务筹划与政策红利运用。" },
      { name: "财务报表审计", desc: "年度审计与专项财务报告出具。" },
      { name: "汇算清缴", desc: "企业所得税年度汇算清缴办理。" },
    ],
    stats: [
      { value: "16年", label: "财税经验" },
      { value: "5000+", label: "服务企业" },
      { value: "0次", label: "逾期申报" },
      { value: "100%", label: "合规交付" },
    ],
    testimonials: [
      { name: "周总", role: "制造企业老板", text: "税务筹划做得专业，合法合规地帮我们省下了不少税。" },
      { name: "吴女士", role: "电商负责人", text: "账目清晰、报税及时，再也不用担心忘报漏报被罚款了。" },
      { name: "郑先生", role: "餐饮连锁创始人", text: "每月的财务分析报告让我对经营情况心里特别有数。" },
    ],
    ctaTitle: "让专业的人，管好你的账",
    ctaSubtitle: "预约财税体检，看看你的企业还有多少优化空间。",
    contactPhone: "400-888-2006",
    contactEmail: "hello@accounting.com",
    contactAddress: "成都市锦江区红星路三段 1 号",
    footerSlogan: "合规为本，做企业财税的坚实后盾。",
  },

  trademark: {
    heroTitle: "知识产权，护你周全",
    heroSubtitle: "商标专利 · 版权登记 · 维权代理，为创新筑起保护墙。",
    aboutBody: [
      "我们是一家专业的知识产权代理机构，团队由资深商标代理人、专利代理师与知识产权律师组成，为企业提供从申请确权到维权保护的全链条服务。",
      "在创新驱动的时代，无形资产往往是企业最核心的竞争力。我们以专业与负责的态度，帮客户把每一项创意、每一个品牌都牢牢握在自己手中。",
    ],
    features: [
      { title: "专业代理", desc: "资深代理人团队，申请通过率高。", icon: I.award },
      { title: "全类布局", desc: "商标专利组合布局，保护更周全。", icon: I.shield },
      { title: "在线查询", desc: "专业检索评估，申请前先看胜算。", icon: I.chart },
      { title: "进度透明", desc: "全程跟进官方进度，节点不遗漏。", icon: I.clock },
      { title: "维权护航", desc: "侵权监测与维权诉讼一并解决。", icon: I.bolt },
      { title: "全球申请", desc: "对接国际渠道，助力品牌出海。", icon: I.globe },
    ],
    services: [
      { name: "商标注册", desc: "商标检索、申请与全类布局保护。" },
      { name: "专利申请", desc: "发明、实用新型与外观专利代理。" },
      { name: "版权登记", desc: "作品与软件著作权登记办理。" },
      { name: "知产维权", desc: "侵权监测、投诉与维权诉讼代理。" },
    ],
    stats: [
      { value: "14年", label: "知产服务" },
      { value: "3万+", label: "成功申请" },
      { value: "92%", label: "注册通过" },
      { value: "100+", label: "维权胜诉" },
    ],
    testimonials: [
      { name: "黄总", role: "品牌创始人", text: "全类商标布局做得很到位，再也不怕辛苦做的品牌被人抢注。" },
      { name: "林先生", role: "科技公司 CTO", text: "专利申请专业高效，核心技术终于有了实打实的保护。" },
      { name: "何女士", role: "设计工作室主理人", text: "遇到侵权他们帮我维权成功，专业又给力，强烈推荐。" },
    ],
    ctaTitle: "别让你的创意，成了别人的资产",
    ctaSubtitle: "免费商标查询与专利评估，把创新牢牢握在自己手里。",
    contactPhone: "400-888-2007",
    contactEmail: "hello@trademark.com",
    contactAddress: "南京市建邺区江东中路 222 号",
    footerSlogan: "守护创新成果，让智慧产生价值。",
  },

  law: {
    heroTitle: "以专业，守护您的权益",
    heroSubtitle: "资深律师团队，为个人与企业提供全方位法律服务。",
    aboutBody: [
      "我们是一家综合性律师事务所，汇聚了在公司、合同、诉讼、知识产权等领域深耕多年的资深律师，致力于为客户提供既专业又务实的法律解决方案。",
      "我们深知每一个案件背后都关乎当事人的切身利益，因此始终坚持「尽职、严谨、负责」的执业准则，用扎实的专业功底，全力维护每一位委托人的合法权益。",
    ],
    features: [
      { title: "资深律师", desc: "多领域专家律师，经验丰富有口碑。", icon: I.award },
      { title: "诉讼经验", desc: "大量胜诉案例，庭审应对从容专业。", icon: I.shield },
      { title: "保密严谨", desc: "严守职业操守，当事人隐私绝对保密。", icon: I.heart },
      { title: "团队协作", desc: "复杂案件多人协作，专业互补无死角。", icon: I.users },
      { title: "及时响应", desc: "紧急法律事务快速介入，不误时机。", icon: I.bolt },
      { title: "费用透明", desc: "收费标准事先明确，绝无隐形费用。", icon: I.chart },
    ],
    services: [
      { name: "企业法律顾问", desc: "常年法律顾问，防范经营风险。" },
      { name: "诉讼仲裁代理", desc: "民商事诉讼代理，全力维护权益。" },
      { name: "合同审查起草", desc: "专业合同起草、审查与风险提示。" },
      { name: "知识产权保护", desc: "商标、专利、版权全链条维权。" },
    ],
    stats: [
      { value: "20年", label: "执业经验" },
      { value: "8000+", label: "代理案件" },
      { value: "93%", label: "胜诉调解" },
      { value: "50+", label: "专业律师" },
    ],
    testimonials: [
      { name: "陈先生", role: "企业法务总监", text: "常年顾问做得很到位，很多经营风险在签约前就帮我们规避了。" },
      { name: "王女士", role: "当事人", text: "一桩拖了很久的纠纷被律师高效解决，专业、负责又有耐心。" },
      { name: "刘总", role: "公司董事长", text: "一场复杂的商事诉讼打赢了，团队的专业功底真不是盖的。" },
    ],
    ctaTitle: "遇到法律难题，先找专业律师",
    ctaSubtitle: "预约一次免费法律咨询，让专业为你的权益护航。",
    contactPhone: "400-888-2008",
    contactEmail: "hello@law.com",
    contactAddress: "北京市朝阳区光华路 5 号世纪财富中心",
    footerSlogan: "以法之名，守护每一份合法权益。",
  },

  guarantee: {
    heroTitle: "为信用增信，为融资护航",
    heroSubtitle: "投资担保 · 融资增信 · 风险共担，让合作多一份安心。",
    aboutBody: [
      "我们是一家持牌经营的专业担保机构，依托雄厚的注册资本与完善的风控体系，为企业与个人提供融资担保、履约担保等多元化的增信服务。",
      "我们深知担保的本质是信任的传递，因此坚持审慎经营、合规风控，与银行等金融机构建立了长期稳定的合作关系，做客户与资金之间最可靠的「信用桥梁」。",
    ],
    features: [
      { title: "持牌经营", desc: "正规担保牌照，合规稳健有底气。", icon: I.shield },
      { title: "雄厚实力", desc: "充足注册资本，担保能力有保障。", icon: I.award },
      { title: "银行合作", desc: "深度对接金融机构，放款更顺畅。", icon: I.globe },
      { title: "风控严谨", desc: "专业风控体系，把控每一个环节。", icon: I.chart },
      { title: "高效审批", desc: "流程精简、响应迅速，不误融资。", icon: I.bolt },
      { title: "方案灵活", desc: "按需设计担保方案，匹配真实需求。", icon: I.cog },
    ],
    services: [
      { name: "融资担保", desc: "为企业银行贷款提供增信担保。" },
      { name: "履约担保", desc: "工程、合同履约保证担保服务。" },
      { name: "诉讼保全担保", desc: "财产保全与诉讼担保业务办理。" },
      { name: "供应链担保", desc: "上下游供应链融资增信方案。" },
    ],
    stats: [
      { value: "15年", label: "担保经验" },
      { value: "200亿", label: "累计担保" },
      { value: "30+", label: "合作银行" },
      { value: "AA", label: "信用等级" },
    ],
    testimonials: [
      { name: "周总", role: "制造企业负责人", text: "有了他们的担保增信，银行贷款审批快了很多，融资终于不犯难。" },
      { name: "吴先生", role: "工程公司老板", text: "履约担保办理高效专业，帮我们顺利拿下了好几个大项目。" },
      { name: "郑女士", role: "贸易公司财务", text: "供应链担保方案很灵活，资金周转一下子盘活了。" },
    ],
    ctaTitle: "融资遇阻，让担保来增信",
    ctaSubtitle: "免费评估你的担保需求，专业团队为你设计增信方案。",
    contactPhone: "400-888-2009",
    contactEmail: "hello@guarantee.com",
    contactAddress: "武汉市江汉区建设大道 568 号",
    footerSlogan: "以信用为桥，连接企业与资金。",
  },

  pawn: {
    heroTitle: "急用钱，典当更便捷",
    heroSubtitle: "典当拍卖 · 名品鉴定 · 资产变现，让资产快速流动起来。",
    aboutBody: [
      "我们是一家持证经营的综合典当行，专注名表、珠宝、黄金、奢侈品与房产汽车的典当、收购与拍卖业务，配备专业鉴定师团队，为客户提供安全、便捷的短期融资渠道。",
      "我们坚持公平估价、当面成交、保密为先，以远高于行业的放款效率和合理的综合费率，帮客户在急需资金时快速盘活手中资产，真正做到救急不添堵。",
    ],
    features: [
      { title: "专业鉴定", desc: "资深鉴定师把关，估价公允透明。", icon: I.award },
      { title: "极速放款", desc: "鉴定即估价，最快十分钟拿到钱。", icon: I.bolt },
      { title: "安全保管", desc: "专业库房与保险，当品安全无忧。", icon: I.shield },
      { title: "费率合理", desc: "综合费用明示，绝无隐形收费。", icon: I.chart },
      { title: "全程保密", desc: "当面交易、信息保密，体面又安心。", icon: I.heart },
      { title: "活当灵活", desc: "随时赎当续当，资金安排更自由。", icon: I.cog },
    ],
    services: [
      { name: "名表珠宝典当", desc: "名表、钻石、黄金快速典当变现。" },
      { name: "奢侈品收购", desc: "名包名表奢侈品鉴定收购回收。" },
      { name: "房产汽车典当", desc: "房产、车辆抵押融资周转服务。" },
      { name: "艺术品拍卖", desc: "古玩字画与收藏品委托拍卖。" },
    ],
    stats: [
      { value: "10年", label: "典当经营" },
      { value: "10分钟", label: "极速估价" },
      { value: "5万+", label: "成交客户" },
      { value: "100%", label: "正品鉴定" },
    ],
    testimonials: [
      { name: "李先生", role: "企业主", text: "急需周转时拿名表来当，十几分钟就放款了，解了燃眉之急。" },
      { name: "张女士", role: "藏家", text: "鉴定专业、估价公道，奢侈品回收的价格比别家高不少。" },
      { name: "王总", role: "回头客", text: "续当赎当都很灵活，全程保密，办事体面又靠谱。" },
    ],
    ctaTitle: "资产变现，就在转眼之间",
    ctaSubtitle: "带上你的当品来店鉴定，或先在线免费预估价值。",
    contactPhone: "400-888-2010",
    contactEmail: "hello@pawn.com",
    contactAddress: "重庆市渝中区解放碑民权路 28 号",
    footerSlogan: "公平估价，让每一份资产快速流动。",
  },
};
