import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「服装/饰品/美容护肤」各子类的精修中文文案。
export const FASHION_CONTENT: ContentMap = {
  womenswear: {
    brand: "她衣阁女装",
    heroTitle: "穿出属于你的风格",
    heroSubtitle: "当季新品上线 · 设计师原创女装，遇见更美的自己。",
    aboutTitle: "关于她衣阁",
    aboutBody: [
      "她衣阁专注于都市女性的日常穿搭，从面料甄选到版型打磨，坚持每一件都经得起细看与久穿。我们相信，衣服不只是蔽体，更是表达态度与自信的方式。",
      "品牌成立八年，与多位独立设计师长期合作，每季推出限量原创系列。我们用恰到好处的剪裁与配色，让你在通勤、约会、聚会的每个场合都从容得体。",
    ],
    featuresTitle: "为什么选择她衣阁",
    featuresSubtitle: "从设计到售后，每一步都为你考虑周到。",
    features: [
      { title: "原创设计", desc: "签约设计师手稿打版，拒绝同质化撞衫。", icon: I.sparkle },
      { title: "优选面料", desc: "天然棉麻与高支精纺，亲肤透气更显质感。", icon: I.leaf },
      { title: "精修版型", desc: "经多轮真人试穿调整，藏肉显瘦不挑身材。", icon: I.award },
      { title: "每周上新", desc: "紧跟四季流行趋势，常逛常新不重样。", icon: I.star },
      { title: "搭配建议", desc: "专属穿搭顾问在线，一对一帮你配出整套。", icon: I.users },
      { title: "无忧退换", desc: "七天无理由退换，吊牌完好即可轻松办理。", icon: I.shield },
    ],
    servicesTitle: "热销系列",
    servicesSubtitle: "从基础百搭到设计单品，总有一款适合你。",
    services: [
      { name: "当季新品", desc: "紧跟潮流趋势，每周上新永远有惊喜。" },
      { name: "设计师系列", desc: "原创独家款，小批量限量发售。" },
      { name: "通勤基础款", desc: "百搭耐看的衬衫西装，职场首选。" },
      { name: "会员专享", desc: "积分抵现、生日礼遇、新品优先购。" },
    ],
    stats: [
      { value: "8年", label: "品牌沉淀" },
      { value: "60万+", label: "服务客户" },
      { value: "98%", label: "好评率" },
      { value: "300+", label: "原创款式/年" },
    ],
    testimonialsTitle: "她们的真实评价",
    testimonials: [
      { name: "林小姐", role: "外企白领", text: "通勤款剪裁特别利落，面料也好，同事都问我在哪买的。" },
      { name: "苏女士", role: "全职妈妈", text: "版型很显瘦，遮肉又有气质，回购好几次了。" },
      { name: "陈小姐", role: "自由职业者", text: "设计师系列真的有辨识度，穿出门很少撞衫，很喜欢。" },
    ],
    ctaTitle: "新季衣橱，从这里开始",
    ctaSubtitle: "立即添加专属穿搭顾问，领取新人专属优惠券。",
    ctaButton: "立即选购",
    contactPhone: "400-888-2001",
    contactEmail: "hello@womenswear.com",
    contactAddress: "杭州市江干区四季青服装市场 A 座 1208 室",
    footerSlogan: "她衣阁 · 让每个女孩都能优雅做自己。",
  },

  menswear: {
    brand: "致绅男装",
    heroTitle: "得体，是男人最好的名片",
    heroSubtitle: "商务正装 · 休闲精选，为每一个重要场合而生。",
    aboutTitle: "关于致绅",
    aboutBody: [
      "致绅男装专注现代都市男士的穿衣需求，从西装版型到休闲单品，以挺括的剪裁与稳重的配色，帮你在职场与生活中始终保持得体形象。",
      "我们坚持选用进口羊毛与高密棉料，配合资深裁缝的手工细节处理。十二年深耕，只为让每一位男士都能轻松穿出格调与自信。",
    ],
    featuresTitle: "为什么选择致绅",
    featuresSubtitle: "好衣服会替你开口，说出你的专业与态度。",
    features: [
      { title: "立体剪裁", desc: "贴合东方男性身形，挺括有型不松垮。", icon: I.award },
      { title: "进口面料", desc: "甄选优质羊毛与免烫棉，舒适又耐穿。", icon: I.leaf },
      { title: "免费改衣", desc: "门店专业裁缝免费修身，量体更合身。", icon: I.cog },
      { title: "成套搭配", desc: "西装、衬衫、领带一站配齐省心省力。", icon: I.star },
      { title: "商务礼遇", desc: "团购定制、企业团服专属服务方案。", icon: I.users },
      { title: "品质质保", desc: "正品保障，缝线脱开一年内免费维修。", icon: I.shield },
    ],
    servicesTitle: "产品系列",
    servicesSubtitle: "从正式到休闲，覆盖你衣橱的每一格。",
    services: [
      { name: "商务正装", desc: "修身西装套装，重要场合稳重大气。" },
      { name: "休闲系列", desc: "夹克、Polo、休闲裤，周末更松弛。" },
      { name: "衬衫专区", desc: "免烫商务衬衫，通勤出差更省心。" },
      { name: "高级定制", desc: "量体裁衣专属定制，独一无二的合身。" },
    ],
    stats: [
      { value: "12年", label: "专注男装" },
      { value: "120家", label: "线下门店" },
      { value: "50万+", label: "会员客户" },
      { value: "99%", label: "合身好评" },
    ],
    testimonialsTitle: "客户评价",
    testimonials: [
      { name: "周先生", role: "公司高管", text: "西装版型挺括又显气场，开会谈判都更有底气。" },
      { name: "高先生", role: "金融从业者", text: "免费改衣很贴心，改完特别合身，料子也很高级。" },
      { name: "马先生", role: "新郎", text: "婚礼定制西装太满意了，所有人都夸帅。" },
    ],
    ctaTitle: "为重要时刻，准备一身好行头",
    ctaSubtitle: "预约到店量体，享专属定制九折优惠。",
    ctaButton: "预约量体",
    contactPhone: "400-888-2002",
    contactEmail: "hello@menswear.com",
    contactAddress: "上海市黄浦区南京东路 558 号品牌旗舰店 3 楼",
    footerSlogan: "致绅男装 · 成就每一位绅士的从容。",
  },

  kidswear: {
    brand: "童趣岛童装",
    heroTitle: "让童年，穿得更舒服",
    heroSubtitle: "亲肤面料 · 安全无忧，陪孩子自在探索每一天。",
    aboutTitle: "关于童趣岛",
    aboutBody: [
      "童趣岛童装专为 0—12 岁孩子设计，把安全与舒适放在第一位。从纽扣松紧到缝线工艺，每个细节都按照孩子好动爱探索的天性反复打磨。",
      "我们所有面料均通过 A 类婴幼儿安全标准检测，无荧光剂、无刺激性染料。鲜亮的配色与活泼的图案，让孩子穿得开心，家长买得放心。",
    ],
    featuresTitle: "为什么选择童趣岛",
    featuresSubtitle: "孩子的衣服，每个细节都不能将就。",
    features: [
      { title: "A类安全", desc: "通过婴幼儿 A 类标准，贴身穿更放心。", icon: I.shield },
      { title: "纯棉亲肤", desc: "高支精梳棉柔软透气，呵护娇嫩肌肤。", icon: I.leaf },
      { title: "活动自如", desc: "宽松版型加弹性设计，跑跳玩耍不受束。", icon: I.bolt },
      { title: "趣味图案", desc: "原创卡通印花，激发孩子想象力。", icon: I.sparkle },
      { title: "成长尺码", desc: "细分年龄段尺码，长个换季更省心。", icon: I.chart },
      { title: "耐穿耐洗", desc: "加固缝线不易变形，反复水洗依旧鲜亮。", icon: I.award },
    ],
    servicesTitle: "产品分类",
    servicesSubtitle: "从内到外，从四季到节日，一站买齐。",
    services: [
      { name: "四季套装", desc: "春夏秋冬应季穿搭，舒适又好看。" },
      { name: "贴身内衣", desc: "A 类纯棉打底，呵护宝宝肌肤。" },
      { name: "亲子装", desc: "全家同款萌系搭配，记录温馨时光。" },
      { name: "节日礼盒", desc: "精美礼盒装，送礼弥月皆相宜。" },
    ],
    stats: [
      { value: "10年", label: "专注童装" },
      { value: "100%", label: "A类面料" },
      { value: "80万+", label: "妈妈信赖" },
      { value: "0", label: "甲醛超标" },
    ],
    testimonialsTitle: "妈妈们怎么说",
    testimonials: [
      { name: "丽丽妈妈", role: "二宝妈妈", text: "面料是真的软，宝宝穿了不红屁股不起疹，安心。" },
      { name: "桐桐妈妈", role: "上班族妈妈", text: "图案可爱质量好，洗了很多次都不变形不褪色。" },
      { name: "果果爸爸", role: "新手爸爸", text: "买了亲子装一起穿出门，回头率超高，孩子也开心。" },
    ],
    ctaTitle: "给孩子一个舒适的童年",
    ctaSubtitle: "关注公众号，新会员立享满减好礼。",
    ctaButton: "马上选购",
    contactPhone: "400-888-2003",
    contactEmail: "hello@kidswear.com",
    contactAddress: "广州市白云区童装产业园 B 栋 5 层",
    footerSlogan: "童趣岛 · 让爱与安全，伴孩子长大。",
  },

  maternity: {
    brand: "暖孕屋母婴",
    heroTitle: "用心，呵护孕育的每一刻",
    heroSubtitle: "精选母婴好物，陪伴妈妈与宝宝平安每一天。",
    aboutTitle: "关于暖孕屋",
    aboutBody: [
      "暖孕屋是一站式母婴用品品牌，从备孕、孕期到产后育儿，覆盖妈妈与宝宝的全周期需求。我们深知每一件母婴用品都关乎安全，因此对品质有近乎苛刻的要求。",
      "所有商品均来自正规渠道、可溯源批次，奶粉纸尿裤等敏感品类全程冷链与防伪验真。我们希望成为每个新家庭最值得信赖的育儿伙伴。",
    ],
    featuresTitle: "为什么选择暖孕屋",
    featuresSubtitle: "母婴无小事，我们替你层层把关。",
    features: [
      { title: "正品溯源", desc: "全品类可查批次，扫码验真假一码不漏。", icon: I.shield },
      { title: "母婴专研", desc: "育婴师选品团队，只留真正好用的。", icon: I.heart },
      { title: "安全材质", desc: "入口入眼用品严控材质，安全更省心。", icon: I.leaf },
      { title: "极速配送", desc: "区域仓就近发货，急需用品当日可达。", icon: I.truck },
      { title: "育儿指导", desc: "专业育婴顾问答疑，喂养护理不慌张。", icon: I.users },
      { title: "贴心售后", desc: "破损漏发极速理赔，购物无后顾之忧。", icon: I.award },
    ],
    servicesTitle: "热销品类",
    servicesSubtitle: "从孕妈到宝宝，所需好物一站备齐。",
    services: [
      { name: "奶粉辅食", desc: "正规渠道直采，批次可溯防伪验真。" },
      { name: "纸尿裤湿巾", desc: "亲肤透气干爽，呵护宝宝小屁屁。" },
      { name: "孕产护理", desc: "待产包、护肤、营养，孕妈贴心呵护。" },
      { name: "喂养用品", desc: "奶瓶、辅食机、消毒锅一应俱全。" },
    ],
    stats: [
      { value: "9年", label: "母婴经营" },
      { value: "5000+", label: "精选 SKU" },
      { value: "70万+", label: "新手家庭" },
      { value: "100%", label: "正品保障" },
    ],
    testimonialsTitle: "宝爸宝妈的信赖",
    testimonials: [
      { name: "悦悦妈", role: "新手妈妈", text: "奶粉都能扫码验真，买着特别安心，物流也快。" },
      { name: "豆豆妈", role: "全职妈妈", text: "客服里有育婴师，半夜问喂养问题都耐心回复。" },
      { name: "team 爸", role: "二胎爸爸", text: "纸尿裤干爽不漏，囤货价格也很实在，会一直买。" },
    ],
    ctaTitle: "给宝宝最好的开始",
    ctaSubtitle: "注册即送新手大礼包，孕育路上不孤单。",
    ctaButton: "立即逛逛",
    contactPhone: "400-888-2004",
    contactEmail: "hello@maternity.com",
    contactAddress: "成都市武侯区母婴产业基地 2 号楼 6 层",
    footerSlogan: "暖孕屋 · 陪你温柔迎接每个新生命。",
  },

  shoes: {
    brand: "步履坊鞋业",
    heroTitle: "每一步，都踏实舒适",
    heroSubtitle: "精选好鞋 · 舒适与时尚兼得，陪你走更远的路。",
    aboutTitle: "关于步履坊",
    aboutBody: [
      "步履坊专注于舒适型鞋履的研发与销售，从鞋楦设计到鞋底回弹，我们用人体工学的标准衡量每一双鞋，让好看与好穿不再二选一。",
      "无论是商务皮鞋、休闲运动还是日常通勤，我们都坚持选用透气的优质材料与缓震科技鞋底。十五年制鞋经验，只为让你的每一步都轻盈有力。",
    ],
    featuresTitle: "为什么选择步履坊",
    featuresSubtitle: "一双好鞋，是对双脚最实在的善待。",
    features: [
      { title: "人体工学", desc: "贴合足弓的鞋楦设计，久站久走不累脚。", icon: I.award },
      { title: "缓震鞋底", desc: "高回弹中底科技，每一步都轻盈减压。", icon: I.bolt },
      { title: "透气材质", desc: "网面与头层牛皮，闷热天气依旧干爽。", icon: I.leaf },
      { title: "防滑耐磨", desc: "深纹大底抓地力强，雨天路面也安心。", icon: I.shield },
      { title: "尺码齐全", desc: "细分尺码与多种楦型，宽脚也能合脚。", icon: I.chart },
      { title: "潮流款式", desc: "紧跟当季流行，舒适也能很时髦。", icon: I.star },
    ],
    servicesTitle: "鞋履系列",
    servicesSubtitle: "上班、运动、休闲，每个场景都有对的鞋。",
    services: [
      { name: "商务皮鞋", desc: "真皮材质显档次，正装通勤百搭。" },
      { name: "运动跑鞋", desc: "轻量缓震科技，运动出行更自在。" },
      { name: "休闲板鞋", desc: "百搭潮流造型，日常穿搭神器。" },
      { name: "舒适凉鞋", desc: "夏季透气清爽，软底踩屎感十足。" },
    ],
    stats: [
      { value: "15年", label: "制鞋经验" },
      { value: "200万+", label: "双售出" },
      { value: "97%", label: "舒适好评" },
      { value: "36-46", label: "全尺码覆盖" },
    ],
    testimonialsTitle: "顾客真实反馈",
    testimonials: [
      { name: "刘先生", role: "销售经理", text: "皮鞋穿一整天都不挤脚，软乎乎的，谈客户很有面子。" },
      { name: "韩女士", role: "跑步爱好者", text: "跑鞋回弹很好，膝盖压力小了不少，性价比超高。" },
      { name: "赵同学", role: "在校学生", text: "板鞋好看又好穿，同学都来问链接，已回购。" },
    ],
    ctaTitle: "换双好鞋，善待你的双脚",
    ctaSubtitle: "下单立享免费试穿，不合脚轻松退换。",
    ctaButton: "选购好鞋",
    contactPhone: "400-888-2005",
    contactEmail: "hello@shoes.com",
    contactAddress: "温州市鹿城区鞋革城 C 区 18 号",
    footerSlogan: "步履坊 · 让每一步都踏实而轻盈。",
  },

  bags: {
    brand: "栖包箱包",
    heroTitle: "好包，承载你的每一次出发",
    heroSubtitle: "精工箱包 · 实用与质感并存，陪你走南闯北。",
    aboutTitle: "关于栖包",
    aboutBody: [
      "栖包专注箱包设计与制造，从通勤背包到旅行拉杆箱，我们以耐用与实用为核心，让每一只包都能扛得住长途奔波，也配得上你的品味。",
      "甄选头层皮与高密尼龙面料，搭配静音万向轮与加固拉链，经过反复负重与拖行测试。我们相信，一只好包应当是值得托付多年的旅途伙伴。",
    ],
    featuresTitle: "为什么选择栖包",
    featuresSubtitle: "好包不只是颜值，更要经得起折腾。",
    features: [
      { title: "耐磨面料", desc: "高密防泼水材质，刮蹭雨淋都不怕。", icon: I.shield },
      { title: "精工五金", desc: "加固拉链与扣件，反复开合不卡顿。", icon: I.cog },
      { title: "静音万向轮", desc: "拉杆箱顺滑静音，机场赶路更从容。", icon: I.bolt },
      { title: "合理收纳", desc: "多隔层分区设计，物品分类一目了然。", icon: I.chart },
      { title: "轻量背负", desc: "减压肩带与轻盈箱体，久背久拖不累。", icon: I.leaf },
      { title: "质感外观", desc: "简约百搭设计，商务休闲都拿得出手。", icon: I.star },
    ],
    servicesTitle: "产品系列",
    servicesSubtitle: "通勤、旅行、出差，总有一只适合你。",
    services: [
      { name: "商务背包", desc: "笔记本防护隔层，通勤出差好搭档。" },
      { name: "旅行拉杆箱", desc: "静音万向轮，大容量耐摔耐拖。" },
      { name: "真皮手袋", desc: "头层牛皮工艺，质感出席更得体。" },
      { name: "户外双肩包", desc: "大容量防泼水，登山徒步好帮手。" },
    ],
    stats: [
      { value: "13年", label: "箱包专研" },
      { value: "150万+", label: "全球用户" },
      { value: "98%", label: "耐用好评" },
      { value: "5年", label: "五金质保" },
    ],
    testimonialsTitle: "用户口碑",
    testimonials: [
      { name: "钱先生", role: "出差党", text: "拉杆箱拖了两年轮子还很顺，扛造，出差离不开它。" },
      { name: "孙女士", role: "背包客", text: "户外包背负系统很舒服，装得多还不压肩，赞。" },
      { name: "吴先生", role: "上班族", text: "电脑包看着低调又有质感，隔层多放东西很方便。" },
    ],
    ctaTitle: "为下一场旅途，挑只好包",
    ctaSubtitle: "全场顺丰包邮，支持一年内五金免费维修。",
    ctaButton: "立即选购",
    contactPhone: "400-888-2006",
    contactEmail: "hello@bags.com",
    contactAddress: "广州市花都区狮岭皮具城 D 馆 32 号",
    footerSlogan: "栖包 · 陪你装下世界，奔赴远方。",
  },

  jewelry: {
    brand: "瑾辰珠宝",
    heroTitle: "每一件，都值得珍藏",
    heroSubtitle: "甄选高品质珠宝，记录人生每一个闪耀时刻。",
    aboutTitle: "关于瑾辰",
    aboutBody: [
      "瑾辰珠宝甄选每一颗钻石与每一克黄金，从原料采购到镶嵌工艺层层把关。我们相信珠宝不仅是装饰，更是承载情感与记忆的传家信物。",
      "门店配备专业鉴定师与定制设计团队，所有钻石均附国际权威证书，黄金足量足金、明码标价。二十年匠心，只为见证你人生中每一个珍贵时刻。",
    ],
    featuresTitle: "为什么选择瑾辰",
    featuresSubtitle: "买珠宝，认准证书与工艺，更要认准放心。",
    features: [
      { title: "权威认证", desc: "钻石附 GIA 国际证书，品质有据可查。", icon: I.shield },
      { title: "足金足量", desc: "黄金克重明码标价，称重透明不缺斤。", icon: I.award },
      { title: "精湛镶嵌", desc: "资深匠师手工镶嵌，牢固又显火彩。", icon: I.sparkle },
      { title: "专属定制", desc: "婚戒纪念款独家设计，刻字寄托心意。", icon: I.heart },
      { title: "终身养护", desc: "免费清洗、检测、改款，常戴常新。", icon: I.cog },
      { title: "保值回购", desc: "黄金支持回购置换，资产灵活有保障。", icon: I.chart },
    ],
    servicesTitle: "产品系列",
    servicesSubtitle: "从日常佩戴到人生大事，皆有所托。",
    services: [
      { name: "钻石定制", desc: "GIA 认证裸钻，专属婚戒一对一设计。" },
      { name: "黄金饰品", desc: "足金工艺，保值传承送礼皆宜。" },
      { name: "婚嫁系列", desc: "对戒、项链、套链，见证浪漫爱情。" },
      { name: "翻新维修", desc: "专业清洗、改款、修复，焕新如初。" },
    ],
    stats: [
      { value: "20年", label: "珠宝世家" },
      { value: "100%", label: "证书可查" },
      { value: "30万+", label: "珍藏客户" },
      { value: "终身", label: "免费养护" },
    ],
    testimonialsTitle: "客户的心声",
    testimonials: [
      { name: "顾女士", role: "准新娘", text: "定制婚戒太美了，火彩特别足，证书一应俱全，安心。" },
      { name: "郑先生", role: "求婚者", text: "设计师把我的想法实现得很好，求婚成功了，谢谢瑾辰。" },
      { name: "冯女士", role: "回头客", text: "金饰明码标价不忽悠，旧款还能免费改新款，很贴心。" },
    ],
    ctaTitle: "为珍贵时刻，挑一件传世之礼",
    ctaSubtitle: "预约到店鉴赏，专属顾问为你私享定制。",
    ctaButton: "预约鉴赏",
    contactPhone: "400-888-2007",
    contactEmail: "hello@jewelry.com",
    contactAddress: "深圳市罗湖区水贝珠宝交易中心 6 楼",
    footerSlogan: "瑾辰珠宝 · 珍藏每一个闪耀的心动。",
  },

  glasses: {
    brand: "明视眼镜",
    heroTitle: "看清世界，也看见品味",
    heroSubtitle: "专业验光 · 时尚镜框，给眼睛更舒适的选择。",
    aboutTitle: "关于明视",
    aboutBody: [
      "明视眼镜专注视光健康与眼镜配制，配备医学级验光设备与专业视光师团队，为每一位顾客提供精准、舒适、个性化的配镜方案。",
      "从镜片折射率到镜框贴合度，我们都严格把控，尤其重视青少年近视防控与中老年渐进多焦的科学配镜。让你看得清晰，也戴得舒适、出得体面。",
    ],
    featuresTitle: "为什么选择明视",
    featuresSubtitle: "配镜是医学验配，不是随便挑个框。",
    features: [
      { title: "医学验光", desc: "21 步精准验光，度数瞳距一丝不差。", icon: I.chart },
      { title: "正品镜片", desc: "进口品牌镜片，防蓝光防紫外更护眼。", icon: I.shield },
      { title: "近视防控", desc: "青少年离焦镜片，科学延缓度数增长。", icon: I.heart },
      { title: "时尚镜框", desc: "百款潮流镜框，轻盈舒适显脸小。", icon: I.star },
      { title: "免费调校", desc: "终身免费清洗调整与螺丝鼻托更换。", icon: I.cog },
      { title: "快速取镜", desc: "门店现场磨片，常规度数当天可取。", icon: I.bolt },
    ],
    servicesTitle: "服务项目",
    servicesSubtitle: "从儿童到长辈，全家视力都被照顾到。",
    services: [
      { name: "专业验光", desc: "医学级设备，精准检测视力状况。" },
      { name: "近视配镜", desc: "防蓝光防控镜片，舒适清晰持久。" },
      { name: "渐进多焦", desc: "中老年看远看近，一副镜片搞定。" },
      { name: "隐形美瞳", desc: "正规品牌日抛月抛，安全更养眼。" },
    ],
    stats: [
      { value: "16年", label: "视光经验" },
      { value: "21步", label: "精准验光" },
      { value: "40万+", label: "配镜顾客" },
      { value: "终身", label: "免费调校" },
    ],
    testimonialsTitle: "顾客评价",
    testimonials: [
      { name: "卫先生", role: "程序员", text: "防蓝光镜片戴着眼睛舒服多了，验光也比别家细致。" },
      { name: "蒋女士", role: "学生家长", text: "给孩子配的离焦镜，半年复查度数没怎么涨，放心。" },
      { name: "沈先生", role: "退休教师", text: "渐进多焦适应得很快，看书看路都清楚，很满意。" },
    ],
    ctaTitle: "给眼睛一次专业的呵护",
    ctaSubtitle: "预约免费验光，到店即享镜框立减优惠。",
    ctaButton: "预约验光",
    contactPhone: "400-888-2008",
    contactEmail: "hello@glasses.com",
    contactAddress: "南京市秦淮区新街口商业大厦 2 层 218 室",
    footerSlogan: "明视眼镜 · 让你看清世界的每个细节。",
  },

  watches: {
    brand: "时光阁名表",
    heroTitle: "腕上时光，品味之选",
    heroSubtitle: "精选机械与时尚腕表，让时间也成为风格。",
    aboutTitle: "关于时光阁",
    aboutBody: [
      "时光阁专营品牌腕表，从经典机械到时尚石英，每一只都经过专业鉴定与精准走时校验。我们深知，腕表不只是计时工具，更是男人腕间的品味象征。",
      "门店设有专业制表师工作台，提供洗油保养、换电防水、表带调节等全套服务。十八年专注，只为让每一只腕表都精准如初、陪你度过悠长岁月。",
    ],
    featuresTitle: "为什么选择时光阁",
    featuresSubtitle: "买表与养表，都该交给懂表的人。",
    features: [
      { title: "正品鉴真", desc: "专业鉴定开箱验机，杜绝仿表翻新。", icon: I.shield },
      { title: "精准走时", desc: "出库前逐只校时调校，误差严格把控。", icon: I.clock },
      { title: "专业保养", desc: "制表师手工洗油保养，机芯历久如新。", icon: I.cog },
      { title: "品类齐全", desc: "机械、石英、智能腕表多元任你选。", icon: I.star },
      { title: "全国联保", desc: "正规渠道行货，享品牌官方质保。", icon: I.award },
      { title: "免费调节", desc: "表带表链免费调长短，佩戴更合腕。", icon: I.bolt },
    ],
    servicesTitle: "服务项目",
    servicesSubtitle: "从选购到养护，给你的腕表全程守护。",
    services: [
      { name: "品牌腕表", desc: "经典机械与时尚款，行货正品联保。" },
      { name: "维修保养", desc: "洗油、换电、防水检测一站完成。" },
      { name: "二手回收", desc: "名表评估回收置换，价格公道透明。" },
      { name: "表带定制", desc: "真皮钢带任选，量腕定制更贴合。" },
    ],
    stats: [
      { value: "18年", label: "钟表经营" },
      { value: "100%", label: "正品行货" },
      { value: "25万+", label: "藏表客户" },
      { value: "全国", label: "联保服务" },
    ],
    testimonialsTitle: "藏家口碑",
    testimonials: [
      { name: "褚先生", role: "腕表爱好者", text: "买表当面验机很专业，走时很准，保养手艺也好。" },
      { name: "卫女士", role: "礼品买家", text: "给先生买的生日礼物，正品联保，服务很到位。" },
      { name: "曹先生", role: "老客户", text: "老表拿来洗油，焕然一新还很准，以后就认这家了。" },
    ],
    ctaTitle: "为腕间，添一份从容时光",
    ctaSubtitle: "到店免费检测走时，老表保养享专属折扣。",
    ctaButton: "预约到店",
    contactPhone: "400-888-2009",
    contactEmail: "hello@watches.com",
    contactAddress: "北京市朝阳区国贸商城 LG2 层 K18 铺",
    footerSlogan: "时光阁 · 让每一刻，都走得精准从容。",
  },

  hairsalon: {
    brand: "尚剪造型",
    heroTitle: "好发型，是最好的整容",
    heroSubtitle: "资深发型师 · 私人定制，从发丝开始焕新自己。",
    aboutTitle: "关于尚剪",
    aboutBody: [
      "尚剪造型是一家专注剪、烫、染与头皮护理的精致美发沙龙。我们坚持以脸型、发质与气质为依据，为每一位顾客量身设计最适合的发型方案。",
      "店内所选染烫产品均为低敏环保品牌，发型师团队定期赴一线进修流行技艺。我们希望你每次走出店门，都能带着满意的发型和好心情。",
    ],
    featuresTitle: "为什么选择尚剪",
    featuresSubtitle: "发型师懂你的脸，也懂你的气质。",
    features: [
      { title: "量脸设计", desc: "依脸型气质定制发型，扬长避短更出彩。", icon: I.sparkle },
      { title: "资深团队", desc: "总监级发型师坐镇，技艺纯熟有审美。", icon: I.award },
      { title: "低敏产品", desc: "环保染烫膏温和护发，孕妇也安心。", icon: I.leaf },
      { title: "头皮养护", desc: "深层清洁与养护，改善出油与脱发。", icon: I.heart },
      { title: "舒适环境", desc: "私密包间与暖心服务，理发也是享受。", icon: I.star },
      { title: "效果跟踪", desc: "回家不会打理可回店免费指导。", icon: I.users },
    ],
    servicesTitle: "服务项目",
    servicesSubtitle: "从日常打理到造型蜕变，全程为你设计。",
    services: [
      { name: "精剪造型", desc: "总监量脸设计，剪出适合你的发型。" },
      { name: "时尚烫染", desc: "低敏环保产品，烫染出当季流行色。" },
      { name: "头皮护理", desc: "深层清洁养护，缓解出油防脱发。" },
      { name: "新娘造型", desc: "婚礼妆发整体设计，美得恰到好处。" },
    ],
    stats: [
      { value: "12年", label: "沙龙品牌" },
      { value: "15位", label: "资深发型师" },
      { value: "10万+", label: "回头顾客" },
      { value: "96%", label: "满意复购" },
    ],
    testimonialsTitle: "顾客好评",
    testimonials: [
      { name: "薇薇", role: "白领", text: "总监根据我脸型剪的，显脸小又好打理，太喜欢了。" },
      { name: "Lina", role: "宝妈", text: "染的颜色很高级，产品味道也不冲，头皮不刺激。" },
      { name: "小满", role: "准新娘", text: "婚礼当天的妆发美哭了，全程跟妆很专业，强推。" },
    ],
    ctaTitle: "换个发型，换个心情",
    ctaSubtitle: "新客到店首剪享八折，关注即送护理体验。",
    ctaButton: "在线预约",
    contactPhone: "400-888-2010",
    contactEmail: "hello@hairsalon.com",
    contactAddress: "武汉市江汉区江汉路步行街 88 号 2 楼",
    footerSlogan: "尚剪造型 · 由内而外，剪出更好的你。",
  },

  nails: {
    brand: "甲悦美甲美睫",
    heroTitle: "指尖与睫毛间的小确幸",
    heroSubtitle: "美甲 · 美睫 · 手足护理，精致从细节开始。",
    aboutTitle: "关于甲悦",
    aboutBody: [
      "甲悦专注美甲、美睫与手足护理，为追求精致的女性打造指尖与眼眸间的优雅。从款式设计到上色嫁接，每一处细节都用心雕琢。",
      "我们坚持一客一消毒、一人一套工具，所选甲油胶与睫毛胶均为可送检的低敏品牌。安心、卫生、好看，是我们对每位顾客的承诺。",
    ],
    featuresTitle: "为什么选择甲悦",
    featuresSubtitle: "美得精致，也要美得卫生安心。",
    features: [
      { title: "严格消毒", desc: "一客一消毒、工具高温灭菌更安心。", icon: I.shield },
      { title: "低敏材料", desc: "甲油胶睫毛胶可送检，敏感人群无忧。", icon: I.leaf },
      { title: "原创款式", desc: "海量当季流行款，也可私人定制图案。", icon: I.sparkle },
      { title: "持久不脱", desc: "专业封层与嫁接手法，美得更长久。", icon: I.clock },
      { title: "手足养护", desc: "去死皮、滋养护理，双手双脚更细嫩。", icon: I.heart },
      { title: "舒适体验", desc: "环境温馨、手法轻柔，做美甲像享受。", icon: I.star },
    ],
    servicesTitle: "服务项目",
    servicesSubtitle: "从指尖到睫毛，全方位的精致护理。",
    services: [
      { name: "时尚美甲", desc: "当季流行款，原创设计随心选。" },
      { name: "睫毛嫁接", desc: "自然浓密多种款式，放大双眼神采。" },
      { name: "手足护理", desc: "去角质滋养，双手双脚柔嫩细滑。" },
      { name: "美甲卸甲", desc: "专业温和卸甲，不伤甲面更健康。" },
    ],
    stats: [
      { value: "8年", label: "门店经营" },
      { value: "1对1", label: "工具消毒" },
      { value: "6万+", label: "精致顾客" },
      { value: "500+", label: "原创款式" },
    ],
    testimonialsTitle: "顾客评价",
    testimonials: [
      { name: "甜甜", role: "上班族", text: "款式特别多又好看，做得很仔细，一个月都不脱色。" },
      { name: "Coco", role: "美妆博主", text: "睫毛嫁接得很自然，根根分明不扎眼，回购很多次。" },
      { name: "阿May", role: "准新娘", text: "卫生做得很到位，工具都是单独消毒的，放心。" },
    ],
    ctaTitle: "宠爱自己，从指尖开始",
    ctaSubtitle: "新客体验价超划算，办卡更享多重好礼。",
    ctaButton: "立即预约",
    contactPhone: "400-888-2011",
    contactEmail: "hello@nails.com",
    contactAddress: "苏州市姑苏区观前街美护广场 3 楼 305",
    footerSlogan: "甲悦 · 把精致，藏进每个小细节。",
  },

  makeup: {
    brand: "悦颜美妆",
    heroTitle: "美，由你定义",
    heroSubtitle: "甄选全球美妆好物，唤醒你的每一面光彩。",
    aboutTitle: "关于悦颜",
    aboutBody: [
      "悦颜美妆甄选全球品牌彩妆与护肤好物，以成分透明、正品可溯为底线，帮每一位爱美的你找到真正适合自己的那一款。",
      "我们组建了专业的美妆顾问与肤质测评团队，从底妆到护肤循序推荐，拒绝盲目跟风。让护肤更科学、上妆更精致，做真实而自信的自己。",
    ],
    featuresTitle: "为什么选择悦颜",
    featuresSubtitle: "护肤上妆，认成分、认正品、认适合。",
    features: [
      { title: "全球正品", desc: "品牌授权可溯源，假一赔十买着安心。", icon: I.shield },
      { title: "成分透明", desc: "标注核心成分功效，理性护肤不踩雷。", icon: I.leaf },
      { title: "肤质测评", desc: "AI 肤质分析，精准匹配适合的产品。", icon: I.chart },
      { title: "全线齐全", desc: "底妆、彩妆、护肤一站购齐更省心。", icon: I.cart },
      { title: "美妆课堂", desc: "专业化妆师线上线下教你妆容技巧。", icon: I.users },
      { title: "贴心小样", desc: "热门单品赠送试用，先试后买不浪费。", icon: I.heart },
    ],
    servicesTitle: "热销品类",
    servicesSubtitle: "由内养肤、由外修颜，一站搞定。",
    services: [
      { name: "彩妆系列", desc: "底妆、唇彩、眼影全线热门齐全。" },
      { name: "护肤精选", desc: "成分党之选，温和高效见效果。" },
      { name: "美妆课堂", desc: "专业化妆师线上线下手把手教学。" },
      { name: "肤质测评", desc: "AI 肤质分析，精准选品不踩坑。" },
    ],
    stats: [
      { value: "10年", label: "美妆经营" },
      { value: "3000+", label: "正品 SKU" },
      { value: "90万+", label: "爱美用户" },
      { value: "100%", label: "正品保障" },
    ],
    testimonialsTitle: "用户口碑",
    testimonials: [
      { name: "可可", role: "学生党", text: "顾问按我的肤质推荐，没乱推贵的，用着很合适。" },
      { name: "Yuki", role: "职场新人", text: "正品有保障，赠的小样也很实用，上妆课很涨知识。" },
      { name: "莉莉", role: "宝妈", text: "护肤品成分讲得很清楚，敏感肌也敢用，回购了。" },
    ],
    ctaTitle: "遇见更有光彩的自己",
    ctaSubtitle: "免费领取肤质测评，新人专享美妆大礼包。",
    ctaButton: "免费测肤",
    contactPhone: "400-888-2012",
    contactEmail: "hello@makeup.com",
    contactAddress: "上海市静安区南京西路美妆旗舰中心 4 层",
    footerSlogan: "悦颜美妆 · 让美，回归真实与自信。",
  },

  slimming: {
    brand: "轻盈纤体",
    heroTitle: "遇见更轻盈的自己",
    heroSubtitle: "科学纤体 · 健康管理，不节食也能塑形成功。",
    aboutTitle: "关于轻盈",
    aboutBody: [
      "轻盈纤体倡导科学、健康、可持续的体重管理理念。我们拒绝极端节食与伤身减肥，通过专业评估、仪器塑形与饮食运动指导，帮你健康瘦下来、稳稳不反弹。",
      "门店配备体脂检测与专业塑形仪器，由健康管理师为每位会员制定个性化方案。我们追求的不只是体重数字，更是健康、紧致、自信的身体状态。",
    ],
    featuresTitle: "为什么选择轻盈",
    featuresSubtitle: "瘦下来不难，难的是健康瘦、不反弹。",
    features: [
      { title: "科学评估", desc: "体脂围度全面检测，方案因人而异。", icon: I.chart },
      { title: "健康塑形", desc: "不节食不伤身，循序渐进更稳妥。", icon: I.heart },
      { title: "专业仪器", desc: "正规塑形设备，针对局部精准管理。", icon: I.cog },
      { title: "饮食指导", desc: "营养师定制食谱，吃饱也能瘦下来。", icon: I.leaf },
      { title: "一对一陪伴", desc: "专属管理师全程跟踪督促不松劲。", icon: I.users },
      { title: "防反弹", desc: "巩固期长期跟进，瘦下来稳得住。", icon: I.shield },
    ],
    servicesTitle: "服务项目",
    servicesSubtitle: "从评估到巩固，全周期陪你瘦下来。",
    services: [
      { name: "体脂评估", desc: "专业检测体成分，找到肥胖根源。" },
      { name: "局部塑形", desc: "针对腰腹腿臀，精准雕塑曲线。" },
      { name: "饮食管理", desc: "营养师定制食谱，科学控热量。" },
      { name: "巩固防反弹", desc: "瘦后长期跟踪，养成易瘦体质。" },
    ],
    stats: [
      { value: "11年", label: "纤体经验" },
      { value: "5万+", label: "成功案例" },
      { value: "95%", label: "不反弹率" },
      { value: "1对1", label: "专属管理" },
    ],
    testimonialsTitle: "会员见证",
    testimonials: [
      { name: "晓静", role: "产后妈妈", text: "三个月瘦了 18 斤，没饿肚子，肚子也紧致了，神奇。" },
      { name: "大鹏", role: "上班族", text: "管理师特别负责，饮食运动都安排好，瘦得很踏实。" },
      { name: "婷婷", role: "教师", text: "之前减了反弹，这次巩固期跟得很紧，半年没反弹。" },
    ],
    ctaTitle: "开启你的健康瘦身计划",
    ctaSubtitle: "预约免费体脂检测，专属方案当场出。",
    ctaButton: "免费评估",
    contactPhone: "400-888-2013",
    contactEmail: "hello@slimming.com",
    contactAddress: "重庆市渝中区解放碑健康管理中心 12 楼",
    footerSlogan: "轻盈纤体 · 科学塑形，瘦出健康自信。",
  },

  "medical-beauty": {
    brand: "瑷美医疗美容",
    heroTitle: "让美，更有医学的底气",
    heroSubtitle: "正规医美机构 · 专业医师团队，安全变美更安心。",
    aboutTitle: "关于瑷美",
    aboutBody: [
      "瑷美医疗美容是经卫生主管部门审批的正规医美机构，拥有合规的医疗资质与执业医师团队。我们坚持医疗的严谨与审美的克制，让每一次变美都建立在安全之上。",
      "从面诊评估到术后随访，我们提供全流程闭环管理，所用药品器械均正规可溯。我们追求的不是千篇一律的网红脸，而是适合你的、自然耐看的美。",
    ],
    featuresTitle: "为什么选择瑷美",
    featuresSubtitle: "医美是医疗，安全与资质永远第一位。",
    features: [
      { title: "正规资质", desc: "持证医疗机构，执业医师持证操作。", icon: I.shield },
      { title: "专业面诊", desc: "一对一深度面诊，方案克制不过度。", icon: I.users },
      { title: "正品药械", desc: "药品器械正规可溯，扫码验真放心。", icon: I.award },
      { title: "自然审美", desc: "因人设计自然耐看，拒绝网红流水线。", icon: I.sparkle },
      { title: "无菌环境", desc: "标准手术净化层流，规范严控感染。", icon: I.heart },
      { title: "术后随访", desc: "全程跟踪恢复，贴心回访不撒手。", icon: I.clock },
    ],
    servicesTitle: "项目分类",
    servicesSubtitle: "皮肤、轮廓、抗衰，专业医师为你把关。",
    services: [
      { name: "皮肤管理", desc: "光电祛斑嫩肤，改善肤质更透亮。" },
      { name: "注射微整", desc: "玻尿酸、肉毒素，正品微调更自然。" },
      { name: "抗衰紧致", desc: "射频提拉除皱，对抗松弛显年轻。" },
      { name: "毛发管理", desc: "激光脱毛与植发，专业精细更持久。" },
    ],
    stats: [
      { value: "14年", label: "医美深耕" },
      { value: "100%", label: "正规资质" },
      { value: "20万+", label: "变美顾客" },
      { value: "全程", label: "术后随访" },
    ],
    testimonialsTitle: "真实顾客分享",
    testimonials: [
      { name: "M女士", role: "白领", text: "面诊医生很负责，没推一堆项目，做完皮肤透亮很自然。" },
      { name: "J先生", role: "企业主", text: "证件资质都齐全，药品能扫码验真，做着踏实安心。" },
      { name: "K小姐", role: "教师", text: "抗衰项目效果自然，恢复期回访很及时，体验很好。" },
    ],
    ctaTitle: "把变美这件事，交给专业",
    ctaSubtitle: "预约资深医师面诊，定制专属变美方案。",
    ctaButton: "预约面诊",
    contactPhone: "400-888-2014",
    contactEmail: "hello@medical-beauty.com",
    contactAddress: "成都市锦江区春熙路医美大厦 8—10 层",
    footerSlogan: "瑷美 · 以医学之名，护航你的美。",
  },
};
