import type { ContentMap } from "./_types";
import { I } from "./_types";

export const FOOD_CONTENT: ContentMap = {
  fastfood: {
    heroTitle: "热乎现做，快人一步",
    heroSubtitle: "地道小吃快餐，现点现做，好吃不用等。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注街头地道风味的小吃快餐品牌，从一碗面、一份盖饭到招牌小吃，坚持每日现做现卖、足量实惠。",
      "明厨亮灶、出餐迅速，无论是赶时间的上班族还是放学的学生党，都能在这里几分钟吃上一口热乎扎实的家常好味。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让快餐也吃得舒坦。",
    features: [
      { title: "现点现做", desc: "拒绝隔夜回锅，热乎出餐才好吃。", icon: I.bolt },
      { title: "出餐神速", desc: "高峰也不久等，几分钟就上桌。", icon: I.clock },
      { title: "足量实惠", desc: "分量管饱价格亲民，吃得满足。", icon: I.heart },
      { title: "明厨亮灶", desc: "后厨全透明，干净卫生看得见。", icon: I.shield },
      { title: "选材新鲜", desc: "每日采购当日用完，新鲜不囤货。", icon: I.leaf },
      { title: "外卖到家", desc: "全平台外卖，热乎送到家门口。", icon: I.cart },
    ],
    servicesTitle: "招牌出品",
    servicesSubtitle: "总有一款是你的心头好。",
    services: [
      { name: "招牌盖饭", desc: "现炒浇头浇在热米饭上，香气扑鼻。" },
      { name: "手工面食", desc: "现煮现拌，劲道爽滑汤头浓香。" },
      { name: "特色小吃", desc: "煎炸卤味多样组合，解馋过瘾。" },
      { name: "套餐搭配", desc: "主食饮品成套优惠，一人食友好。" },
    ],
    stats: [
      { value: "6分钟", label: "平均出餐" },
      { value: "10年", label: "老店口碑" },
      { value: "50+", label: "在售单品" },
      { value: "98%", label: "复购好评" },
    ],
    testimonialsTitle: "食客怎么说",
    testimonials: [
      { name: "小王", role: "附近白领", text: "中午就靠它续命，出餐快分量足，吃完精神满满下午不犯困。" },
      { name: "阿强", role: "学生党", text: "便宜又好吃，盖饭浇头给得特别足，几乎天天打卡。" },
      { name: "刘姐", role: "外卖常客", text: "外卖送到还是热乎的，包装也干净，工作日的午餐救星。" },
    ],
    ctaTitle: "到店或下单尝一口",
    ctaSubtitle: "现在下单，热乎好味马上安排。",
    ctaButton: "立即点餐",
    contactPhone: "400-888-4001",
    contactEmail: "hello@fastfood.com",
    contactAddress: "长沙市芙蓉区五一大道 168 号小吃街",
    footerSlogan: "现做现卖，把热乎的实在端给你。",
  },

  hotpot: {
    heroTitle: "一锅沸腾，温暖相聚",
    heroSubtitle: "精选食材 · 秘制锅底，每一筷都是地道好味道。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家主打地道川味的火锅品牌，秘制锅底以数十种香料慢熬而成，香辣醇厚、回味不燥，越煮越有味。",
      "鲜货每日现切现摆、毛肚虾滑现打现上，搭配宽敞舒适的环境与热情周到的服务，把红火热闹的相聚时光端上桌。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让这顿火锅吃得尽兴。",
    features: [
      { title: "秘制锅底", desc: "多味慢熬底料，香辣鲜醇不上火。", icon: I.bolt },
      { title: "鲜切现摆", desc: "肉品蔬菜每日现切，新鲜看得见。", icon: I.leaf },
      { title: "毛肚现打", desc: "毛肚虾滑现点现做，脆嫩弹牙。", icon: I.sparkle },
      { title: "贴心服务", desc: "围裙手机套小料台，细节都到位。", icon: I.heart },
      { title: "舒适包厢", desc: "宽敞包间聚会首选，热闹不打扰。", icon: I.users },
      { title: "食安卫生", desc: "餐具高温消毒，后厨干净有保障。", icon: I.shield },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "从锅底到食材，处处用心。",
    services: [
      { name: "招牌锅底", desc: "秘制牛油与清汤可选，香辣鲜醇任挑。" },
      { name: "鲜切食材", desc: "毛肚黄喉鲜虾滑，每日现切现上。" },
      { name: "包厢预订", desc: "大小包间灵活，朋友家庭聚会无忧。" },
      { name: "外卖到家", desc: "火锅食材锅底打包，在家也能涮。" },
    ],
    stats: [
      { value: "15年", label: "火锅老味" },
      { value: "30+", label: "鲜货品类" },
      { value: "200桌", label: "宴客容量" },
      { value: "99%", label: "回头率" },
    ],
    testimonialsTitle: "食客怎么说",
    testimonials: [
      { name: "陈先生", role: "老顾客", text: "锅底是真的香，越涮越入味，毛肚脆得很，每次聚会都选这家。" },
      { name: "林女士", role: "家庭聚餐", text: "包厢宽敞热闹，服务员手脚麻利还会帮忙涮菜，带孩子也方便。" },
      { name: "赵先生", role: "朋友聚会", text: "鲜切肉品分量足又新鲜，氛围一上来根本停不下筷子。" },
    ],
    ctaTitle: "预订今晚这顿火锅",
    ctaSubtitle: "在线订座享专属优惠，相聚不排队。",
    ctaButton: "立即订座",
    contactPhone: "400-888-4002",
    contactEmail: "hello@hotpot.com",
    contactAddress: "成都市武侯区一环路南二段 9 号美食广场",
    footerSlogan: "一锅热辣，涮出热气腾腾的相聚。",
  },

  western: {
    heroTitle: "一刀一叉，品味精致时光",
    heroSubtitle: "经典西餐 · 主厨牛排 · 红酒佐餐，营造浪漫用餐体验。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家主打经典与现代融合的西餐厅，由海外研修归来的主厨掌勺，精选进口牛排与时令食材，用心呈现每一道料理。",
      "从优雅的环境、考究的摆盘到细致的桌边服务，我们希望每一次到来，都能成为一段值得纪念的精致用餐时光。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让每一餐都仪式感满满。",
    features: [
      { title: "主厨出品", desc: "资深主厨掌勺，火候摆盘皆讲究。", icon: I.award },
      { title: "进口食材", desc: "精选进口牛排海鲜，品质有保障。", icon: I.shield },
      { title: "甄选酒单", desc: "侍酒师推荐佐餐酒，餐酒更相宜。", icon: I.star },
      { title: "优雅环境", desc: "格调灯光与轻音乐，氛围满分。", icon: I.sparkle },
      { title: "桌边服务", desc: "细致专业的服务，全程舒适体贴。", icon: I.heart },
      { title: "纪念定制", desc: "求婚生日惊喜定制，留下美好回忆。", icon: I.users },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "从前菜到甜点，环环精致。",
    services: [
      { name: "主厨牛排", desc: "精选部位现煎，外焦里嫩汁水丰盈。" },
      { name: "经典前菜", desc: "沙拉浓汤与开胃小食，开启味蕾。" },
      { name: "红酒佐餐", desc: "侍酒师甄选，餐酒搭配相得益彰。" },
      { name: "纪念套餐", desc: "求婚生日主题套餐，浪漫有惊喜。" },
    ],
    stats: [
      { value: "12年", label: "西餐积淀" },
      { value: "5星", label: "环境评分" },
      { value: "100+", label: "酒单选择" },
      { value: "98%", label: "顾客满意" },
    ],
    testimonialsTitle: "食客怎么说",
    testimonials: [
      { name: "苏女士", role: "纪念日顾客", text: "牛排火候完美，桌边服务很贴心，主厨还为我们准备了惊喜甜点，超浪漫。" },
      { name: "何先生", role: "商务宴请", text: "环境优雅有格调，菜品精致，宴请客户特别有面子。" },
      { name: "罗小姐", role: "美食爱好者", text: "餐酒搭配建议很专业，每道菜摆盘都像艺术品，体验感拉满。" },
    ],
    ctaTitle: "预订一席精致晚餐",
    ctaSubtitle: "在线订座，提前告知纪念需求享专属布置。",
    ctaButton: "立即订位",
    contactPhone: "400-888-4003",
    contactEmail: "hello@western.com",
    contactAddress: "上海市黄浦区外滩中山东一路 6 号",
    footerSlogan: "以匠心料理，款待每一段精致时光。",
  },

  "japanese-korean": {
    heroTitle: "原汁原味，舌尖上的东瀛与韩风",
    heroSubtitle: "日式料理 · 韩式烤肉 · 寿司刺身，地道风味一站尝遍。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注日韩料理的人气餐厅，刺身海鲜每日空运直达，寿司由专业板前师傅现做，韩式烤肉选用上等鲜切肉品。",
      "从清酒烧鸟到部队锅石锅拌饭，我们还原地道做法与就餐氛围，让你不用出国，也能尝到一口正宗的东瀛与韩风。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让每一口都地道。",
    features: [
      { title: "刺身空运", desc: "海鲜每日空运直达，鲜甜不打折。", icon: I.leaf },
      { title: "板前现做", desc: "专业师傅现捏寿司，温度刚刚好。", icon: I.sparkle },
      { title: "鲜切肉品", desc: "韩式烤肉精选部位，现切现烤。", icon: I.award },
      { title: "地道还原", desc: "做法摆盘忠于原味，正宗不将就。", icon: I.star },
      { title: "清酒小酒", desc: "甄选清酒烧酒，佐餐更有氛围。", icon: I.heart },
      { title: "卡座氛围", desc: "和风韩式卡座，约会聚餐都适合。", icon: I.users },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "日韩经典一网打尽。",
    services: [
      { name: "寿司刺身", desc: "板前现做寿司、当日刺身，鲜甜入味。" },
      { name: "韩式烤肉", desc: "上等鲜切肉品，自助现烤香气四溢。" },
      { name: "日式小食", desc: "烧鸟天妇罗茶碗蒸，下酒又解馋。" },
      { name: "韩式锅物", desc: "部队锅石锅拌饭，暖胃又过瘾。" },
    ],
    stats: [
      { value: "10年", label: "料理经验" },
      { value: "每日", label: "刺身空运" },
      { value: "80+", label: "菜品选择" },
      { value: "97%", label: "回头好评" },
    ],
    testimonialsTitle: "食客怎么说",
    testimonials: [
      { name: "吴小姐", role: "刺身控", text: "三文鱼新鲜得入口即化，寿司温度刚好，这家是我心里的天花板。" },
      { name: "郑先生", role: "烤肉爱好者", text: "鲜切肉品油花漂亮，店员还会帮忙烤，配韩式小菜绝了。" },
      { name: "李女士", role: "约会顾客", text: "卡座氛围很有调性，清酒和料理都地道，约会首选。" },
    ],
    ctaTitle: "预订今晚日韩盛宴",
    ctaSubtitle: "在线订座享时段优惠，旺季不久等。",
    ctaButton: "立即订座",
    contactPhone: "400-888-4004",
    contactEmail: "hello@japanese-korean.com",
    contactAddress: "广州市越秀区环市东路 368 号美食大厦",
    footerSlogan: "一桌日韩好味，让味蕾来一场旅行。",
  },

  bakery: {
    heroTitle: "现烤出炉，香甜每一天",
    heroSubtitle: "欧包软欧 · 蛋糕甜点 · 生日定制，把幸福烤进每一口。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家坚持每日现烤的手作烘焙坊，选用天然黄油与优质面粉，少糖少添加，从软欧、吐司到法式甜点都现做现卖。",
      "无论是清晨的一份早餐面包，还是生日聚会的定制蛋糕，我们都用真材实料与细致手艺，把那份温暖香甜稳稳送到你手里。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让甜点吃得安心。",
    features: [
      { title: "每日现烤", desc: "当日烘焙当日售，新鲜松软不隔夜。", icon: I.clock },
      { title: "天然用料", desc: "真黄油优质面粉，少糖少添加。", icon: I.leaf },
      { title: "手作甜点", desc: "法式甜点师手作，颜值口感俱佳。", icon: I.sparkle },
      { title: "生日定制", desc: "主题蛋糕定制，惊喜创意全实现。", icon: I.heart },
      { title: "明档烘焙", desc: "现场烘焙看得见，干净卫生更安心。", icon: I.shield },
      { title: "贴心配送", desc: "蛋糕同城冷链配送，完好准时达。", icon: I.truck },
    ],
    servicesTitle: "我们的出品",
    servicesSubtitle: "从早餐到甜点，香甜不重样。",
    services: [
      { name: "现烤面包", desc: "软欧吐司可颂，松软麦香每日新鲜。" },
      { name: "精致甜点", desc: "慕斯、千层、塔派，颜值口感双在线。" },
      { name: "生日蛋糕", desc: "主题创意定制，为重要日子加甜。" },
      { name: "节庆礼盒", desc: "节日伴手礼盒，送礼体面有心意。" },
    ],
    stats: [
      { value: "9年", label: "烘焙经验" },
      { value: "100%", label: "当日现烤" },
      { value: "120+", label: "在售单品" },
      { value: "99%", label: "甜蜜好评" },
    ],
    testimonialsTitle: "顾客怎么说",
    testimonials: [
      { name: "杨女士", role: "老顾客", text: "软欧不甜不腻还很扎实，孩子早餐都吃这家，吃得放心。" },
      { name: "周先生", role: "定制顾客", text: "给老婆订的生日蛋糕又美又好吃，配送准时还完好，惊喜满分。" },
      { name: "韩小姐", role: "甜点控", text: "千层和慕斯都太赞了，下午茶必囤，颜值口感都在线。" },
    ],
    ctaTitle: "预订你的专属甜点",
    ctaSubtitle: "生日蛋糕提前预订，热门款不错过。",
    ctaButton: "立即预订",
    contactPhone: "400-888-4005",
    contactEmail: "hello@bakery.com",
    contactAddress: "苏州市姑苏区观前街 58 号烘焙工坊",
    footerSlogan: "用真材实料，把香甜与幸福现烤给你。",
  },

  bbq: {
    heroTitle: "炭火滋滋，鲜到舍不得停筷",
    heroSubtitle: "烧烤畅吃 · 海鲜自助，一价畅享、吃个尽兴。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家主打烧烤与海鲜自助的人气餐厅，海鲜每日直采、肉品现腌现切，从炭火烤串到生蚝大虾，一价畅吃毫不手软。",
      "宽敞热闹的就餐空间、丰富的取餐区与贴心的烤制服务，让朋友相聚、家庭聚餐都能放开肚皮，把鲜香与畅快一次吃够。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让自助吃得过瘾又安心。",
    features: [
      { title: "一价畅吃", desc: "海鲜烤品畅享，不限量吃到满足。", icon: I.cart },
      { title: "海鲜直采", desc: "每日鲜活直达，生蚝大虾新鲜足。", icon: I.leaf },
      { title: "现腌现切", desc: "肉品当天腌制现切，入味又新鲜。", icon: I.sparkle },
      { title: "炭火现烤", desc: "真炭火烤制，焦香四溢更地道。", icon: I.bolt },
      { title: "品类丰富", desc: "百余种食材随取，荤素海鲜全覆盖。", icon: I.star },
      { title: "食安保障", desc: "取餐区分区管理，干净卫生有序。", icon: I.shield },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "从烤串到海鲜，应有尽有。",
    services: [
      { name: "炭火烧烤", desc: "牛羊肉串与各式烤物，焦香入味。" },
      { name: "海鲜畅吃", desc: "生蚝鲜虾扇贝任取，鲜甜满分。" },
      { name: "自助小吃", desc: "凉菜炸物甜品饮品，一站取齐。" },
      { name: "聚会包场", desc: "团体聚餐包场，热闹畅吃更尽兴。" },
    ],
    stats: [
      { value: "8年", label: "自助口碑" },
      { value: "150+", label: "畅吃食材" },
      { value: "每日", label: "海鲜直采" },
      { value: "98%", label: "吃饱好评" },
    ],
    testimonialsTitle: "食客怎么说",
    testimonials: [
      { name: "马先生", role: "聚会常客", text: "海鲜是真新鲜，生蚝大虾管够，一群朋友吃得特别尽兴，超划算。" },
      { name: "高女士", role: "家庭聚餐", text: "品类太丰富了，老人小孩都有爱吃的，环境也热闹干净。" },
      { name: "钱先生", role: "烧烤爱好者", text: "炭火烤出来就是香，肉串现切现腌入味，一价畅吃太爽了。" },
    ],
    ctaTitle: "订座来一场畅吃盛宴",
    ctaSubtitle: "在线订座享时段优惠，聚会不排队。",
    ctaButton: "立即订座",
    contactPhone: "400-888-4006",
    contactEmail: "hello@bbq.com",
    contactAddress: "青岛市市南区香港中路 88 号海鲜美食城",
    footerSlogan: "炭火与海鲜的盛宴，一价吃到尽兴。",
  },

  farmstay: {
    heroTitle: "回归田园，享一日慢生活",
    heroSubtitle: "农家美食 · 采摘垂钓 · 亲子体验，吃住玩一站搞定。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家依山傍水的生态农家乐，自有菜园鱼塘与果园，土菜土鸡现做现上，蔬果从地头直接端上桌，新鲜得吃得出。",
      "这里有采摘、垂钓、烧烤与亲子游乐，远离城市喧嚣，约上家人朋友来一场吃住玩一体的田园慢时光，给身心放个假。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让全家玩得开心吃得放心。",
    features: [
      { title: "地头直供", desc: "自家菜园现摘现做，土味才地道。", icon: I.leaf },
      { title: "土灶柴火", desc: "柴火土灶烹制，还原儿时家常香。", icon: I.bolt },
      { title: "采摘垂钓", desc: "瓜果采摘鱼塘垂钓，乐趣体验多。", icon: I.sparkle },
      { title: "亲子游乐", desc: "草坪乐园小动物，孩子玩到不想走。", icon: I.heart },
      { title: "山水环境", desc: "依山傍水空气好，远离城市喧嚣。", icon: I.globe },
      { title: "吃住一体", desc: "餐饮住宿一站搞定，周末微度假。", icon: I.users },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "把田园乐趣安排明白。",
    services: [
      { name: "农家土菜", desc: "土鸡土鸭时令鲜蔬，柴火现做地道香。" },
      { name: "果园采摘", desc: "应季瓜果亲手采摘，体验丰收乐趣。" },
      { name: "垂钓烧烤", desc: "鱼塘垂钓现钓现烤，户外畅快尽兴。" },
      { name: "亲子团建", desc: "家庭出游与团队团建，活动一站安排。" },
    ],
    stats: [
      { value: "60亩", label: "生态园区" },
      { value: "12年", label: "经营口碑" },
      { value: "30桌", label: "宴客容量" },
      { value: "99%", label: "全家好评" },
    ],
    testimonialsTitle: "客人怎么说",
    testimonials: [
      { name: "陈先生", role: "家庭出游", text: "土菜真的香，孩子采草莓喂小羊玩疯了，全家放松了一整天。" },
      { name: "林女士", role: "周末客人", text: "环境清新空气好，钓鱼烧烤都很尽兴，城里待久了就该来这透透气。" },
      { name: "公司工会", role: "团建组织", text: "团建活动场地大、餐食足，组织一条龙省心，同事都说下次还来。" },
    ],
    ctaTitle: "预订你的田园周末",
    ctaSubtitle: "在线预订餐位与活动，周末名额有限。",
    ctaButton: "立即预订",
    contactPhone: "400-888-4007",
    contactEmail: "hello@farmstay.com",
    contactAddress: "杭州市临安区青山湖畔生态农庄",
    footerSlogan: "回归田园，把慢时光与好胃口都还给你。",
  },

  resort: {
    heroTitle: "择一处山水，享一段闲时光",
    heroSubtitle: "温泉养生 · 山水度假 · 亲子休闲，给身心放个假。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家坐落于山水之间的休闲度假区，集温泉、客房、餐饮、康养与亲子娱乐于一体，让你放下行程表，慢享每一刻。",
      "天然温泉、舒适客房与丰富的休闲设施，搭配贴心管家式服务，无论是情侣度假、家庭出游还是企业团建，都能找到属于你的松弛感。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让度假彻底放松。",
    features: [
      { title: "天然温泉", desc: "多池温泉富含矿物，泡走一身疲惫。", icon: I.leaf },
      { title: "山水环抱", desc: "依山傍水景致宜人，推窗即是风景。", icon: I.globe },
      { title: "舒适客房", desc: "宽敞客房静谧安睡，细节皆用心。", icon: I.heart },
      { title: "康养休闲", desc: "SPA、瑜伽、健身一应俱全。", icon: I.sparkle },
      { title: "亲子娱乐", desc: "儿童乐园与亲子活动，孩子玩不腻。", icon: I.users },
      { title: "管家服务", desc: "贴心管家全程照料，省心又惬意。", icon: I.award },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "把度假体验做到尽善尽美。",
    services: [
      { name: "温泉康养", desc: "多池温泉与水疗SPA，舒缓身心。" },
      { name: "度假住宿", desc: "山景客房与亲子房型，安睡好眠。" },
      { name: "特色餐饮", desc: "山珍时令美食，养生与美味兼得。" },
      { name: "团建会务", desc: "会议宴会与团建活动，整体承接。" },
    ],
    stats: [
      { value: "300亩", label: "度假园区" },
      { value: "10年", label: "运营经验" },
      { value: "20池", label: "温泉汤池" },
      { value: "98%", label: "宾客满意" },
    ],
    testimonialsTitle: "宾客怎么说",
    testimonials: [
      { name: "苏女士", role: "情侣度假", text: "温泉太治愈了，房间能看到山景，服务也周到，彻底放松了一个周末。" },
      { name: "何先生", role: "家庭出游", text: "孩子在乐园玩疯了，大人泡泡温泉做做SPA，全家都满意。" },
      { name: "企业行政", role: "团建会务", text: "会议加团建一站安排，餐食住宿都很到位，同事评价很高。" },
    ],
    ctaTitle: "预订你的度假时光",
    ctaSubtitle: "在线预订客房与温泉套餐，享专属礼遇。",
    ctaButton: "立即预订",
    contactPhone: "400-888-4008",
    contactEmail: "hello@resort.com",
    contactAddress: "黄山市黄山区汤口镇温泉度假区",
    footerSlogan: "在山水之间，找回久违的松弛与惬意。",
  },

  hotel: {
    heroTitle: "宾至如归的每一晚",
    heroSubtitle: "舒适客房 · 贴心服务，让旅途成为一种享受。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家位于城市核心地段的精品酒店，毗邻商圈与交通枢纽，集住宿、餐饮、会议与休闲于一体，出行商务皆便捷。",
      "从舒适静谧的客房、丰盛的自助早餐到 24 小时贴心服务，我们用细致入微的款待，让每一位旅人都能安心入眠、舒心出发。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让住宿安心又舒心。",
    features: [
      { title: "核心地段", desc: "毗邻商圈交通枢纽，出行便利。", icon: I.globe },
      { title: "舒适客房", desc: "优质床品静音环境，一夜好眠。", icon: I.heart },
      { title: "贴心服务", desc: "24小时前台与管家，随叫随到。", icon: I.clock },
      { title: "丰盛餐饮", desc: "自助早餐与中西餐厅，味蕾满足。", icon: I.star },
      { title: "商务会务", desc: "多功能会议厅，商务接待无忧。", icon: I.users },
      { title: "安心住宿", desc: "严格消杀与安保，住得放心。", icon: I.shield },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖住宿全场景需求。",
    services: [
      { name: "豪华客房", desc: "多种房型可选，舒适床品静谧安睡。" },
      { name: "餐饮宴会", desc: "中西自助与宴会承办，丰俭由人。" },
      { name: "会议会展", desc: "多功能厅配套齐全，商务首选。" },
      { name: "休闲康养", desc: "健身泳池SPA一应俱全，放松身心。" },
    ],
    stats: [
      { value: "16年", label: "运营经验" },
      { value: "260间", label: "精品客房" },
      { value: "24h", label: "贴心服务" },
      { value: "98%", label: "住客好评" },
    ],
    testimonialsTitle: "住客怎么说",
    testimonials: [
      { name: "郑先生", role: "商务出差", text: "位置太方便了，房间安静床品舒服，早餐也丰盛，出差首选这家。" },
      { name: "刘女士", role: "家庭旅客", text: "服务很贴心，主动帮我们换了大床房还备了儿童用品，体验很好。" },
      { name: "王总", role: "会务客户", text: "会议厅设备齐全，餐饮接待都很到位，活动办得很顺利。" },
    ],
    ctaTitle: "预订你的舒适一晚",
    ctaSubtitle: "官网直订享会员价与免费升房礼遇。",
    ctaButton: "立即预订",
    contactPhone: "400-888-4009",
    contactEmail: "hello@hotel.com",
    contactAddress: "北京市朝阳区建国路 99 号CBD核心区",
    footerSlogan: "以细致款待，让每一晚都宾至如归。",
  },

  "travel-agency": {
    heroTitle: "把世界，带到你眼前",
    heroSubtitle: "跟团自由行 · 定制路线 · 一站预订，省心畅游每一程。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家持证经营的综合旅行服务机构，深耕国内外热门与小众目的地，从跟团游、自由行到私人定制，线路丰富、品质可靠。",
      "专业顾问为你规划行程、预订机酒门票，资深领队全程随行，把繁琐的安排都交给我们，你只管收拾好心情，出发去看世界。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让旅行省心又尽兴。",
    features: [
      { title: "持证经营", desc: "正规旅行社资质，合同保障安心出游。", icon: I.shield },
      { title: "线路丰富", desc: "国内外目的地齐全，热门小众都有。", icon: I.globe },
      { title: "私人定制", desc: "按需定制专属行程，玩法随你做主。", icon: I.sparkle },
      { title: "一站预订", desc: "机酒门票签证打包，省去比价奔波。", icon: I.cart },
      { title: "资深领队", desc: "专业领队全程随行，应急有保障。", icon: I.users },
      { title: "贴心客服", desc: "行程顾问全程跟进，问题随时解决。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖旅行全流程需求。",
    services: [
      { name: "跟团旅游", desc: "精品线路省心出行，玩法行程都安排好。" },
      { name: "自由行", desc: "机酒自由组合，玩法时间随心安排。" },
      { name: "定制旅行", desc: "私人专属行程，按预算与喜好量身打造。" },
      { name: "票务预订", desc: "机票酒店门票一站预订，便捷优惠。" },
    ],
    stats: [
      { value: "18年", label: "从业经验" },
      { value: "500+", label: "热门线路" },
      { value: "50万+", label: "服务游客" },
      { value: "99%", label: "出游好评" },
    ],
    testimonialsTitle: "游客怎么说",
    testimonials: [
      { name: "孙女士", role: "跟团游客", text: "行程安排很合理不赶不累，领队专业又热情，玩得特别省心。" },
      { name: "马先生", role: "定制客户", text: "顾问把全家的需求都考虑到了，定制的行程节奏刚刚好，体验超棒。" },
      { name: "周小姐", role: "自由行客户", text: "机酒打包比自己订还划算，遇到问题客服秒回，很放心。" },
    ],
    ctaTitle: "规划你的下一段旅程",
    ctaSubtitle: "在线咨询定制行程，领取专属出游优惠。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-4010",
    contactEmail: "hello@travel-agency.com",
    contactAddress: "西安市雁塔区高新路 25 号旅游服务中心",
    footerSlogan: "用心规划每一程，把世界带到你眼前。",
  },

  "local-tour": {
    heroTitle: "周末说走就走，近处也有诗意",
    heroSubtitle: "周边一日游 · 短途自驾 · 主题路线，轻松玩转身边的美好。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们专注于城市周边的短途旅行，精选两小时车程内的山水景区、古镇村落与亲子农场，让你利用周末就能来一场轻松出游。",
      "省心的拼团与自驾路线、贴心的餐食与门票安排，无论是带娃遛弯、朋友踏青还是家庭赏景，都能不折腾地玩好这一天。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让短途游说走就走。",
    features: [
      { title: "近距出游", desc: "两小时车程可达，周末轻松往返。", icon: I.clock },
      { title: "天天发团", desc: "热门线路天天成行，不凑人数。", icon: I.bolt },
      { title: "主题路线", desc: "踏青赏花古镇亲子，主题随心选。", icon: I.sparkle },
      { title: "一价全含", desc: "车费门票餐食包含，玩得不操心。", icon: I.cart },
      { title: "舒适用车", desc: "正规旅游车与司机，安全又准点。", icon: I.truck },
      { title: "亲子友好", desc: "节奏轻松活动有趣，带娃也轻松。", icon: I.heart },
    ],
    servicesTitle: "我们的特色",
    servicesSubtitle: "把周边好去处一网打尽。",
    services: [
      { name: "一日游", desc: "热门周边景区当天往返，省心畅玩。" },
      { name: "短途自驾", desc: "精选自驾路线与攻略，自由又随性。" },
      { name: "亲子线路", desc: "农场采摘动物乐园，遛娃好去处。" },
      { name: "主题踏青", desc: "赏花古镇徒步主题，应季换新玩法。" },
    ],
    stats: [
      { value: "10年", label: "周边深耕" },
      { value: "200+", label: "短途线路" },
      { value: "天天", label: "发团成行" },
      { value: "98%", label: "出游好评" },
    ],
    testimonialsTitle: "游客怎么说",
    testimonials: [
      { name: "高先生", role: "亲子游客", text: "周末带娃去农场采摘喂动物，行程不赶餐食也不错，一家人玩得很开心。" },
      { name: "钱女士", role: "踏青客人", text: "赏花一日游一价全含太省心了，车准时景色美，性价比很高。" },
      { name: "曹先生", role: "自驾客户", text: "自驾路线攻略很实用，避开了堵车点，玩得自由又轻松。" },
    ],
    ctaTitle: "安排这个周末的出游",
    ctaSubtitle: "在线选线路、定座位，周末名额抢先订。",
    ctaButton: "立即报名",
    contactPhone: "400-888-4011",
    contactEmail: "hello@local-tour.com",
    contactAddress: "南京市玄武区中山路 100 号出游服务点",
    footerSlogan: "近处也精彩，让每个周末都有好去处。",
  },

  visa: {
    heroTitle: "出境无忧，签证省心交给我们",
    heroSubtitle: "签证办理 · 材料代审 · 加急服务，出签率高、流程透明。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的出境游与签证服务机构，覆盖申根、英美澳加、日韩东南亚等热门国家，资深签证顾问全程一对一指导。",
      "从材料清单梳理、表格填写到预约递签，我们以规范的流程与丰富的案例经验，帮你规避拒签风险，让出境之路顺畅省心。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让办签安心又高效。",
    features: [
      { title: "高出签率", desc: "资深顾问把关材料，规避拒签风险。", icon: I.award },
      { title: "覆盖广泛", desc: "热门国家签证全覆盖，一站办理。", icon: I.globe },
      { title: "一对一指导", desc: "专属顾问全程跟进，材料不踩坑。", icon: I.users },
      { title: "加急服务", desc: "紧急行程可加急，时效灵活安排。", icon: I.bolt },
      { title: "材料代审", desc: "清单梳理表格代填，省时又省心。", icon: I.cog },
      { title: "信息安全", desc: "证件资料严格保密，全程可追溯。", icon: I.shield },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖出境签证全流程。",
    services: [
      { name: "旅游签证", desc: "申根日韩东南亚等热门签证全程代办。" },
      { name: "商务签证", desc: "邀请函与材料指导，商务出行无忧。" },
      { name: "材料代审", desc: "清单梳理表格代填，预约递签一条龙。" },
      { name: "加急办理", desc: "紧急出行加急通道，争分夺秒不误期。" },
    ],
    stats: [
      { value: "15年", label: "办签经验" },
      { value: "60+", label: "覆盖国家" },
      { value: "99%", label: "平均出签" },
      { value: "10万+", label: "成功案例" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "唐女士", role: "申根签客户", text: "顾问把材料清单列得清清楚楚，全程指导很专业，顺利出签太省心了。" },
      { name: "冯先生", role: "商务签客户", text: "临时出差时间很紧，加急服务三天就搞定，真的帮了大忙。" },
      { name: "董小姐", role: "旅游签客户", text: "第一次办签全靠他们手把手指导，材料一次过审，再也不怕踩坑。" },
    ],
    ctaTitle: "免费评估你的签证方案",
    ctaSubtitle: "在线咨询出签把握，定制专属办理方案。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-4012",
    contactEmail: "hello@visa.com",
    contactAddress: "深圳市福田区深南大道 1001 号签证服务中心",
    footerSlogan: "专业护航每一程，让出境之路畅通无忧。",
  },
};
