import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「食品/茶酒/医药保健」全部子类的精修中文文案。
export const GROCERY_CONTENT: ContentMap = {
  "fruit-veg": {
    heroTitle: "新鲜直达,菜篮子里的安心",
    heroSubtitle: "产地直采当季蔬果,凌晨采摘、当日送达,把田园的鲜甜送进千家万户。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注新鲜蔬果供应的产销一体企业,在全国布局多处自有种植基地与合作农场,从源头把控品质,让每一棵青菜、每一颗水果都新鲜可溯。",
      "依托冷链仓配体系与高效的城市配送网络,我们实现「凌晨采摘、清晨入仓、当日到家」,既服务社区家庭,也为商超、餐饮门店提供稳定货源。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "从田间到餐桌,六重保障守护每一份新鲜。",
    features: [
      { title: "产地直采", desc: "自有基地与合作农场直供,减少中间环节,新鲜更实惠。", icon: I.leaf },
      { title: "全程冷链", desc: "采后预冷、冷链运输,锁住水分与营养,到家依然脆嫩。", icon: I.bolt },
      { title: "当日送达", desc: "城市仓配网络高效运转,下单当日即可送达。", icon: I.truck },
      { title: "品质分级", desc: "按果径、成熟度严格分级,所见即所得不踩坑。", icon: I.award },
      { title: "源头可溯", desc: "每批果蔬可追溯到产地与采摘日期,买得明白。", icon: I.shield },
      { title: "坏果包赔", desc: "签收发现磕碰损耗,拍照即赔,售后无忧。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖家庭、商超与餐饮的全场景果蔬供应。",
    services: [
      { name: "当季时令蔬果", desc: "应季上新,新鲜采摘,营养与口感双在线。" },
      { name: "社区团购到家", desc: "整栋自提点直配,省心省力还省钱。" },
      { name: "商超餐饮配送", desc: "为门店提供稳定货源与定时配送。" },
      { name: "果蔬礼盒定制", desc: "节庆精品礼盒,健康送礼有面子。" },
    ],
    stats: [
      { value: "12年", label: "果蔬经营" },
      { value: "60+", label: "直供基地" },
      { value: "8h", label: "采后入仓" },
      { value: "99%", label: "新鲜签收" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "陈阿姨", role: "社区会员", text: "天天在他家买菜,蔬菜带着露水似的新鲜,价格也比菜场实在。" },
      { name: "刘经理", role: "餐厅采购", text: "供货稳定、分级到位,后厨备菜省了不少心,合作两年很放心。" },
      { name: "周女士", role: "上班族", text: "下班前下单,到家就送到,免去逛菜场,生活质量提升了。" },
    ],
    ctaTitle: "把新鲜带回家",
    ctaSubtitle: "现在下单,体验产地直采的当季鲜甜。",
    ctaButton: "立即选购",
    contactPhone: "400-888-5101",
    contactEmail: "hello@fruit-veg.com",
    contactAddress: "山东省寿光市蔬菜产业园区 18 号",
    footerSlogan: "新鲜蔬果优选 · 让每一餐都安心健康。",
  },

  snacks: {
    heroTitle: "解馋好物,快乐一口接一口",
    heroSubtitle: "网罗全球人气零食,严选好原料、好工艺,把好吃停不下来送到你手边。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注休闲零食的精选品牌,从坚果炒货到糕点蜜饯,从网红爆款到地方风味,只为帮你挑出真正好吃又安心的那一份。",
      "我们与优质原料产地及正规工厂深度合作,严控配料表与生产标准,让每一袋零食既满足味蕾,也吃得放心。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "好吃不踩雷,六大优势让嘴巴和心里都满足。",
    features: [
      { title: "全球甄选", desc: "海内外人气零食一网打尽,潮流好物不断更新。", icon: I.globe },
      { title: "新鲜日期", desc: "小批量快周转,到手日期新鲜,口感更佳。", icon: I.clock },
      { title: "配料透明", desc: "配料表清晰公开,少添加更安心。", icon: I.shield },
      { title: "锁鲜包装", desc: "独立小包与充氮锁鲜,随吃随取不返潮。", icon: I.sparkle },
      { title: "极速发货", desc: "下单即拣,当日发出,馋虫不用久等。", icon: I.bolt },
      { title: "好评严选", desc: "上架前真人试吃,差评款绝不上货架。", icon: I.star },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "从日常解馋到节庆送礼的全品类零食。",
    services: [
      { name: "坚果炒货", desc: "每日坚果与原味炒货,香脆营养两不误。" },
      { name: "网红爆款", desc: "紧跟潮流上新,人气好物先尝为快。" },
      { name: "地方特色味", desc: "各地风味小吃,把家乡味带到身边。" },
      { name: "零食大礼包", desc: "组合装超值囤货,聚会追剧一应俱全。" },
    ],
    stats: [
      { value: "2000+", label: "在售单品" },
      { value: "500万+", label: "累计订单" },
      { value: "98%", label: "好评回购" },
      { value: "24h", label: "当日发货" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "小林", role: "追剧党", text: "每次囤货都从这下单,口味多到选不过来,到手还都很新鲜。" },
      { name: "婷婷", role: "宝妈", text: "给孩子选零食最看配料表,他家标得清清楚楚,买着踏实。" },
      { name: "阿杰", role: "办公室团长", text: "公司下午茶都靠它,大礼包又划算又解馋,同事都爱。" },
    ],
    ctaTitle: "犒劳一下自己",
    ctaSubtitle: "现在下单,开启你的快乐解馋时刻。",
    ctaButton: "马上抢购",
    contactPhone: "400-888-5102",
    contactEmail: "hello@snacks.com",
    contactAddress: "上海市闵行区食品产业园 6 号楼",
    footerSlogan: "休闲零食优选 · 把快乐装进每一袋。",
  },

  specialty: {
    heroTitle: "一方水土,一方好物",
    heroSubtitle: "甄选各地原产地特产,溯源好山好水,把地道风味与匠心好礼带给你。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们深耕地方特产领域,走进一座座原产地村镇,与农户、合作社、老字号作坊直接合作,只为把真正地道的「家乡味」带出大山、带向全国。",
      "从优选、品控到包装设计,我们坚持原产地直供与标准化品控,让每一份特产既有风土的味道,也有放心的品质与体面的颜值。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "原产地直供,六重把关让好物更有底气。",
    features: [
      { title: "原产地直供", desc: "深入产区源头采购,正宗地道、价更优。", icon: I.leaf },
      { title: "匠心好物", desc: "传承老手艺与传统工艺,风味更纯正。", icon: I.award },
      { title: "溯源认证", desc: "地理标志与产地溯源,品质有据可查。", icon: I.shield },
      { title: "精致礼盒", desc: "原创礼盒设计,送礼有面、收礼有心。", icon: I.sparkle },
      { title: "全国直发", desc: "产地仓直接发货,新鲜地道不打折。", icon: I.truck },
      { title: "助农优选", desc: "与合作社共建,既买好物也助乡村。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "从尝鲜到送礼的原产地特产精选。",
    services: [
      { name: "地理标志特产", desc: "受地理标志保护的名优特产,正宗有保障。" },
      { name: "时令尝鲜", desc: "应季限定好物,错过再等一年。" },
      { name: "节庆礼盒", desc: "中秋、年货精品礼盒,体面又地道。" },
      { name: "企业团购定制", desc: "专属包装与开票服务,团购更省心。" },
    ],
    stats: [
      { value: "30+", label: "合作产区" },
      { value: "300+", label: "甄选好物" },
      { value: "15万+", label: "服务家庭" },
      { value: "100%", label: "原产地直供" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "郑先生", role: "返乡游子", text: "买到了小时候的味道,包装也精致,寄给外地朋友很有面子。" },
      { name: "孙女士", role: "送礼达人", text: "逢年过节都在这选特产礼盒,正宗又好看,长辈都喜欢。" },
      { name: "黄经理", role: "企业采购", text: "公司福利团购选了好几次,品质稳定、开票规范,很省心。" },
    ],
    ctaTitle: "把地道好物带回家",
    ctaSubtitle: "现在下单,品味来自原产地的匠心风味。",
    ctaButton: "立即品鉴",
    contactPhone: "400-888-5103",
    contactEmail: "hello@specialty.com",
    contactAddress: "云南省大理市古城特产文化街 22 号",
    footerSlogan: "原产地特产优选 · 一份好物,一份心意。",
  },

  tea: {
    heroTitle: "一盏好茶,品味生活",
    heroSubtitle: "原产地直采名优茶,传承千年茶文化,让每一次冲泡都回甘悠长。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家深耕茶行业多年的名优茶品牌,在多个核心产区拥有自有茶园与合作基地,从一片鲜叶的采摘到一杯好茶的呈现,坚持传统工艺与现代品控并重。",
      "我们相信好茶源于好山好水与匠心制作,以原产地直采保障品质与价格,让爱茶之人都能喝到一杯干净、地道、回甘的好茶。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "从茶园到茶杯,六重匠心成就一盏好茶。",
    features: [
      { title: "原产地直采", desc: "核心产区自有茶园直供,正宗地道更安心。", icon: I.leaf },
      { title: "古法制茶", desc: "非遗工艺与制茶师匠心,锁住本真茶香。", icon: I.award },
      { title: "无农残检测", desc: "批批送检,农残重金属严格管控。", icon: I.shield },
      { title: "原叶分级", desc: "按等级精细分拣,所见即所得。", icon: I.star },
      { title: "礼盒典藏", desc: "高端礼盒设计,品饮与馈赠两相宜。", icon: I.sparkle },
      { title: "茶艺服务", desc: "专业茶艺指导,带你读懂每一款茶。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖品饮、馈赠与茶文化体验的全方位服务。",
    services: [
      { name: "名优茶", desc: "原产地直采各类名茶,品质有保障。" },
      { name: "礼盒定制", desc: "高端礼盒,逢年过节送礼更体面。" },
      { name: "茶具茶器", desc: "精选茶器,提升每一次冲泡的茶趣。" },
      { name: "茶艺培训", desc: "专业茶艺课程,品茶从入门到精通。" },
    ],
    stats: [
      { value: "20年", label: "制茶传承" },
      { value: "8大", label: "核心产区" },
      { value: "50万+", label: "爱茶客户" },
      { value: "100%", label: "原产地直采" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "赵老师", role: "老顾客", text: "喝了五年,茶汤干净回甘,一喝就知道是用心做的好茶。" },
      { name: "钱先生", role: "茶礼采购", text: "礼盒大气、品质稳定,送客户长辈都很有面子。" },
      { name: "吴女士", role: "茶艺爱好者", text: "不仅茶好,还能学到泡茶门道,越喝越懂茶。" },
    ],
    ctaTitle: "开启你的品茶之旅",
    ctaSubtitle: "现在就来选一盏好茶,品味山水间的回甘。",
    ctaButton: "立即选茶",
    contactPhone: "400-888-5104",
    contactEmail: "hello@tea.com",
    contactAddress: "福州市鼓楼区五一中路茶文化街 8 号",
    footerSlogan: "名优茶优选 · 一盏好茶,品味生活。",
  },

  baijiu: {
    heroTitle: "纯粮酿造,杯杯见真章",
    heroSubtitle: "传承古法固态酿造,精选优质粮食,窖藏陈香,只为一口绵柔好酒。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家坚持纯粮固态酿造的白酒企业,沿用传统古法工艺,以高粱、小麦等优质粮食为原料,经历制曲、发酵、蒸馏、窖藏等多道工序,酿出绵柔醇厚的好酒。",
      "我们深知好酒离不开时间的沉淀,坚持长期窖藏、批批检验,既守护传统风味,也以现代品控让每一瓶酒都纯正可靠、安心入口。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "古法与匠心并存,六重保障酿就一瓶好酒。",
    features: [
      { title: "纯粮固态", desc: "粮食固态发酵,拒绝勾兑,本真酒香。", icon: I.leaf },
      { title: "古法工艺", desc: "传统制曲与老窖发酵,风味更醇厚。", icon: I.award },
      { title: "陈年窖藏", desc: "长期窖藏沉淀,入口绵柔不上头。", icon: I.clock },
      { title: "正品防伪", desc: "一物一码防伪溯源,杜绝假冒。", icon: I.shield },
      { title: "品质送检", desc: "批批检测,理化指标稳定达标。", icon: I.star },
      { title: "礼盒臻享", desc: "典藏礼盒包装,宴请送礼皆相宜。", icon: I.sparkle },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "从口粮酒到收藏酒的全系列供应。",
    services: [
      { name: "纯粮口粮酒", desc: "日常自饮的高性价比纯粮好酒。" },
      { name: "宴席用酒", desc: "婚宴寿宴整箱供货,价优量足。" },
      { name: "高端礼盒酒", desc: "典藏礼盒,商务馈赠有档次。" },
      { name: "封坛定制酒", desc: "私人封坛与企业定制,专属风味。" },
    ],
    stats: [
      { value: "30年", label: "酿酒传承" },
      { value: "5年+", label: "窖藏陈酿" },
      { value: "100%", label: "纯粮酿造" },
      { value: "20万+", label: "客户信赖" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "老张", role: "回头客", text: "纯粮酒就是不一样,喝着绵柔,第二天也不头疼,认准这家了。" },
      { name: "马总", role: "宴席采购", text: "孩子婚宴整箱拿的,口感好、价格实,客人都说酒不错。" },
      { name: "高先生", role: "藏酒爱好者", text: "封坛定制很有仪式感,留着收藏或者过节开封都合适。" },
    ],
    ctaTitle: "品一杯纯粮好酒",
    ctaSubtitle: "现在下单,感受古法窖藏的绵柔醇香。",
    ctaButton: "立即品鉴",
    contactPhone: "400-888-5105",
    contactEmail: "hello@baijiu.com",
    contactAddress: "四川省宜宾市叙州区酒谷大道 88 号",
    footerSlogan: "纯粮白酒优选 · 古法窖藏,杯杯醇香。",
  },

  wine: {
    heroTitle: "一杯红酒,佐味好时光",
    heroSubtitle: "全球精选酒庄直采,从入门佳酿到名庄珍藏,为每一次相聚增添优雅。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的葡萄酒进口与精选品牌,与法国、意大利、智利、澳洲等多国优质酒庄建立直采合作,把世界各地的风土之味带到你的餐桌。",
      "从产区甄选、原瓶进口到全程恒温仓储,我们坚持正品保真与专业储运,并提供选酒与配餐建议,让懂酒与初识者都能轻松找到心仪那一瓶。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "懂风土更懂你,六大优势让品酒更省心。",
    features: [
      { title: "酒庄直采", desc: "与海外名庄直接合作,原瓶进口更地道。", icon: I.globe },
      { title: "正品保真", desc: "海关报关原瓶进口,扫码溯源可查。", icon: I.shield },
      { title: "恒温仓储", desc: "专业恒温恒湿酒窖,呵护每一瓶风味。", icon: I.clock },
      { title: "专业侍酒", desc: "侍酒师选酒配餐建议,品鉴不踩坑。", icon: I.award },
      { title: "稳妥配送", desc: "防震防漏专业包装,完好送达手中。", icon: I.truck },
      { title: "品鉴沙龙", desc: "定期举办品酒会,结识同好享美好。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "从日常餐酒到名庄珍藏的优雅之选。",
    services: [
      { name: "日常餐酒", desc: "高性价比口粮红酒,佐餐自饮皆宜。" },
      { name: "名庄精选", desc: "知名产区与名庄佳酿,品鉴收藏首选。" },
      { name: "礼盒套装", desc: "精致双支礼盒,商务节庆馈赠有格调。" },
      { name: "宴会酒水方案", desc: "婚宴年会整体配酒,省心又体面。" },
    ],
    stats: [
      { value: "10国", label: "直采产区" },
      { value: "800+", label: "在售酒款" },
      { value: "100%", label: "正品保真" },
      { value: "30万+", label: "品酒会员" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "Linda", role: "品酒爱好者", text: "选酒建议很专业,每次都能挑到合口味的,配餐也讲得很到位。" },
      { name: "徐先生", role: "商务宴请", text: "礼盒上档次、口感也好,招待客户很有面子,会一直回购。" },
      { name: "何女士", role: "新晋酒友", text: "从小白入门到爱上红酒,品酒会让我学到很多,氛围特别好。" },
    ],
    ctaTitle: "开启一段品酒时光",
    ctaSubtitle: "现在选购,让好酒为你的生活添一抹优雅。",
    ctaButton: "立即选酒",
    contactPhone: "400-888-5106",
    contactEmail: "hello@wine.com",
    contactAddress: "广州市天河区珠江新城进口酒展示中心 3 层",
    footerSlogan: "进口红酒优选 · 一杯佳酿,佐味好时光。",
  },

  hospital: {
    heroTitle: "守护健康,用心相伴",
    heroSubtitle: "专业医疗团队 · 先进诊疗设备,以仁心仁术为您的健康保驾护航。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家集医疗、预防、康复于一体的综合性医疗机构,汇聚多学科专家团队,引进先进诊疗设备,致力于为患者提供安全、规范、有温度的医疗服务。",
      "我们坚持以患者为中心,持续优化就医流程、推进智慧医疗建设,让看病更便捷、诊疗更精准,用专业与关怀守护每一位患者的健康。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "以患者为中心,六大保障让就医更安心。",
    features: [
      { title: "专家坐诊", desc: "多学科资深专家团队,精准诊断少走弯路。", icon: I.users },
      { title: "先进设备", desc: "引进高端诊疗设备,检查更精细可靠。", icon: I.cog },
      { title: "规范诊疗", desc: "标准化诊疗流程,质量与安全双把控。", icon: I.shield },
      { title: "智慧就医", desc: "在线挂号、报告查询,少排队更省心。", icon: I.bolt },
      { title: "全程关怀", desc: "导诊陪护与随访服务,就医更有温度。", icon: I.heart },
      { title: "隐私保护", desc: "严守诊疗隐私,信息安全有保障。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖诊疗、体检与康复的全周期健康服务。",
    services: [
      { name: "专家门诊", desc: "知名专家坐诊,提供精准诊疗方案。" },
      { name: "健康体检", desc: "个性化体检套餐,疾病早筛早防。" },
      { name: "智慧医疗", desc: "在线挂号、远程问诊,就医更便捷。" },
      { name: "康复护理", desc: "专业康复治疗与护理,助力快速恢复。" },
    ],
    stats: [
      { value: "30年", label: "办院历史" },
      { value: "200+", label: "专家团队" },
      { value: "100万+", label: "年服务量" },
      { value: "24h", label: "急诊响应" },
    ],
    testimonialsTitle: "患者怎么说",
    testimonials: [
      { name: "李大爷", role: "复诊患者", text: "医生很耐心,检查也细致,看病流程顺畅,在这看病很安心。" },
      { name: "王女士", role: "体检客户", text: "体检套餐很全面,报告解读专业,还能在线查结果,很方便。" },
      { name: "张先生", role: "康复患者", text: "康复团队很专业,恢复得比预期快,服务态度也特别好。" },
    ],
    ctaTitle: "把健康交给专业",
    ctaSubtitle: "现在预约,享受贴心、规范的医疗服务。",
    ctaButton: "在线预约",
    contactPhone: "400-888-5107",
    contactEmail: "hello@hospital.com",
    contactAddress: "北京市朝阳区健康路 1 号",
    footerSlogan: "守护健康 · 用专业与关怀相伴每一位患者。",
  },

  pharmacy: {
    heroTitle: "好药在身边,健康有依靠",
    heroSubtitle: "正品药品 · 专业药师,线上线下一站购药,把安心送到家门口。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家正规经营的连锁药房,严格执行药品采购与储存规范,所有药品均来自正规渠道,确保每一盒药都正品可溯、安全可靠。",
      "门店配备执业药师全程坐诊,提供用药咨询、慢病管理与健康指导,并开通线上下单、急送到家服务,让买药用药更专业、更便捷、更安心。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "专业与便捷兼得,六重保障守护用药安全。",
    features: [
      { title: "正品保障", desc: "正规渠道采购,药品可溯源,拒绝假药。", icon: I.shield },
      { title: "药师坐诊", desc: "执业药师专业指导,科学用药不踩坑。", icon: I.users },
      { title: "急送到家", desc: "线上下单急配,常用药快速送上门。", icon: I.bolt },
      { title: "慢病管理", desc: "建立健康档案,慢病随访贴心提醒。", icon: I.heart },
      { title: "品类齐全", desc: "处方药、OTC、保健品一站购齐。", icon: I.cart },
      { title: "规范储存", desc: "冷链药品恒温存放,药效有保障。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖购药、咨询与健康管理的便民服务。",
    services: [
      { name: "处方与OTC药品", desc: "处方调配与非处方药供应,正品齐全。" },
      { name: "用药咨询", desc: "执业药师一对一解答,安全合理用药。" },
      { name: "线上购药到家", desc: "手机下单、急送上门,买药不用跑。" },
      { name: "健康养护用品", desc: "保健品、医疗器械、护理用品一应俱全。" },
    ],
    stats: [
      { value: "15年", label: "连锁经营" },
      { value: "120+", label: "门店网点" },
      { value: "30分钟", label: "急送到家" },
      { value: "100%", label: "正品承诺" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "陈先生", role: "社区居民", text: "药师讲解很专业,用药放心,半夜急用药也能送上门,太方便了。" },
      { name: "刘阿姨", role: "慢病患者", text: "帮我建了健康档案,定期提醒复购,血压药再没断过,很贴心。" },
      { name: "小杨", role: "上班族", text: "手机下单半小时就送到,不用请假跑药店,服务很到位。" },
    ],
    ctaTitle: "用药就找专业药房",
    ctaSubtitle: "现在下单或到店,享受正品药品与专业药师服务。",
    ctaButton: "立即购药",
    contactPhone: "400-888-5108",
    contactEmail: "hello@pharmacy.com",
    contactAddress: "杭州市拱墅区健康大道 168 号",
    footerSlogan: "连锁药房 · 正品好药,健康相伴。",
  },

  dental: {
    heroTitle: "好牙好心情,笑容更自信",
    heroSubtitle: "专业齿科团队 · 舒适诊疗体验,为全家提供种植、正畸、美白等口腔服务。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注口腔健康的现代化齿科机构,汇聚种植、正畸、修复、儿牙等多领域专业医师,引进数字化诊疗设备,为每一位顾客量身定制口腔方案。",
      "我们坚持严格的院感消毒标准与舒适化诊疗理念,从检查到治疗全程透明、温柔无痛,让看牙不再令人紧张,让健康笑容触手可及。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "专业又舒适,六大保障让看牙更安心。",
    features: [
      { title: "专业医师", desc: "种植正畸资深医师团队,技术精湛可靠。", icon: I.users },
      { title: "数字诊疗", desc: "口扫与数字化设计,方案精准可视化。", icon: I.cog },
      { title: "严格消毒", desc: "一人一用一消毒,院感防控达标。", icon: I.shield },
      { title: "舒适无痛", desc: "舒适化诊疗理念,温柔治疗少恐惧。", icon: I.heart },
      { title: "正规品牌", desc: "种植体与材料正品可溯,长期有保障。", icon: I.award },
      { title: "全程跟踪", desc: "建立口腔档案,定期复查贴心提醒。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖全龄口腔健康的一站式诊疗。",
    services: [
      { name: "种植牙", desc: "缺牙修复种植,稳固美观如真牙。" },
      { name: "牙齿正畸", desc: "传统托槽与隐形矫正,排齐更自信。" },
      { name: "美白修复", desc: "冷光美白、贴面修复,焕亮笑容。" },
      { name: "全家口腔护理", desc: "洗牙、补牙、儿牙,全家口腔守护。" },
    ],
    stats: [
      { value: "16年", label: "齿科经验" },
      { value: "50+", label: "专业医师" },
      { value: "10万+", label: "诊疗案例" },
      { value: "98%", label: "顾客满意" },
    ],
    testimonialsTitle: "顾客怎么说",
    testimonials: [
      { name: "周女士", role: "种植牙顾客", text: "种牙过程比想象中轻松,医生很细心,现在吃东西完全没问题。" },
      { name: "小敏", role: "正畸顾客", text: "戴了隐形牙套,牙齿排齐了,笑起来自信多了,服务也很贴心。" },
      { name: "吴爸爸", role: "家庭顾客", text: "带全家来做口腔检查,环境干净、消毒严格,孩子看牙也不哭了。" },
    ],
    ctaTitle: "给牙齿一次专业呵护",
    ctaSubtitle: "现在预约,开启舒适放心的口腔诊疗。",
    ctaButton: "预约面诊",
    contactPhone: "400-888-5109",
    contactEmail: "hello@dental.com",
    contactAddress: "深圳市南山区科技园口腔健康中心 2 层",
    footerSlogan: "专业齿科 · 好牙好笑容,健康每一天。",
  },
};
