import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「五金/设备/汽车服务」全部子类的精修中文文案。
export const HARDWARE_CONTENT: ContentMap = {
  handles: {
    heroTitle: "方寸之间,握住品质细节",
    heroSubtitle: "专注门窗家具拉手研发制造,精工五金、手感顺滑,为家居与工程提供可靠之选。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的拉手五金制造企业,深耕橱柜、门窗、家具拉手领域多年,拥有成熟的模具开发与表面处理工艺,产品远销国内外众多家居品牌与工程项目。",
      "从原材料选择到电镀喷涂,我们严控每一道工序,坚持以稳定的品质、丰富的款式与高效的交付,成为家装与工程客户值得信赖的五金配套伙伴。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "细节见真章,六大优势铸就好拉手。",
    features: [
      { title: "精工铸造", desc: "锌合金/不锈钢精铸成型,结实耐用不松动。", icon: I.cog },
      { title: "顺滑手感", desc: "精细打磨与圆润倒角,开合顺手不刮手。", icon: I.sparkle },
      { title: "耐蚀电镀", desc: "多层电镀与拉丝工艺,防锈耐磨持久亮。", icon: I.shield },
      { title: "款式齐全", desc: "现代简约到中式经典,海量款式任选。", icon: I.star },
      { title: "支持定制", desc: "尺寸、颜色、LOGO 按需开模定制。", icon: I.bolt },
      { title: "稳定交付", desc: "自有产线产能充足,工程订单准时交付。", icon: I.truck },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖家装零售与工程配套的拉手供应。",
    services: [
      { name: "橱柜衣柜拉手", desc: "多规格家具拉手,匹配各类柜门。" },
      { name: "门窗执手", desc: "门窗专用执手把手,坚固顺滑。" },
      { name: "定制开模", desc: "按图开模定制,满足专属设计需求。" },
      { name: "工程批量供货", desc: "地产精装与工程项目批量配套。" },
    ],
    stats: [
      { value: "18年", label: "五金制造" },
      { value: "1000+", label: "产品款式" },
      { value: "30+", label: "出口国家" },
      { value: "99%", label: "准时交付" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "林经理", role: "家具厂采购", text: "拉手手感好、电镀均匀,装到柜子上很上档次,合作多年很省心。" },
      { name: "陈工", role: "工程项目方", text: "工程量大也能按期交货,品质稳定,验收一次通过。" },
      { name: "Anna", role: "外贸客户", text: "支持定制开模,打样响应快,出口品质完全达标。" },
    ],
    ctaTitle: "为产品配上好五金",
    ctaSubtitle: "现在联系我们,获取拉手样册与工程报价。",
    ctaButton: "索取样册",
    contactPhone: "400-888-5201",
    contactEmail: "hello@handles.com",
    contactAddress: "广东省中山市小榄镇五金工业区 12 号",
    footerSlogan: "精工拉手制造 · 握住每一处品质细节。",
  },

  windows: {
    heroTitle: "门窗有道,安居有方",
    heroSubtitle: "系统门窗研发制造与安装,隔音隔热、密封抗风,为家筑起安静舒适的边界。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家集研发、生产、安装于一体的系统门窗企业,选用优质断桥铝型材与高性能五金配件,打造隔音、保温、防水、抗风性能俱佳的高品质门窗系统。",
      "从上门测量、方案设计到生产安装、售后维保,我们提供一站式门窗解决方案,既服务家装业主,也承接地产工程与公建项目,让每一扇窗都安心耐用。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "性能与工艺并重,六重保障守护每一扇窗。",
    features: [
      { title: "断桥隔热", desc: "断桥铝型材隔热保温,四季室温更宜居。", icon: I.shield },
      { title: "静音降噪", desc: "中空/夹胶玻璃多重密封,隔绝室外喧嚣。", icon: I.sparkle },
      { title: "抗风防水", desc: "结构稳固密封到位,抗风压、不渗漏。", icon: I.bolt },
      { title: "安全配件", desc: "优质五金与防坠设计,使用更安心。", icon: I.cog },
      { title: "量尺定制", desc: "上门测量按户定制,尺寸严丝合缝。", icon: I.star },
      { title: "专业安装", desc: "标准化安装工艺,验收合格再交付。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖家装与工程的系统门窗一站式服务。",
    services: [
      { name: "系统门窗", desc: "断桥铝平开、推拉门窗,隔音保温。" },
      { name: "阳光房定制", desc: "阳光房与封阳台定制,通透又安心。" },
      { name: "工程门窗配套", desc: "地产与公建项目批量门窗供应安装。" },
      { name: "测量安装维保", desc: "上门测量、专业安装与售后维保。" },
    ],
    stats: [
      { value: "20年", label: "门窗经验" },
      { value: "5万+", label: "安装案例" },
      { value: "10年", label: "质保承诺" },
      { value: "98%", label: "客户满意" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "赵女士", role: "家装业主", text: "换了他家的隔音窗,临街也安静了不少,密封做得很到位。" },
      { name: "孙经理", role: "地产项目方", text: "工程门窗交付准时、性能达标,验收顺利,合作很愉快。" },
      { name: "李先生", role: "封阳台业主", text: "上门测量很专业,安装师傅细致,阳光房做得又通透又结实。" },
    ],
    ctaTitle: "为家装上好门窗",
    ctaSubtitle: "现在预约,获取免费上门测量与方案报价。",
    ctaButton: "免费测量",
    contactPhone: "400-888-5202",
    contactEmail: "hello@windows.com",
    contactAddress: "山东省临沂市兰山区门窗产业园 6 号",
    footerSlogan: "系统门窗制造 · 门窗有道,安居有方。",
  },

  bathroom: {
    heroTitle: "卫浴之美,藏在每个细节",
    heroSubtitle: "专注高品质卫浴洁具,龙头花洒到智能马桶,让每天的盥洗成为一种享受。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的卫浴洁具制造与供应企业,产品涵盖龙头、花洒、智能马桶、浴室柜等全系列卫浴用品,以精工品质与人性化设计提升每一个卫浴空间。",
      "从阀芯、电镀到智能控制,我们坚持选用优质材料与成熟工艺,严控出厂检测,既服务家装零售,也为酒店、地产工程提供稳定的卫浴整体配套方案。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "好用更耐用,六大优势重塑卫浴体验。",
    features: [
      { title: "精密阀芯", desc: "陶瓷阀芯耐用顺滑,开合数十万次不漏。", icon: I.cog },
      { title: "健康用水", desc: "无铅环保材质,呵护全家用水安全。", icon: I.shield },
      { title: "节水科技", desc: "恒温节水设计,舒适又省水省气。", icon: I.leaf },
      { title: "智能体验", desc: "智能马桶即热冲洗,科技带来舒适。", icon: I.sparkle },
      { title: "亮泽电镀", desc: "多层电镀工艺,长久亮泽不易锈蚀。", icon: I.star },
      { title: "工程配套", desc: "酒店地产整体卫浴配套,稳定供货。", icon: I.truck },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖家装与工程的整体卫浴解决方案。",
    services: [
      { name: "龙头花洒", desc: "恒温节水龙头花洒,舒适耐用。" },
      { name: "智能马桶", desc: "即热冲洗智能坐便,提升如厕体验。" },
      { name: "浴室柜镜柜", desc: "防潮浴室柜与镜柜,收纳更从容。" },
      { name: "工程整体配套", desc: "酒店地产卫浴整体方案与供货。" },
    ],
    stats: [
      { value: "22年", label: "卫浴制造" },
      { value: "60万次", label: "阀芯寿命" },
      { value: "5年", label: "质保服务" },
      { value: "1000+", label: "合作工程" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "周先生", role: "家装业主", text: "龙头手感顺滑、出水稳定,智能马桶用着很舒服,质量没得说。" },
      { name: "Helen", role: "酒店采购", text: "整体卫浴配套方案专业,供货及时,客房升级后口碑提升明显。" },
      { name: "王女士", role: "装修客户", text: "浴室柜防潮做得好,用了两年依旧如新,售后也很省心。" },
    ],
    ctaTitle: "升级你的卫浴空间",
    ctaSubtitle: "现在咨询,获取卫浴选型与整体方案报价。",
    ctaButton: "立即咨询",
    contactPhone: "400-888-5203",
    contactEmail: "hello@bathroom.com",
    contactAddress: "广东省佛山市南海区卫浴产业基地 28 号",
    footerSlogan: "高品质卫浴 · 把美好藏进每个细节。",
  },

  machinery: {
    heroTitle: "智造未来,精工品质",
    heroSubtitle: "高端机械设备研发制造,稳定高效、坚固耐用,为工业生产提供可靠动力。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注机械设备研发与制造的高新技术企业,拥有自主设计团队与精密加工产线,产品广泛应用于制造、包装、食品、化工等多个工业领域。",
      "我们坚持以稳定的性能、过硬的质量与完善的服务赢得客户信赖,提供从方案设计、设备制造到安装调试、终身维保的一体化解决方案,助力客户降本增效。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "硬核实力护航,六大优势成就高效产线。",
    features: [
      { title: "精密制造", desc: "高精度数控加工,部件精度与稳定性出众。", icon: I.cog },
      { title: "稳定耐用", desc: "优选材料与工艺,长时间运转少故障。", icon: I.shield },
      { title: "高效产能", desc: "自动化设计提升节拍,显著提高产能。", icon: I.bolt },
      { title: "方案定制", desc: "按工艺需求定制产线,适配生产场景。", icon: I.chart },
      { title: "安装调试", desc: "工程师上门安装调试,投产无忧。", icon: I.users },
      { title: "终身维保", desc: "原厂配件与全周期维保,运行更安心。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖设备全生命周期的工业解决方案。",
    services: [
      { name: "设备制造", desc: "标准与非标设备精密制造,品质可靠。" },
      { name: "产线方案定制", desc: "按需定制自动化生产线整体方案。" },
      { name: "安装调试", desc: "专业团队上门安装、调试与培训。" },
      { name: "售后维保", desc: "全周期维护保养与配件供应。" },
    ],
    stats: [
      { value: "25年", label: "装备制造" },
      { value: "3000+", label: "设备交付" },
      { value: "40+", label: "服务行业" },
      { value: "24h", label: "技术响应" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "张厂长", role: "制造企业", text: "设备运行稳定、故障率低,定制的产线节拍很合理,产能上来了。" },
      { name: "刘总", role: "包装行业客户", text: "从方案到调试都很专业,投产很顺利,售后响应也及时。" },
      { name: "陈经理", role: "食品工厂", text: "卫生级设计符合我们的标准,维保到位,合作很放心。" },
    ],
    ctaTitle: "为产线注入可靠动力",
    ctaSubtitle: "现在联系我们,获取设备方案与定制报价。",
    ctaButton: "获取方案",
    contactPhone: "400-888-5204",
    contactEmail: "hello@machinery.com",
    contactAddress: "江苏省苏州市吴中区装备制造产业园 9 号",
    footerSlogan: "高端装备制造 · 智造未来,精工品质。",
  },

  instruments: {
    heroTitle: "精准测量,数据可信",
    heroSubtitle: "专业仪器仪表与实验器材供应,精准可靠、计量可溯,为科研与工业保驾护航。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的仪器仪表与实验器材供应商,代理及自营涵盖检测、分析、计量、实验等多门类产品,服务于科研院所、高校实验室、工业质检与环境监测等领域。",
      "我们不仅提供高精度仪器设备,更配套校准计量、安装培训与技术支持,坚持以精准的数据与专业的服务,帮助客户构建可信赖的测量与检测能力。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "精准之上更专业,六大优势让数据可信。",
    features: [
      { title: "高精度", desc: "高精度仪器选型,测量结果稳定可靠。", icon: I.chart },
      { title: "计量溯源", desc: "提供校准证书,量值可溯源可追查。", icon: I.shield },
      { title: "正品行货", desc: "正规渠道供货,品牌行货质保无忧。", icon: I.award },
      { title: "安装培训", desc: "上门安装与操作培训,快速上手。", icon: I.users },
      { title: "技术支持", desc: "专业工程师答疑,选型应用更省心。", icon: I.cog },
      { title: "快速供货", desc: "常用仪器备货充足,交付高效及时。", icon: I.bolt },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖选型、计量与技术支持的全流程服务。",
    services: [
      { name: "检测分析仪器", desc: "实验分析与检测仪器,精准高效。" },
      { name: "计量校准服务", desc: "仪器校准与量值溯源,数据可信。" },
      { name: "实验室器材", desc: "实验耗材与器材配套,一站采购。" },
      { name: "安装培训支持", desc: "设备安装、培训与技术答疑。" },
    ],
    stats: [
      { value: "16年", label: "行业服务" },
      { value: "5000+", label: "在售型号" },
      { value: "1000+", label: "合作单位" },
      { value: "100%", label: "正品行货" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "王教授", role: "高校实验室", text: "仪器选型建议很专业,精度达标、校准齐全,科研数据更有底气。" },
      { name: "李工", role: "工业质检", text: "供货及时、培训到位,质检效率提升不少,售后也很靠谱。" },
      { name: "赵主任", role: "环境监测站", text: "设备稳定、证书规范,迎检顺利通过,合作很值得信赖。" },
    ],
    ctaTitle: "让每一次测量都可信",
    ctaSubtitle: "现在咨询,获取仪器选型与计量方案。",
    ctaButton: "立即咨询",
    contactPhone: "400-888-5205",
    contactEmail: "hello@instruments.com",
    contactAddress: "北京市海淀区中关村科技仪器城 5 层",
    footerSlogan: "专业仪器仪表 · 精准测量,数据可信。",
  },

  firesafety: {
    heroTitle: "防患未然,守护每一刻安全",
    heroSubtitle: "消防与安防器材一站供应,从灭火器材到防盗系统,为生命财产筑牢防线。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的消防防盗器材供应与工程服务企业,产品涵盖灭火器材、火灾报警、应急照明、防盗门禁与监控联动等,全部具备合规认证,安全可靠。",
      "我们为企事业单位、商业楼宇与住宅小区提供从产品供应、方案设计到安装施工与年检维保的一站式安全解决方案,以专业守护每一处人居与生产安全。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "合规又专业,六重保障筑牢安全防线。",
    features: [
      { title: "认证合规", desc: "产品通过权威认证,验收备案有保障。", icon: I.shield },
      { title: "及时预警", desc: "烟感报警联动响应,险情第一时间知晓。", icon: I.bolt },
      { title: "稳定可靠", desc: "关键器材严选品质,关键时刻不掉链子。", icon: I.award },
      { title: "方案设计", desc: "按场景定制消防安防方案,科学布防。", icon: I.cog },
      { title: "专业施工", desc: "持证团队规范安装,施工质量过硬。", icon: I.users },
      { title: "年检维保", desc: "定期检测维护,设施长期有效可用。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖供货、设计与维保的安全一体化服务。",
    services: [
      { name: "消防器材供应", desc: "灭火器、消防栓、应急照明等全配套。" },
      { name: "火灾报警系统", desc: "烟感报警与联动控制,及时预警。" },
      { name: "防盗门禁监控", desc: "防盗报警、门禁与监控联动布防。" },
      { name: "工程安装维保", desc: "方案设计、安装施工与年检维保。" },
    ],
    stats: [
      { value: "18年", label: "安防经验" },
      { value: "2000+", label: "服务项目" },
      { value: "100%", label: "认证合规" },
      { value: "24h", label: "应急响应" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "马经理", role: "商业楼宇方", text: "消防方案做得很细,验收一次通过,年检维保也很省心。" },
      { name: "周主任", role: "工厂安全负责人", text: "报警和监控联动很灵敏,演练效果好,安全感大大提升。" },
      { name: "李先生", role: "小区物业", text: "防盗门禁加监控之后,小区安全好了很多,业主满意度也高。" },
    ],
    ctaTitle: "把安全交给专业",
    ctaSubtitle: "现在联系我们,获取消防安防方案与报价。",
    ctaButton: "获取方案",
    contactPhone: "400-888-5206",
    contactEmail: "hello@firesafety.com",
    contactAddress: "湖北省武汉市江汉区安防科技大厦 10 层",
    footerSlogan: "消防防盗专家 · 防患未然,守护每一刻。",
  },

  electrical: {
    heroTitle: "电力相连,安全无忧",
    heroSubtitle: "专业电气配件供应,断路器、开关插座到线缆配电,为用电安全提供坚实保障。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的电气配件供应企业,产品涵盖断路器、接触器、开关插座、电线电缆与配电箱柜等,广泛应用于家装、商业与工业配电等用电场景。",
      "我们坚持选用符合国标与行业认证的优质产品,严控品质与安全性能,既服务零售批发客户,也为工程项目提供稳定的电气配套供货与技术支持。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "安全是底线,六大优势守护每一度电。",
    features: [
      { title: "国标认证", desc: "产品符合国标认证,用电安全有保障。", icon: I.shield },
      { title: "可靠保护", desc: "过载短路精准保护,关键时刻能断电。", icon: I.bolt },
      { title: "耐用阻燃", desc: "阻燃材质与优质触点,长久耐用。", icon: I.award },
      { title: "品类齐全", desc: "强弱电配件一站齐备,选配更省心。", icon: I.cog },
      { title: "工程配套", desc: "配电箱柜成套配套,项目供货稳定。", icon: I.truck },
      { title: "技术支持", desc: "选型与配电方案专业答疑指导。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖零售批发与工程配套的电气供应。",
    services: [
      { name: "断路器接触器", desc: "低压电器元件,安全可靠的电路保护。" },
      { name: "开关插座", desc: "家装商用开关插座,款式齐全。" },
      { name: "电线电缆", desc: "国标电线电缆,阻燃耐用更安心。" },
      { name: "配电箱柜成套", desc: "配电箱柜定制成套与工程供货。" },
    ],
    stats: [
      { value: "20年", label: "电气供应" },
      { value: "8000+", label: "在售型号" },
      { value: "100%", label: "国标认证" },
      { value: "99%", label: "准时交付" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "陈工", role: "电气工程方", text: "配件型号齐全、证书规范,配电箱成套做得好,验收很顺利。" },
      { name: "黄老板", role: "建材批发商", text: "供货稳定、价格实在,品质有保障,客户复购率很高。" },
      { name: "刘师傅", role: "装修电工", text: "开关插座手感好、安装方便,接触可靠,用着特别放心。" },
    ],
    ctaTitle: "为用电安全加把锁",
    ctaSubtitle: "现在联系我们,获取电气配件报价与配套方案。",
    ctaButton: "立即询价",
    contactPhone: "400-888-5207",
    contactEmail: "hello@electrical.com",
    contactAddress: "浙江省温州市乐清市电气产业园 16 号",
    footerSlogan: "专业电气配件 · 电力相连,安全无忧。",
  },

  surveillance: {
    heroTitle: "全天候守望,安全看得见",
    heroSubtitle: "高清监控与智能安防系统,远程可视、智能预警,让每一处空间尽在掌握。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注监控安防的系统集成商,产品涵盖高清摄像机、网络录像机、智能门禁与可视对讲等,为家庭、商铺、园区与工厂提供清晰可靠的安防监控方案。",
      "我们融合 AI 智能分析与远程可视技术,提供从勘测设计、设备供应到布线安装与运维的一体化服务,让安全防护看得清、调得出、管得住。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "看得清更管得住,六大优势全程守护。",
    features: [
      { title: "高清成像", desc: "高清夜视摄像,画面清晰细节可辨。", icon: I.sparkle },
      { title: "智能预警", desc: "AI 人形车辆识别,异常自动报警。", icon: I.bolt },
      { title: "远程可视", desc: "手机随时查看回放,管理更省心。", icon: I.globe },
      { title: "稳定存储", desc: "录像稳定存储,关键画面不丢失。", icon: I.shield },
      { title: "整体设计", desc: "按场景定制点位,无死角覆盖。", icon: I.cog },
      { title: "安装运维", desc: "专业布线安装与长期运维支持。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖设备、安装与运维的安防一体化服务。",
    services: [
      { name: "高清监控系统", desc: "摄像机与录像主机成套供应。" },
      { name: "智能门禁对讲", desc: "门禁、可视对讲联动安防管理。" },
      { name: "方案设计施工", desc: "点位勘测、布线安装一站完成。" },
      { name: "远程运维服务", desc: "系统维护与故障响应,稳定运行。" },
    ],
    stats: [
      { value: "15年", label: "安防集成" },
      { value: "3000+", label: "落地项目" },
      { value: "7×24h", label: "在线监控" },
      { value: "98%", label: "客户满意" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "王老板", role: "连锁商铺", text: "多家门店统一联网监控,手机就能巡店,智能报警很实用。" },
      { name: "张经理", role: "园区管理方", text: "点位设计很合理,没有死角,运维响应快,安全管理省心多了。" },
      { name: "李先生", role: "家庭用户", text: "装了高清监控,出门在外也能看家,夜视清晰,很有安全感。" },
    ],
    ctaTitle: "为空间装上智慧之眼",
    ctaSubtitle: "现在联系我们,获取监控方案与上门勘测。",
    ctaButton: "预约勘测",
    contactPhone: "400-888-5208",
    contactEmail: "hello@surveillance.com",
    contactAddress: "广东省深圳市龙岗区安防科技园 B 座",
    footerSlogan: "智能监控安防 · 全天候守望,安全看得见。",
  },

  auto: {
    heroTitle: "驾享每一段旅程",
    heroSubtitle: "整车销售 · 专业养护,从选车购车到维修保养,做你身边贴心的汽车专家。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家集整车销售、维修保养、美容改装与保险理赔于一体的汽车服务企业,授权经营多个主流品牌车型,为车主提供省心、透明、专业的一站式用车服务。",
      "我们坚持原厂配件、规范工时与明码标价,配备专业技师团队与先进检测设备,从买车到养车全程贴心服务,让每一位车主都安心出行、畅享驾驶。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "买车养车都省心,六大优势相伴每段旅程。",
    features: [
      { title: "正规授权", desc: "品牌授权经营,新车手续齐全有保障。", icon: I.shield },
      { title: "原厂配件", desc: "原厂正品配件,保养维修更可靠。", icon: I.cog },
      { title: "透明报价", desc: "工时配件明码标价,消费明明白白。", icon: I.chart },
      { title: "专业技师", desc: "认证技师与精密检测,养护更专业。", icon: I.users },
      { title: "快捷服务", desc: "快保快修、免费检测,省时又省心。", icon: I.bolt },
      { title: "一站无忧", desc: "购车、保险、理赔一站搞定。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖购车到用车全周期的汽车服务。",
    services: [
      { name: "整车销售", desc: "多品牌车型一站选购,贷款分期无忧。" },
      { name: "保养维修", desc: "原厂配件专业养护,保养维修一站通。" },
      { name: "美容改装", desc: "贴膜镀晶、内饰升级与个性改装。" },
      { name: "保险理赔", desc: "保险办理与事故理赔协助,省心高效。" },
    ],
    stats: [
      { value: "16年", label: "汽车服务" },
      { value: "10万+", label: "服务车主" },
      { value: "100%", label: "原厂配件" },
      { value: "98%", label: "客户满意" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "周先生", role: "新车车主", text: "买车手续齐全、讲解专业,后续保养也方便,服务很到位。" },
      { name: "李女士", role: "保养客户", text: "工时配件明码标价,不乱收费,技师很负责,养车很放心。" },
      { name: "王师傅", role: "改装爱好者", text: "贴膜改装效果好、做工细,出了小事故理赔也帮忙跟进,省心。" },
    ],
    ctaTitle: "把爱车交给专业",
    ctaSubtitle: "现在预约,享受购车养车一站式贴心服务。",
    ctaButton: "立即预约",
    contactPhone: "400-888-5209",
    contactEmail: "hello@auto.com",
    contactAddress: "重庆市渝北区汽车园大道 99 号",
    footerSlogan: "汽车服务专家 · 驾享每一段旅程。",
  },
};
