import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「数码/家具/家居百货」各子类的精修中文文案（9 个 key）。
export const HOME_CONTENT: ContentMap = {
  digital: {
    brand: "极客优选数码",
    heroTitle: "科技好物，触手可及",
    heroSubtitle: "精选电脑与数码产品，为你的数字生活全面升级。",
    heroCta: "立即选购",
    heroCtaAlt: "查看爆款",
    aboutTitle: "关于极客优选",
    aboutBody: [
      "极客优选数码专注于电脑整机、笔记本与数码外设的销售与服务，覆盖办公、游戏、创作多种场景，所有产品均为正品行货，提供完善的安装、调试与质保支持。",
      "我们既懂硬件也懂需求，导购团队会根据你的预算与用途量身推荐配置，让每一分预算都花在刀刃上，买得明白、用得顺手。",
    ],
    featuresTitle: "为什么选极客优选",
    featuresSubtitle: "懂产品、懂场景、懂服务的数码伙伴。",
    features: [
      { title: "正品行货", desc: "官方授权渠道，假一赔十，全国联保。", icon: I.shield },
      { title: "性能严选", desc: "实测筛选高性价比配置，拒绝智商税。", icon: I.bolt },
      { title: "专业装机", desc: "工程师免费装机调试，开箱即用。", icon: I.cog },
      { title: "以旧换新", desc: "旧机高价回收，换新轻松又划算。", icon: I.cart },
      { title: "极速发货", desc: "现货当日发出，热门型号不断货。", icon: I.truck },
      { title: "贴心售后", desc: "上门检修与远程指导，问题快响应。", icon: I.phone },
    ],
    servicesTitle: "产品与服务",
    servicesSubtitle: "覆盖选购、装机到售后的全程数码服务。",
    services: [
      { name: "笔记本电脑", desc: "办公、游戏、创作本，按需精准推荐。" },
      { name: "智能外设", desc: "键鼠、显示器、存储配件齐全。" },
      { name: "以旧换新", desc: "旧设备高价回收，焕新无忧。" },
      { name: "上门维修", desc: "专业工程师快速响应，省心可靠。" },
    ],
    stats: [
      { value: "11年", label: "数码经验" },
      { value: "10万+", label: "成交用户" },
      { value: "99%", label: "好评率" },
      { value: "24h", label: "极速发货" },
    ],
    testimonialsTitle: "用户怎么说",
    testimonials: [
      { name: "小俊", role: "游戏玩家", text: "按预算配的机器性能拉满，装机调试都帮做好，开箱就能开黑。" },
      { name: "陈姐", role: "设计师", text: "推荐的创作本色准给力，以旧换新还省了一大笔，很专业。" },
      { name: "老吴", role: "企业采购", text: "批量采购正品有发票，售后响应快，公司设备都从这买。" },
    ],
    ctaTitle: "正在挑选数码好物？",
    ctaSubtitle: "告诉我们预算与用途，导购为你定制最优配置。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5101",
    contactEmail: "hello@digital.com",
    contactAddress: "深圳市福田区华强北路赛格数码广场 6 楼",
    footerSlogan: "极客优选数码 · 让科技为你的生活加速。",
  },

  appliance: {
    brand: "舒享生活电器",
    heroTitle: "好电器，让生活更舒心",
    heroSubtitle: "精选品质生活电器，把便利与品质带回每个家。",
    heroCta: "选购家电",
    heroCtaAlt: "热销榜单",
    aboutTitle: "关于舒享",
    aboutBody: [
      "舒享生活电器主营厨房电器、清洁电器与个护小家电，与多家知名品牌建立官方合作，从大家电到小家电一站配齐，覆盖装修新居与日常焕新的多样需求。",
      "我们坚持正品保障与省心服务，提供专业的选型建议、免费配送与上门安装，让你买家电不再纠结，用家电更加安心。",
    ],
    featuresTitle: "选择舒享的理由",
    featuresSubtitle: "品质、便利、安心一站满足。",
    features: [
      { title: "品牌正品", desc: "官方授权货源，品质与售后双保障。", icon: I.shield },
      { title: "节能省电", desc: "主推一级能效产品，长期用更省钱。", icon: I.bolt },
      { title: "送装一体", desc: "免费配送上门安装，到家即可用。", icon: I.truck },
      { title: "智能体验", desc: "智能互联家电，操作便捷更省心。", icon: I.cog },
      { title: "一站配齐", desc: "大小家电品类齐全，新居一次购齐。", icon: I.cart },
      { title: "无忧售后", desc: "全国联保，故障上门快速处理。", icon: I.phone },
    ],
    servicesTitle: "家电品类",
    servicesSubtitle: "覆盖厨房、客厅与个护的全屋家电。",
    services: [
      { name: "厨房电器", desc: "油烟机、灶具、洗碗机品质之选。" },
      { name: "清洁电器", desc: "扫地机、洗地机、吸尘器轻松打理。" },
      { name: "个护小家电", desc: "吹风机、剃须刀等精致生活之选。" },
      { name: "送装与售后", desc: "免费配送安装，全国联保无忧。" },
    ],
    stats: [
      { value: "13年", label: "家电零售" },
      { value: "30万+", label: "服务家庭" },
      { value: "98%", label: "满意度" },
      { value: "0元", label: "上门安装" },
    ],
    testimonialsTitle: "顾客评价",
    testimonials: [
      { name: "周女士", role: "新房业主", text: "全屋家电一次配齐，送装一条龙，入住前全部就位，太省事了。" },
      { name: "李先生", role: "回头客", text: "都是正品有发票，能效高用着省电，售后报修第二天就上门。" },
      { name: "张阿姨", role: "社区用户", text: "导购很耐心帮选型，洗碗机扫地机用了真香，邻居都来问。" },
    ],
    ctaTitle: "新家正在添置家电？",
    ctaSubtitle: "告诉我们户型与需求，为你搭配高性价比家电方案。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5102",
    contactEmail: "hello@appliance.com",
    contactAddress: "杭州市余杭区未来科技城舒享家电体验馆",
    footerSlogan: "舒享生活电器 · 让每个家都更省心。",
  },

  phone: {
    brand: "壹号手机通讯",
    heroTitle: "换新机，从这里开始",
    heroSubtitle: "正品手机与配件一站购齐，享贴心售后服务。",
    heroCta: "选购手机",
    heroCtaAlt: "配件专区",
    aboutTitle: "关于壹号",
    aboutBody: [
      "壹号手机通讯主营各大品牌智能手机及周边配件，所有机型均为正品行货、支持验机，门店与线上同价同质，是消费者放心换机的优选渠道。",
      "我们提供以旧换新、贴膜安装、数据迁移与碎屏维修等一站式服务，让你从选机到用机的每一步都省心又安心。",
    ],
    featuresTitle: "壹号的承诺",
    featuresSubtitle: "正品、保价、贴心服务全程在线。",
    features: [
      { title: "正品验机", desc: "官方渠道全新行货，支持当面验机。", icon: I.shield },
      { title: "全网比价", desc: "同款机型保价，买贵补差更安心。", icon: I.chart },
      { title: "以旧换新", desc: "旧机现场估价回收，换新更划算。", icon: I.cart },
      { title: "数据迁移", desc: "免费数据搬家，资料一键无缝转移。", icon: I.cog },
      { title: "碎屏速修", desc: "原厂配件快速维修，立等可取。", icon: I.bolt },
      { title: "贴心售后", desc: "全国联保 + 门店质保，售后无忧。", icon: I.phone },
    ],
    servicesTitle: "手机与配件",
    servicesSubtitle: "从换机到用机的一站式服务。",
    services: [
      { name: "全品牌手机", desc: "热门旗舰与高性价机型现货齐全。" },
      { name: "原厂配件", desc: "充电器、耳机、保护壳正品配套。" },
      { name: "以旧换新", desc: "旧机高价回收，差价换新无忧。" },
      { name: "维修贴膜", desc: "碎屏维修、贴膜安装专业到位。" },
    ],
    stats: [
      { value: "10年", label: "通讯零售" },
      { value: "50万+", label: "成交用户" },
      { value: "100%", label: "正品保障" },
      { value: "30分钟", label: "碎屏速修" },
    ],
    testimonialsTitle: "买家口碑",
    testimonials: [
      { name: "阿强", role: "学生用户", text: "现场验机透明，旧机换新抵了不少钱，数据还帮我全迁好了。" },
      { name: "陈先生", role: "上班族", text: "价格比官网还划算，碎屏当场就修好，服务确实靠谱。" },
      { name: "刘女士", role: "回头客", text: "全国联保有发票，家里几台手机都在这买，售后从不扯皮。" },
    ],
    ctaTitle: "准备换新机了吗？",
    ctaSubtitle: "到店或线上联系我们，享以旧换新与超值优惠。",
    ctaButton: "立即咨询",
    contactPhone: "400-888-5103",
    contactEmail: "hello@phone.com",
    contactAddress: "广州市天河区天河路壹号通讯数码城 1 楼",
    footerSlogan: "壹号手机通讯 · 正品换机，省心一号。",
  },

  furniture: {
    brand: "栖木家私家具",
    heroTitle: "为家，造一份美好",
    heroSubtitle: "原创设计家具，让每个空间都恰到好处。",
    heroCta: "预约设计",
    heroCtaAlt: "逛展厅",
    aboutTitle: "关于栖木",
    aboutBody: [
      "栖木家私家具集设计、生产与销售于一体，主营实木与板木家具及全屋定制，从客厅、卧室到书房，为不同户型提供兼具美感与实用的家居解决方案。",
      "我们坚持环保选材与精工细作，从板材到五金均严格把关，配合专业的空间设计与送装服务，让每一件家具都恰好融入你的生活。",
    ],
    featuresTitle: "栖木的坚持",
    featuresSubtitle: "好设计、好材料、好服务缺一不可。",
    features: [
      { title: "原创设计", desc: "自有设计团队，造型耐看不撞款。", icon: I.sparkle },
      { title: "环保选材", desc: "甄选环保板材与实木，安心居家。", icon: I.leaf },
      { title: "全屋定制", desc: "按户型量身设计，空间利用最大化。", icon: I.cog },
      { title: "精工品质", desc: "精细打磨与五金把关，经久耐用。", icon: I.award },
      { title: "送装一体", desc: "免费配送专业安装，到家即享。", icon: I.truck },
      { title: "质保无忧", desc: "多年质保与售后维护，长久安心。", icon: I.shield },
    ],
    servicesTitle: "家具与服务",
    servicesSubtitle: "从单品到全屋的一站家居方案。",
    services: [
      { name: "全屋定制", desc: "量身设计，柜体与空间一站到位。" },
      { name: "实木家具", desc: "精选木材，环保工艺，质感十足。" },
      { name: "软装搭配", desc: "专业软装设计，提升整体格调。" },
      { name: "送装一体", desc: "免费配送，专业安装，省心无忧。" },
    ],
    stats: [
      { value: "19年", label: "家具制造" },
      { value: "10万+", label: "服务家庭" },
      { value: "96%", label: "满意度" },
      { value: "10年", label: "质保承诺" },
    ],
    testimonialsTitle: "业主评价",
    testimonials: [
      { name: "孙女士", role: "新房业主", text: "全屋定制把每个角落都利用上了，设计师审美在线，太满意了。" },
      { name: "赵先生", role: "实木爱好者", text: "实木做工扎实、味道很淡，用了一年依旧稳固如新。" },
      { name: "钱太太", role: "改善型用户", text: "从设计到送装一条龙，软装搭配也帮做了，住进去特别舒服。" },
    ],
    ctaTitle: "想为家添置好家具？",
    ctaSubtitle: "预约设计师上门量尺，获取专属全屋方案。",
    ctaButton: "免费预约",
    contactPhone: "400-888-5104",
    contactEmail: "hello@furniture.com",
    contactAddress: "佛山市顺德区龙江镇栖木家具展销中心 3 号馆",
    footerSlogan: "栖木家私家具 · 为生活造一处栖居。",
  },

  kitchenware: {
    brand: "鼎厨餐厨用品",
    heroTitle: "好厨具，烹出好生活",
    heroSubtitle: "专业餐饮与家用厨房用品，让烹饪更得心应手。",
    heroCta: "选购厨具",
    heroCtaAlt: "商用专区",
    aboutTitle: "关于鼎厨",
    aboutBody: [
      "鼎厨餐厨用品主营家用与商用厨房用品，涵盖锅具、刀具、餐具与厨房收纳，既服务追求品质的家庭厨房，也为餐厅、食堂提供整套商用厨具配套。",
      "我们坚持选用食品级安全材质与耐用工艺，从一口锅到一整套出餐设备都经得起高频使用，让专业与家用厨房都更高效省心。",
    ],
    featuresTitle: "鼎厨的优势",
    featuresSubtitle: "安全、耐用、专业的厨房好帮手。",
    features: [
      { title: "食品级材质", desc: "选用安全无毒材质，入口更放心。", icon: I.shield },
      { title: "耐用工艺", desc: "加厚耐磨结构，经得起高频使用。", icon: I.bolt },
      { title: "商用配套", desc: "餐厅食堂整套厨具一站配齐。", icon: I.cart },
      { title: "精工锋利", desc: "刀具锋利持久，切配省力又顺手。", icon: I.star },
      { title: "易洗易收", desc: "防粘耐刷、收纳合理，厨房更整洁。", icon: I.sparkle },
      { title: "贴心售后", desc: "破损补配、质保无忧，长期省心。", icon: I.phone },
    ],
    servicesTitle: "厨房用品线",
    servicesSubtitle: "覆盖家用到商用的全套餐厨方案。",
    services: [
      { name: "品质锅具", desc: "炒锅、汤锅、煎锅，导热均匀耐用。" },
      { name: "专业刀具", desc: "中式厨刀与套刀，锋利持久好用。" },
      { name: "餐具用品", desc: "碗碟杯具与餐厨配件，成套搭配。" },
      { name: "商用配套", desc: "餐厅食堂整体厨具选型与供应。" },
    ],
    stats: [
      { value: "15年", label: "餐厨经验" },
      { value: "5000+", label: "餐饮客户" },
      { value: "99%", label: "好评率" },
      { value: "48h", label: "快速发货" },
    ],
    testimonialsTitle: "客户的认可",
    testimonials: [
      { name: "陈师傅", role: "餐厅主厨", text: "整套商用厨具一次配齐，锅具耐用刀具顺手，出餐效率高多了。" },
      { name: "周女士", role: "家庭主妇", text: "炒锅不粘好洗，刀切菜很省力，下厨幸福感直线上升。" },
      { name: "李经理", role: "食堂采购", text: "材质安全有检测，破损还能补配，大批量采购很省心。" },
    ],
    ctaTitle: "厨房想升级一套好装备？",
    ctaSubtitle: "告诉我们家用还是商用，为你搭配合适的厨具方案。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5105",
    contactEmail: "hello@kitchenware.com",
    contactAddress: "潮州市潮安区彩塘镇鼎厨不锈钢制品园",
    footerSlogan: "鼎厨餐厨用品 · 让烹饪成为一种享受。",
  },

  decor: {
    brand: "栖意家居软饰",
    heroTitle: "软饰之美，点亮居所",
    heroSubtitle: "精选家居软装饰品，为空间注入温度与格调。",
    heroCta: "选购软饰",
    heroCtaAlt: "看搭配案例",
    aboutTitle: "关于栖意",
    aboutBody: [
      "栖意家居软饰专注于窗帘、地毯、抱枕、挂画与装饰摆件等软装产品，风格涵盖现代、轻奢、北欧与新中式，为家庭与商业空间提供整体软装搭配方案。",
      "我们相信细节成就格调，从面料到配色都精心甄选，并提供专业的软装设计服务，用恰到好处的软饰让空间更有温度、更显品味。",
    ],
    featuresTitle: "栖意的格调",
    featuresSubtitle: "懂搭配、重品质、有温度的软装专家。",
    features: [
      { title: "风格齐全", desc: "多种风格软饰任选，搭出理想空间。", icon: I.sparkle },
      { title: "精选面料", desc: "优质环保面料，质感与耐用兼具。", icon: I.leaf },
      { title: "整体搭配", desc: "色彩与材质统一规划，告别杂乱。", icon: I.star },
      { title: "软装设计", desc: "设计师整体提案，所见即所得。", icon: I.users },
      { title: "上门测量", desc: "窗帘等定品上门测量，尺寸精准。", icon: I.cog },
      { title: "送装服务", desc: "配送安装一体，到家轻松焕新。", icon: I.truck },
    ],
    servicesTitle: "软装产品线",
    servicesSubtitle: "用软饰为空间锦上添花。",
    services: [
      { name: "窗帘布艺", desc: "遮光、纱帘等多款,量身定制安装。" },
      { name: "地毯抱枕", desc: "客厅卧室软饰,提升舒适与质感。" },
      { name: "装饰挂画", desc: "风格挂画与摆件,点睛整体空间。" },
      { name: "整体软装设计", desc: "一站式软装提案与落地服务。" },
    ],
    stats: [
      { value: "12年", label: "软装经验" },
      { value: "20万+", label: "搭配案例" },
      { value: "97%", label: "满意度" },
      { value: "0元", label: "上门测量" },
    ],
    testimonialsTitle: "客户评价",
    testimonials: [
      { name: "林女士", role: "家居业主", text: "整体软装搭下来,家里档次一下提升了,窗帘配色尤其惊艳。" },
      { name: "黄先生", role: "民宿主理人", text: "软饰风格统一又出片,客人入住好评率明显上去了。" },
      { name: "吴小姐", role: "回头客", text: "面料环保有味道淡,设计师审美在线,换季再来找她搭。" },
    ],
    ctaTitle: "想给家换个气质？",
    ctaSubtitle: "预约软装设计师,用软饰为你的空间重新调味。",
    ctaButton: "免费预约",
    contactPhone: "400-888-5106",
    contactEmail: "hello@decor.com",
    contactAddress: "苏州市姑苏区平江路栖意软装生活馆",
    footerSlogan: "栖意家居软饰 · 让家更有温度与格调。",
  },

  bedding: {
    brand: "云眠床上用品",
    heroTitle: "好睡眠，从一床好被开始",
    heroSubtitle: "舒适亲肤的床上用品，给你每晚安心好眠。",
    heroCta: "选购床品",
    heroCtaAlt: "热销套件",
    aboutTitle: "关于云眠",
    aboutBody: [
      "云眠床上用品专注于四件套、被芯、枕芯与床垫等寝具的研发与销售，从面料织造到成品检测层层把关，致力于把舒适、亲肤、健康的睡眠体验带进每个家庭。",
      "我们坚持高支高密面料与环保填充工艺，兼顾透气性与耐用度,无论换季还是日常,都能为你打造贴合身体、安心舒适的睡眠空间。",
    ],
    featuresTitle: "云眠的用心",
    featuresSubtitle: "为好睡眠认真对待每一处细节。",
    features: [
      { title: "亲肤面料", desc: "高支高密棉,柔软透气贴肤更舒适。", icon: I.heart },
      { title: "健康环保", desc: "环保染整与填充,无刺激更安心。", icon: I.leaf },
      { title: "四季适用", desc: "分季被芯搭配,冷暖随心好入眠。", icon: I.clock },
      { title: "工艺精良", desc: "走线平整、做工扎实,经久耐用。", icon: I.award },
      { title: "易打理", desc: "耐洗不易变形,日常护理省心。", icon: I.sparkle },
      { title: "贴心售后", desc: "色差破损无忧换,购物更放心。", icon: I.shield },
    ],
    servicesTitle: "床品系列",
    servicesSubtitle: "一站配齐卧室的舒适寝具。",
    services: [
      { name: "床品四件套", desc: "高支棉套件,亲肤透气易打理。" },
      { name: "被芯枕芯", desc: "分季被芯与护颈枕,冷暖贴合。" },
      { name: "床垫床褥", desc: "软硬适中床垫,承托脊椎更安睡。" },
      { name: "套件定制", desc: "尺寸与花色定制,适配各种床型。" },
    ],
    stats: [
      { value: "14年", label: "寝具经验" },
      { value: "40万+", label: "睡眠家庭" },
      { value: "98%", label: "好评率" },
      { value: "7天", label: "无忧退换" },
    ],
    testimonialsTitle: "顾客好评",
    testimonials: [
      { name: "苏女士", role: "家庭用户", text: "四件套摸着特别柔软,睡上去很亲肤,洗了几次也不起球。" },
      { name: "郑先生", role: "回头客", text: "冬被又轻又暖,换季再也不用纠结,一家人都换成云眠了。" },
      { name: "何小姐", role: "新婚用户", text: "婚房床品定制了尺寸,花色高级,睡眠质量肉眼可见变好。" },
    ],
    ctaTitle: "想拥有一夜好眠？",
    ctaSubtitle: "联系我们挑选合适的床品,把舒适睡眠带回家。",
    ctaButton: "立即选购",
    contactPhone: "400-888-5107",
    contactEmail: "hello@bedding.com",
    contactAddress: "南通市通州区家纺城云眠寝具旗舰馆",
    footerSlogan: "云眠床上用品 · 用心呵护你的每一夜。",
  },

  towel: {
    brand: "棉柔毛巾巾品",
    heroTitle: "柔软触感，呵护每一天",
    heroSubtitle: "高品质毛巾巾类产品，吸水柔软，贴心日常。",
    heroCta: "选购毛巾",
    heroCtaAlt: "礼盒专区",
    aboutTitle: "关于棉柔",
    aboutBody: [
      "棉柔毛巾巾品专注于面巾、浴巾、方巾及各类巾类产品的生产销售,从家庭日用到酒店采购、商务礼赠,提供柔软吸水、安全卫生的优质巾品。",
      "我们坚持精梳长绒棉与无荧光剂工艺,注重吸水性与耐久度,让每一条毛巾都柔软贴肤、久用不掉毛,把舒适与安心融入日常每一刻。",
    ],
    featuresTitle: "棉柔的品质",
    featuresSubtitle: "柔软、吸水、安全是我们的底线。",
    features: [
      { title: "精梳长绒棉", desc: "选用优质长绒棉,柔软厚实更亲肤。", icon: I.heart },
      { title: "强力吸水", desc: "高密织造速吸快干,清爽不黏腻。", icon: I.bolt },
      { title: "安全无添加", desc: "无荧光剂无刺激,贴脸用更放心。", icon: I.shield },
      { title: "久用不掉毛", desc: "锁边扎实耐洗,反复使用依旧柔软。", icon: I.award },
      { title: "礼盒定制", desc: "毛巾礼盒可定制 logo,商务馈赠体面。", icon: I.sparkle },
      { title: "批量供应", desc: "酒店宾馆整批供货,品质统一稳定。", icon: I.truck },
    ],
    servicesTitle: "巾品系列",
    servicesSubtitle: "覆盖家用、商用与礼赠的全线巾品。",
    services: [
      { name: "面巾浴巾", desc: "纯棉吸水,日常洗护柔软贴肤。" },
      { name: "酒店巾品", desc: "宾馆专用巾品,品质统一耐用。" },
      { name: "礼盒套装", desc: "精美礼盒,送礼自用两相宜。" },
      { name: "定制印绣", desc: "logo 印绣定制,品牌专属巾品。" },
    ],
    stats: [
      { value: "13年", label: "巾品制造" },
      { value: "3000+", label: "合作客户" },
      { value: "99%", label: "好评率" },
      { value: "48h", label: "快速发货" },
    ],
    testimonialsTitle: "用户口碑",
    testimonials: [
      { name: "王女士", role: "家庭用户", text: "毛巾又软又吸水,洗脸特别舒服,用了大半年也不掉毛。" },
      { name: "张经理", role: "酒店采购", text: "整批巾品品质很统一,客人反馈手感好,复购很省心。" },
      { name: "刘先生", role: "企业客户", text: "定制了 logo 礼盒发给客户,体面又实用,反响很不错。" },
    ],
    ctaTitle: "想挑选优质毛巾？",
    ctaSubtitle: "无论家用还是采购,联系我们获取专属巾品方案。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5108",
    contactEmail: "hello@towel.com",
    contactAddress: "石家庄市高邑县纺织工业园棉柔巾品厂",
    footerSlogan: "棉柔毛巾巾品 · 把柔软带进日常每一刻。",
  },

  lighting: {
    brand: "光屿灯具灯饰",
    heroTitle: "点亮空间，更点亮生活",
    heroSubtitle: "精选灯具灯饰，用光影为家与商业空间塑造氛围。",
    heroCta: "选购灯具",
    heroCtaAlt: "工程合作",
    aboutTitle: "关于光屿",
    aboutBody: [
      "光屿灯具灯饰主营家居照明、商业照明与装饰灯饰,产品涵盖吊灯、筒灯、灯带与智能照明系统,既服务家装用户,也承接酒店、商铺等工程照明项目。",
      "我们注重光效与美学的平衡,从光源品质到造型设计层层把关,并提供专业的照明设计建议,让恰当的光线营造出舒适而有格调的空间氛围。",
    ],
    featuresTitle: "光屿的专业",
    featuresSubtitle: "懂光、懂美、懂场景的照明专家。",
    features: [
      { title: "护眼光源", desc: "高显色低频闪,照明舒适更护眼。", icon: I.star },
      { title: "节能省电", desc: "优质 LED 高光效,长寿命更省电。", icon: I.bolt },
      { title: "智能照明", desc: "调光调色、远程控制,光随心动。", icon: I.cog },
      { title: "设计美学", desc: "造型多样耐看,灯饰也是空间艺术。", icon: I.sparkle },
      { title: "照明设计", desc: "提供空间布光方案,光效与氛围兼得。", icon: I.users },
      { title: "工程配套", desc: "酒店商铺整体照明,选型供货一站。", icon: I.globe },
    ],
    servicesTitle: "灯具与服务",
    servicesSubtitle: "覆盖家装到工程的整体照明方案。",
    services: [
      { name: "家居照明", desc: "吊灯、吸顶灯、筒射灯,布光更得当。" },
      { name: "装饰灯饰", desc: "氛围灯带与艺术灯饰,点亮格调。" },
      { name: "智能照明", desc: "可调光调色系统,场景一键切换。" },
      { name: "工程照明", desc: "商业空间整体照明设计与供货。" },
    ],
    stats: [
      { value: "16年", label: "照明经验" },
      { value: "1200+", label: "工程案例" },
      { value: "98%", label: "满意度" },
      { value: "5年", label: "质保承诺" },
    ],
    testimonialsTitle: "客户评价",
    testimonials: [
      { name: "陈女士", role: "家装业主", text: "全屋布光方案做得很专业,灯光层次分明,家里氛围一下高级了。" },
      { name: "罗经理", role: "酒店项目", text: "工程照明从设计到供货一条龙,光效统一,验收非常顺利。" },
      { name: "周先生", role: "商铺老板", text: "智能灯带切换场景很方便,顾客进店感觉好,出片率也高。" },
    ],
    ctaTitle: "想为空间设计灯光？",
    ctaSubtitle: "把空间和需求告诉我们,获取专业布光方案与报价。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5109",
    contactEmail: "hello@lighting.com",
    contactAddress: "中山市古镇镇灯都大道光屿照明展厅 A 座",
    footerSlogan: "光屿灯具灯饰 · 用光影点亮美好生活。",
  },
};
