import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「化工/环保/农林牧渔」各子类的精修中文文案（8 个 key）。
export const INDUSTRY_CONTENT: ContentMap = {
  "chem-material": {
    brand: "宏基建材化工",
    heroTitle: "筑基每一项工程的可靠选择",
    heroSubtitle: "建筑与化工材料一体化供应，让品质从源头开始。",
    heroCta: "获取报价",
    heroCtaAlt: "下载样册",
    aboutTitle: "关于宏基",
    aboutBody: [
      "宏基建材化工深耕建筑与化工材料领域二十余年，业务涵盖防水材料、外加剂、保温系统与特种砂浆，年供应能力覆盖华东大型基建与商品房项目，是众多总包单位的长期合作供应商。",
      "我们自建研发实验室与质检中心，每一批产品出厂前均经过力学、耐候与环保多维度检测，以稳定的品质与准时的交付，为客户的工程进度与质量保驾护航。",
    ],
    featuresTitle: "为什么选择宏基",
    featuresSubtitle: "从原料到现场，六重保障贯穿每一道环节。",
    features: [
      { title: "国标品质", desc: "全线产品符合并优于现行国家标准，质检报告随货可查。", icon: I.shield },
      { title: "自有研发", desc: "实验室持续优化配方，应对不同气候与工况需求。", icon: I.cog },
      { title: "稳定供货", desc: "三大区域仓储联动，旺季工程也能准时到料。", icon: I.truck },
      { title: "环保达标", desc: "低 VOC 配方，满足绿色建筑与环评要求。", icon: I.leaf },
      { title: "技术驻场", desc: "工程师现场指导施工配比，减少返工浪费。", icon: I.users },
      { title: "全程溯源", desc: "批次编码全程可追溯，质量责任清晰可控。", icon: I.chart },
    ],
    servicesTitle: "核心产品与服务",
    servicesSubtitle: "覆盖建筑全周期的材料与化工解决方案。",
    services: [
      { name: "建筑防水材料", desc: "卷材、涂料、密封胶，地下与屋面整体防水。" },
      { name: "混凝土外加剂", desc: "减水剂、缓凝剂等，提升强度与施工性能。" },
      { name: "特种砂浆", desc: "瓷砖胶、自流平、修补砂浆，适配多种基面。" },
      { name: "保温隔热系统", desc: "外墙保温一体化方案，节能又耐久。" },
    ],
    stats: [
      { value: "22年", label: "行业深耕" },
      { value: "1800+", label: "合作项目" },
      { value: "99%", label: "批次合格率" },
      { value: "48h", label: "区域急送" },
    ],
    testimonialsTitle: "客户的信任",
    testimonials: [
      { name: "周工", role: "总包项目经理", text: "防水材料质量稳定，技术老师还到工地指导配比，工程验收很省心。" },
      { name: "陈总", role: "建材经销商", text: "供货及时、价格透明，旺季也不掉链子，合作三年从没出过问题。" },
      { name: "李监理", role: "工程监理", text: "每批料都有完整检测报告，溯源清晰，监理这边特别放心。" },
    ],
    ctaTitle: "正在为工程选材？",
    ctaSubtitle: "把项目需求告诉我们，获取专属配比方案与优惠报价。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-4101",
    contactEmail: "hello@chem-material.com",
    contactAddress: "南京市江宁区科创大道 286 号宏基产业园",
    footerSlogan: "宏基建材化工 · 以品质夯实每一项工程。",
  },

  textile: {
    brand: "锦丰纺织辅料",
    heroTitle: "成衣品质，始于每一根丝线",
    heroSubtitle: "专业纺织辅料供应，为服装制造提供稳定可靠的配套。",
    heroCta: "索取样卡",
    heroCtaAlt: "在线选样",
    aboutTitle: "关于锦丰",
    aboutBody: [
      "锦丰纺织辅料专注于缝纫线、织带、拉链、纽扣等服装辅料的研发与供应，服务对象涵盖外贸成衣厂、品牌服饰与箱包企业，色卡齐全、起订灵活，是珠三角众多工厂的稳定辅料伙伴。",
      "我们坚持环保染料与坚牢度优先的选材理念，所有色号均可量产复色，配合快速打样与小批量试单，帮助客户在交期与品质之间取得最佳平衡。",
    ],
    featuresTitle: "锦丰的优势",
    featuresSubtitle: "懂工厂、懂交期、懂品质的辅料供应商。",
    features: [
      { title: "色号齐全", desc: "上千常备色号，疑难色三天内复色出样。", icon: I.sparkle },
      { title: "环保染料", desc: "通过环保检测，满足国际买家合规要求。", icon: I.leaf },
      { title: "坚牢度高", desc: "耐洗耐摩擦，成衣水洗后不掉色不变形。", icon: I.shield },
      { title: "快速打样", desc: "常规打样 24 小时，紧急订单优先排产。", icon: I.bolt },
      { title: "小单友好", desc: "灵活起订量，新款试单也能轻松配套。", icon: I.cart },
      { title: "稳定交期", desc: "自有产线 + 安全库存，旺季交付不延误。", icon: I.clock },
    ],
    servicesTitle: "辅料产品线",
    servicesSubtitle: "一站配齐成衣所需的各类辅料。",
    services: [
      { name: "高强缝纫线", desc: "涤纶、尼龙各规格，色牢度与强度兼优。" },
      { name: "织带与松紧带", desc: "罗纹、人字、弹力带，宽窄花型可定制。" },
      { name: "拉链与纽扣", desc: "金属、树脂、隐形拉链及配套钮扣五金。" },
      { name: "标牌与洗唛", desc: "织唛、印唛、吊牌，品牌信息精准呈现。" },
    ],
    stats: [
      { value: "16年", label: "辅料经验" },
      { value: "2000+", label: "常备色号" },
      { value: "24h", label: "常规打样" },
      { value: "600+", label: "合作工厂" },
    ],
    testimonialsTitle: "工厂的口碑",
    testimonials: [
      { name: "黄厂长", role: "成衣厂采购", text: "复色又快又准，水洗测试一次过，再也不用担心买家投诉色差。" },
      { name: "Linda", role: "外贸跟单", text: "环保报告齐全，欧美客户的合规要求都能满足，跟单省了大量沟通。" },
      { name: "吴老板", role: "品牌服饰", text: "小单也愿意配，打样速度快，新款上市节奏跟得上。" },
    ],
    ctaTitle: "新一季备料开始了吗？",
    ctaSubtitle: "发来色卡或样衣，我们为你快速配齐全套辅料。",
    ctaButton: "立即配料",
    contactPhone: "400-888-4102",
    contactEmail: "hello@textile.com",
    contactAddress: "广州市番禺区大龙街锦绣纺织城 B 区 12 栋",
    footerSlogan: "锦丰纺织辅料 · 让每一件成衣都经得起检验。",
  },

  "rubber-plastic": {
    brand: "恒塑橡塑科技",
    heroTitle: "弹性与韧性，源自专业制造",
    heroSubtitle: "橡胶与塑料制品定制生产，配套各行业精密需求。",
    heroCta: "提交图纸",
    heroCtaAlt: "查看案例",
    aboutTitle: "关于恒塑",
    aboutBody: [
      "恒塑橡塑科技专注橡胶密封件、塑料注塑件与改性材料的研发制造，产品广泛应用于汽车、家电、工程机械与管道密封领域，具备从模具开发到批量生产的一体化能力。",
      "我们拥有精密注塑机群与硫化生产线，配合三坐标检测与材料分析，确保每一件制品在尺寸精度、耐温与耐老化性能上都达到客户的严苛标准。",
    ],
    featuresTitle: "恒塑制造实力",
    featuresSubtitle: "从一颗胶粒到一件精密制品的全程把控。",
    features: [
      { title: "模具自研", desc: "自有模具车间，开模周期短、修模响应快。", icon: I.cog },
      { title: "材料改性", desc: "按工况调配料,耐温耐油耐老化按需定制。", icon: I.bolt },
      { title: "精密成型", desc: "全自动注塑与硫化，尺寸公差稳定可控。", icon: I.chart },
      { title: "全检出厂", desc: "三坐标与气密检测，杜绝不良流入产线。", icon: I.shield },
      { title: "批量交付", desc: "多机台并行排产，大单也能按期出货。", icon: I.truck },
      { title: "环保用料", desc: "可选无卤、食品级原料，满足合规需求。", icon: I.leaf },
    ],
    servicesTitle: "橡塑制品方案",
    servicesSubtitle: "覆盖密封、结构与功能件的定制制造。",
    services: [
      { name: "橡胶密封件", desc: "O 形圈、油封、异形密封，耐压耐介质。" },
      { name: "塑料注塑件", desc: "结构件、外壳、连接件，精密批量成型。" },
      { name: "改性材料供应", desc: "增强、阻燃、耐候改性粒料按需定制。" },
      { name: "模具开发", desc: "从设计到试模，缩短产品上市周期。" },
    ],
    stats: [
      { value: "18年", label: "橡塑制造" },
      { value: "120台", label: "成型设备" },
      { value: "±0.02mm", label: "成型精度" },
      { value: "300+", label: "配套客户" },
    ],
    testimonialsTitle: "合作方评价",
    testimonials: [
      { name: "钱工", role: "汽车零部件采购", text: "密封件耐温耐油性能稳定，装车测试零渗漏，配套很省心。" },
      { name: "孙经理", role: "家电制造商", text: "开模快、修模及时，新品量产节点踩得很准，配合度很高。" },
      { name: "赵总", role: "工程机械厂", text: "大批量交付从不拖期，质量一致性好，是值得长期合作的伙伴。" },
    ],
    ctaTitle: "有橡塑件需要打样？",
    ctaSubtitle: "发来 3D 图纸或样件，我们为你评估方案与报价。",
    ctaButton: "免费评估",
    contactPhone: "400-888-4103",
    contactEmail: "hello@rubber-plastic.com",
    contactAddress: "宁波市北仑区临港工业区恒塑路 9 号",
    footerSlogan: "恒塑橡塑科技 · 以精密成型铸就可靠配套。",
  },

  metallurgy: {
    brand: "金鼎冶金矿产",
    heroTitle: "钢铁脊梁，矿产为基",
    heroSubtitle: "冶金原料与矿产资源供应，为工业制造夯实根基。",
    heroCta: "询价采购",
    heroCtaAlt: "了解资源",
    aboutTitle: "关于金鼎",
    aboutBody: [
      "金鼎冶金矿产从事铁矿石、合金、有色金属及冶金辅料的贸易与供应，拥有稳定的矿源渠道与港口仓储资源，服务钢厂、铸造厂与冶炼企业，是产业链上游可靠的资源整合者。",
      "我们以化验数据说话，每一批矿料与合金均提供权威检测成分单，配合灵活的物流与结算方案，帮助客户控制原料成本、保障生产连续。",
    ],
    featuresTitle: "金鼎的资源力",
    featuresSubtitle: "上游矿源、港口仓储与专业化验的三重保障。",
    features: [
      { title: "矿源稳定", desc: "长期合作矿山与进口渠道，货源持续可靠。", icon: I.globe },
      { title: "成分准确", desc: "第三方化验出具成分单，品位真实可查。", icon: I.chart },
      { title: "港口仓储", desc: "临港堆场就近发货，缩短到厂周期。", icon: I.truck },
      { title: "规格齐全", desc: "矿粉、块矿、合金多牌号现货可选。", icon: I.cog },
      { title: "灵活结算", desc: "多种结算与账期方案，缓解资金压力。", icon: I.award },
      { title: "诚信经营", desc: "足量足秤、长期口碑，复购率高。", icon: I.shield },
    ],
    servicesTitle: "冶金矿产供应",
    servicesSubtitle: "贯通矿料、合金与辅料的一站采购。",
    services: [
      { name: "铁矿石供应", desc: "进口与国产矿粉、块矿，品位稳定。" },
      { name: "铁合金贸易", desc: "硅锰、铬铁等合金，牌号齐全可调。" },
      { name: "有色金属", desc: "铜、铝、锌锭及精矿现货供应。" },
      { name: "冶金辅料", desc: "石灰、焦炭、耐材等配套辅料供应。" },
    ],
    stats: [
      { value: "20年", label: "矿贸经验" },
      { value: "30万吨", label: "年供应量" },
      { value: "12个", label: "合作港口" },
      { value: "98%", label: "履约率" },
    ],
    testimonialsTitle: "用户评价",
    testimonials: [
      { name: "刘厂长", role: "钢厂采购", text: "品位稳定、化验数据真实，按这个矿料配料生产很省心。" },
      { name: "马总", role: "铸造企业", text: "合金牌号齐全，临港仓发货快，原料从没断过供。" },
      { name: "郑经理", role: "冶炼公司", text: "结算灵活、足量足秤，长期合作下来非常信得过。" },
    ],
    ctaTitle: "需要稳定的矿料供应？",
    ctaSubtitle: "告诉我们品类与用量，获取实时行情与现货报价。",
    ctaButton: "获取报价",
    contactPhone: "400-888-4104",
    contactEmail: "hello@metallurgy.com",
    contactAddress: "唐山市曹妃甸工业区临港大道 58 号",
    footerSlogan: "金鼎冶金矿产 · 做产业链上可靠的资源伙伴。",
  },

  recycling: {
    brand: "绿源环保回收",
    heroTitle: "让资源，循环新生",
    heroSubtitle: "绿色环保回收，为可持续未来贡献每一份力量。",
    heroCta: "预约上门",
    heroCtaAlt: "了解流程",
    aboutTitle: "关于绿源",
    aboutBody: [
      "绿源环保回收专注于工业废料与再生资源的回收处理，业务覆盖废金属、废塑料、废纸及电子废弃物，持有正规环保资质，与众多工厂、园区建立了长期稳定的回收合作关系。",
      "我们坚持无害化处理与资源再生并重，通过规范的分拣、清洗与再加工流程，让废弃物重新进入生产循环，既为企业降本，也为城市减负。",
    ],
    featuresTitle: "选择绿源的理由",
    featuresSubtitle: "合规、透明、环保的全链条回收服务。",
    features: [
      { title: "资质齐全", desc: "持有正规环保经营许可，处置全程合规。", icon: I.shield },
      { title: "上门回收", desc: "园区与厂区定点上门，省心又高效。", icon: I.truck },
      { title: "公道计价", desc: "电子地磅、透明称重，价格随行就市。", icon: I.chart },
      { title: "无害处理", desc: "规范分拣与无害化处置，达标排放。", icon: I.leaf },
      { title: "资源再生", desc: "再生材料回炉利用,真正变废为宝。", icon: I.sparkle },
      { title: "环评咨询", desc: "提供环保合规与减废方案咨询服务。", icon: I.users },
    ],
    servicesTitle: "回收处理服务",
    servicesSubtitle: "覆盖各类再生资源的回收与再利用。",
    services: [
      { name: "废金属回收", desc: "废钢、废铜铝等金属规范回收再生。" },
      { name: "废塑料回收", desc: "各类塑料分类回收，造粒再利用。" },
      { name: "电子废弃物", desc: "废旧设备拆解，无害化合规处置。" },
      { name: "环评与咨询", desc: "企业减废与环保合规方案设计。" },
    ],
    stats: [
      { value: "15年", label: "行业经验" },
      { value: "8万吨", label: "年回收量" },
      { value: "500+", label: "合作企业" },
      { value: "100%", label: "合规处置" },
    ],
    testimonialsTitle: "合作企业说",
    testimonials: [
      { name: "杨经理", role: "合作企业", text: "称重透明、结算及时，厂区废料处理交给绿源完全放心。" },
      { name: "何主任", role: "园区管理方", text: "上门回收很规范，台账齐全，环保检查时资料一应俱全。" },
      { name: "曾总", role: "制造企业", text: "废料变成了再生收益，还帮我们做了减废方案，一举两得。" },
    ],
    ctaTitle: "厂区还有废料堆积？",
    ctaSubtitle: "现在预约上门评估，让闲置废料变成绿色收益。",
    ctaButton: "免费预约",
    contactPhone: "400-888-4105",
    contactEmail: "hello@recycling.com",
    contactAddress: "苏州市吴江区汾湖高新区环保产业园 7 号",
    footerSlogan: "绿源环保回收 · 让每一份资源都物尽其用。",
  },

  farming: {
    brand: "沃野生态农场",
    heroTitle: "从田间到餐桌的安心",
    heroSubtitle: "生态种植 · 绿色农产，把健康送到每个家庭。",
    heroCta: "采购洽谈",
    heroCtaAlt: "参观基地",
    aboutTitle: "关于沃野",
    aboutBody: [
      "沃野生态农场拥有连片标准化种植基地，主营时令果蔬、粮油作物与特色经济作物，从选种、田管到采收全程标准化作业，是商超、食堂与社区团购信赖的稳定产地供应方。",
      "我们坚持绿色生态种植理念，减少化学投入、注重土壤养护，配合订单农业模式实现产销精准对接，让好农产以更新鲜的状态直达客户。",
    ],
    featuresTitle: "沃野的承诺",
    featuresSubtitle: "源头把控，让每一份农产都安心。",
    features: [
      { title: "源头种植", desc: "自有基地标准化管理，品质从田头抓起。", icon: I.leaf },
      { title: "绿色无公害", desc: "减药减肥、生态防治，检测合格上市。", icon: I.shield },
      { title: "订单农业", desc: "产销对接、按需种植，供应稳定不滞销。", icon: I.chart },
      { title: "产地直供", desc: "基地直发，减少中间环节更新鲜。", icon: I.truck },
      { title: "农技支持", desc: "驻场农艺师指导，产量品质双提升。", icon: I.users },
      { title: "全程溯源", desc: "种植档案可追溯，吃得明白更放心。", icon: I.globe },
    ],
    servicesTitle: "农产供应服务",
    servicesSubtitle: "从基地到餐桌的一站式农产供应。",
    services: [
      { name: "生态果蔬", desc: "时令蔬菜与精品水果，新鲜直采。" },
      { name: "订单种植", desc: "按客户需求定向种植，稳定供货。" },
      { name: "粮油作物", desc: "优质稻麦、油料作物规模化供应。" },
      { name: "农技服务", desc: "提供种植指导与田间技术培训。" },
    ],
    stats: [
      { value: "12年", label: "种植经验" },
      { value: "3000亩", label: "种植基地" },
      { value: "200+", label: "合作客户" },
      { value: "12h", label: "采后直发" },
    ],
    testimonialsTitle: "客户的认可",
    testimonials: [
      { name: "林采购", role: "商超采购", text: "基地直供新鲜度高，损耗低、品相好，顾客回头率明显提升。" },
      { name: "邓经理", role: "团餐企业", text: "订单种植让供货特别稳定，价格也有保障，配合很顺畅。" },
      { name: "范老板", role: "社区团购", text: "采后当天就发货，到货还带着田间的新鲜,团友评价很高。" },
    ],
    ctaTitle: "想要稳定的农产货源？",
    ctaSubtitle: "联系我们洽谈订单种植与基地直供合作。",
    ctaButton: "立即洽谈",
    contactPhone: "400-888-4106",
    contactEmail: "hello@farming.com",
    contactAddress: "潍坊市寿光市文家街道沃野生态种植基地",
    footerSlogan: "沃野生态农场 · 用心种好每一寸土地。",
  },

  feed: {
    brand: "牧丰畜禽饲料",
    heroTitle: "科学营养，养出好效益",
    heroSubtitle: "专业畜禽饲料研发生产，助养殖户提质增收。",
    heroCta: "索取配方",
    heroCtaAlt: "技术咨询",
    aboutTitle: "关于牧丰",
    aboutBody: [
      "牧丰畜禽饲料专注于猪、禽、反刍动物全价料与浓缩料的研发与生产，依托营养配方团队与现代化饲料生产线，为规模养殖场与家庭农场提供高效、安全的饲料产品。",
      "我们以动物营养科学为核心，结合各阶段生长需求精准配比，并提供养殖技术服务，帮助客户提升料肉比、降低发病率，让每一份投入都转化为实实在在的效益。",
    ],
    featuresTitle: "牧丰的价值",
    featuresSubtitle: "营养、安全、增效，养殖户的好搭档。",
    features: [
      { title: "科学配方", desc: "按品种与阶段精准配比，营养更均衡。", icon: I.chart },
      { title: "原料严选", desc: "严控霉菌毒素与重金属，源头保安全。", icon: I.shield },
      { title: "高料肉比", desc: "提升转化效率，同样投入长得更快。", icon: I.bolt },
      { title: "无抗健康", desc: "减抗替抗方案，肠道健康少发病。", icon: I.heart },
      { title: "技术驻场", desc: "营养师上门指导饲养与配料管理。", icon: I.users },
      { title: "稳定供货", desc: "自动化产线足量生产，旺季不断货。", icon: I.truck },
    ],
    servicesTitle: "饲料产品线",
    servicesSubtitle: "覆盖主要畜禽品种的全程营养方案。",
    services: [
      { name: "猪用全价料", desc: "乳猪、育肥、母猪分段料，增重稳健。" },
      { name: "禽用饲料", desc: "蛋鸡、肉鸡专用料，产蛋率高料比优。" },
      { name: "反刍料", desc: "牛羊精料补充料，促长奶产双提升。" },
      { name: "养殖技术服务", desc: "提供配料、防疫与饲养管理指导。" },
    ],
    stats: [
      { value: "14年", label: "饲料研发" },
      { value: "20万吨", label: "年产能力" },
      { value: "2000+", label: "养殖客户" },
      { value: "99%", label: "出厂合格率" },
    ],
    testimonialsTitle: "养殖户口碑",
    testimonials: [
      { name: "老张", role: "生猪养殖户", text: "换了牧丰的料后增重明显，料肉比降下来，一栏猪多赚不少。" },
      { name: "王大姐", role: "蛋鸡养殖场", text: "产蛋率稳、蛋壳硬度好，营养师还常来指导,特别贴心。" },
      { name: "马场长", role: "肉牛养殖场", text: "反刍料适口性好，牛长势均匀，供货也从来没断过。" },
    ],
    ctaTitle: "想提升养殖效益？",
    ctaSubtitle: "把养殖品种和规模告诉我们，获取专属营养方案。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-4107",
    contactEmail: "hello@feed.com",
    contactAddress: "驻马店市正阳县产业集聚区牧丰饲料厂",
    footerSlogan: "牧丰畜禽饲料 · 科学营养，助你养殖更增收。",
  },

  garden: {
    brand: "锦园园林花卉",
    heroTitle: "让绿意，点亮每一处空间",
    heroSubtitle: "园林绿化与花卉苗木一体服务，把自然引入生活。",
    heroCta: "预约设计",
    heroCtaAlt: "浏览苗圃",
    aboutTitle: "关于锦园",
    aboutBody: [
      "锦园园林花卉集苗木培育、园林设计与绿化养护于一体，自有苗圃基地培育乔木、灌木、地被及时令花卉，承接市政绿化、地产景观与庭院造园等各类项目。",
      "我们以设计为先、以养护为本，从方案规划到苗木供应再到长期养护一站到位，让每一片绿地都四季有景、长久常青。",
    ],
    featuresTitle: "锦园的专长",
    featuresSubtitle: "从一株苗到一片景的全程服务。",
    features: [
      { title: "自有苗圃", desc: "基地直供，规格齐全、成活率高。", icon: I.leaf },
      { title: "原创设计", desc: "因地制宜规划景观，四季有景可赏。", icon: I.sparkle },
      { title: "工程施工", desc: "专业队伍精细施工，落地还原设计。", icon: I.cog },
      { title: "长期养护", desc: "修剪、施肥、病虫害防治一站托管。", icon: I.heart },
      { title: "时令花卉", desc: "节庆摆花与花境布置，鲜活应景。", icon: I.star },
      { title: "成活保障", desc: "栽植养护双保障，绿化效果有承诺。", icon: I.shield },
    ],
    servicesTitle: "园林绿化服务",
    servicesSubtitle: "覆盖设计、施工与养护的全链条。",
    services: [
      { name: "园林景观设计", desc: "庭院、地产、市政景观整体规划。" },
      { name: "苗木花卉供应", desc: "乔灌木、地被、时令花卉基地直供。" },
      { name: "绿化工程施工", desc: "土建、栽植、铺装一体化施工。" },
      { name: "绿化养护托管", desc: "长期专业养护，保绿地常青。" },
    ],
    stats: [
      { value: "17年", label: "园林经验" },
      { value: "500亩", label: "苗圃基地" },
      { value: "800+", label: "落地项目" },
      { value: "95%", label: "苗木成活率" },
    ],
    testimonialsTitle: "业主与单位评价",
    testimonials: [
      { name: "顾经理", role: "地产开发商", text: "景观设计很出彩，苗木规格到位，交付效果比效果图还惊艳。" },
      { name: "胡主任", role: "市政单位", text: "施工规范、养护到位，几个绿化标段都验收顺利。" },
      { name: "潘女士", role: "庭院业主", text: "从设计到栽植再到养护一条龙，院子四季都有花看，太省心了。" },
    ],
    ctaTitle: "想为空间添一抹绿意？",
    ctaSubtitle: "预约设计师上门勘察，获取专属绿化方案与报价。",
    ctaButton: "免费预约",
    contactPhone: "400-888-4108",
    contactEmail: "hello@garden.com",
    contactAddress: "成都市温江区花木大道锦园苗圃基地 18 号",
    footerSlogan: "锦园园林花卉 · 用绿意装点你的每一天。",
  },
};
