import type { ContentMap } from "./_types";
import { I } from "./_types";

export const LIFE_CONTENT: ContentMap = {
  wedding: {
    heroTitle: "一生一次，值得最好",
    heroSubtitle: "全案婚礼策划，为你定制独一无二的梦幻婚礼。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一支深耕婚礼行业十余年的全案策划团队，由资深策划师、花艺师、灯光舞美与司仪摄影团队组成，已为上千对新人筑造了属于他们的高光时刻。",
      "从主题构思到现场落地，我们坚持「一对新人，一套方案」的定制理念，把你们的故事与心愿，化作宾客难忘、自己更动容的那一天。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大核心优势，让你的婚礼省心更动人。",
    features: [
      { title: "全案定制", desc: "主题、流程、布置一站式定制，不套模板。", icon: I.heart },
      { title: "金牌团队", desc: "资深策划+四大金刚，配合默契零失误。", icon: I.users },
      { title: "原创设计", desc: "专属手绘效果图，所见即所得。", icon: I.sparkle },
      { title: "现场督导", desc: "全程跟场把控，让你只管做幸福新人。", icon: I.shield },
      { title: "透明报价", desc: "明码标价无隐形消费，预算清清楚楚。", icon: I.chart },
      { title: "贴心售后", desc: "婚礼花絮、物料留存，回忆长久珍藏。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖婚礼全流程，让每个环节都恰到好处。",
    services: [
      { name: "婚礼策划", desc: "主题、流程、动线全案定制，独一无二。" },
      { name: "现场布置", desc: "鲜花、灯光、舞美一体化浪漫呈现。" },
      { name: "司仪摄影", desc: "金牌司仪与摄影摄像团队全程记录。" },
      { name: "婚车车队", desc: "豪华婚车迎亲，仪式感拉满每一程。" },
    ],
    stats: [
      { value: "12年", label: "婚礼经验" },
      { value: "3000+", label: "成功案例" },
      { value: "99%", label: "新人好评" },
      { value: "50+", label: "金牌团队" },
    ],
    testimonialsTitle: "新人怎么说",
    testimonials: [
      { name: "陈先生 & 林女士", role: "新人", text: "从沟通到执行都特别用心，现场比效果图还美，亲友都说是参加过最浪漫的婚礼。" },
      { name: "周女士", role: "新娘", text: "策划师把我随口说的小心愿都记在心上，那天我真的哭着笑着完成了仪式。" },
      { name: "黄先生", role: "新郎", text: "全程督导省心到位，我们只负责享受幸福，太值了！" },
    ],
    ctaTitle: "预约你的专属婚礼方案",
    ctaSubtitle: "现在预约即享免费档期咨询与初版主题构思。",
    ctaButton: "免费预约",
    contactPhone: "400-888-3001",
    contactEmail: "hello@wedding.com",
    contactAddress: "成都市锦江区红星路三段 99 号婚礼艺术中心",
    footerSlogan: "以匠心成就一生一次的幸福时刻。",
  },

  bridal: {
    heroTitle: "穿上婚纱，遇见最美的自己",
    heroSubtitle: "高级定制与租赁婚纱礼服，为你的人生大片量身打造。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注婚纱礼服多年的高级定制工作室，汇聚海内外当季设计款与原创手工礼服，从主纱、敬酒服到伴娘裙一应俱全。",
      "专业版型师为每位新娘量体修身，让礼服贴合身形、衬托气质，把「这件就是为我而做」的惊艳还给每一位准新娘。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让试纱成为一段美好回忆。",
    features: [
      { title: "海量款式", desc: "主纱、礼服、秀禾上千款，总有一件心动。", icon: I.sparkle },
      { title: "原创设计", desc: "设计师原创手工款，撞衫几率几乎为零。", icon: I.star },
      { title: "专业修身", desc: "资深版型师量体改版，贴合每寸身形。", icon: I.award },
      { title: "一对一顾问", desc: "婚纱顾问陪同挑选，懂你也懂场合。", icon: I.users },
      { title: "干洗消毒", desc: "每件礼服一客一洗，干净安心试穿。", icon: I.shield },
      { title: "灵活租定", desc: "可租可定可购，方案随预算自由组合。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "从挑选到上身，全程专业陪伴。",
    services: [
      { name: "婚纱定制", desc: "量体设计手工缝制，打造专属梦中嫁衣。" },
      { name: "礼服租赁", desc: "当季新款随心租，性价比与美感兼得。" },
      { name: "秀禾旗袍", desc: "中式婚服与改良旗袍，演绎东方韵味。" },
      { name: "妆造跟拍", desc: "搭配妆发造型与跟拍，整体一站搞定。" },
    ],
    stats: [
      { value: "1000+", label: "在店款式" },
      { value: "10年", label: "定制经验" },
      { value: "98%", label: "顾客满意" },
      { value: "8位", label: "专属顾问" },
    ],
    testimonialsTitle: "新娘怎么说",
    testimonials: [
      { name: "苏小姐", role: "准新娘", text: "顾问太懂我了，第三件就找到了梦中情纱，改版后上身简直绝美。" },
      { name: "何女士", role: "新娘", text: "秀禾的绣工特别精致，长辈们都赞不绝口，仪式感满分。" },
      { name: "罗小姐", role: "伴娘", text: "陪闺蜜来选婚纱，连伴娘裙都安排得明明白白，服务超贴心。" },
    ],
    ctaTitle: "预约到店试穿",
    ctaSubtitle: "提前预约专属顾问，避开高峰从容挑选。",
    ctaButton: "预约试纱",
    contactPhone: "400-888-3002",
    contactEmail: "hello@bridal.com",
    contactAddress: "杭州市西湖区文三路 188 号婚纱礼服馆",
    footerSlogan: "让每一位新娘，都遇见最美的自己。",
  },

  photography: {
    heroTitle: "定格时光，留住每一份心动",
    heroSubtitle: "婚纱写真 · 全家福 · 个人艺术照，用镜头讲述你的故事。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家以原创风格见长的专业摄影机构，拥有多间主题实景棚与外景基地，由资深摄影师与化妆造型团队联手出品。",
      "比起千篇一律的摆拍，我们更在意捕捉你最自然的神情与情绪，让每一张照片都有温度、有故事、有当下的你。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让拍照成为一次愉快体验。",
    features: [
      { title: "原创风格", desc: "多种主题风格随心选，拒绝流水线套路。", icon: I.sparkle },
      { title: "资深摄影", desc: "金牌摄影师掌镜，构图用光自成一格。", icon: I.star },
      { title: "实景影棚", desc: "多间精致实景棚与外景，场景任你拍。", icon: I.globe },
      { title: "精修出片", desc: "专业修图师细修，张张可当封面。", icon: I.award },
      { title: "底片全送", desc: "拍摄底片全部赠送，回忆完整带回家。", icon: I.heart },
      { title: "妆造跟妆", desc: "造型师全程跟妆补妆，状态始终在线。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖人生各个重要瞬间。",
    services: [
      { name: "婚纱摄影", desc: "室内外多场景拍摄，记录浪漫爱情。" },
      { name: "个人写真", desc: "艺术、清新、复古风格，定格独特的你。" },
      { name: "全家福", desc: "温馨合影留念，把团圆永久封存。" },
      { name: "孕婚亲子", desc: "孕照、宝宝照、亲子照，陪伴每个阶段。" },
    ],
    stats: [
      { value: "15年", label: "影像经验" },
      { value: "20000+", label: "拍摄客片" },
      { value: "12间", label: "主题影棚" },
      { value: "100%", label: "底片赠送" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "吴女士", role: "婚纱客片", text: "摄影师特别会引导，全程很放松，成片自然又高级，朋友圈都在问哪家拍的。" },
      { name: "郑先生", role: "全家福", text: "一家老小拍得其乐融融，照片挂在客厅每天看都温暖。" },
      { name: "刘小姐", role: "个人写真", text: "原本很怕镜头，结果拍出了我自己都没见过的好看，太惊喜了。" },
    ],
    ctaTitle: "预约你的专属拍摄",
    ctaSubtitle: "档期有限，提前预约锁定理想拍摄日。",
    ctaButton: "立即预约",
    contactPhone: "400-888-3003",
    contactEmail: "hello@photography.com",
    contactAddress: "广州市天河区天河路 230 号影像创意园",
    footerSlogan: "用镜头，留住值得珍藏的每一刻。",
  },

  cleaning: {
    heroTitle: "干净到家，省心到位",
    heroSubtitle: "家庭保洁 · 深度清洁 · 开荒擦窗，让家焕然一新。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注家庭清洁服务的连锁机构，配备专业保洁设备与环保清洁剂，所有阿姨均经岗前培训、持证上岗、背景核验。",
      "无论是日常保洁、节前大扫除还是新房开荒，我们都以标准化流程与可量化的验收标准，把「看得见的干净」交到你手中。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大保障，让保洁干净又放心。",
    features: [
      { title: "持证上岗", desc: "阿姨实名核验、岗前培训，安心进家门。", icon: I.shield },
      { title: "标准流程", desc: "分区分项作业，每处都有验收标准。", icon: I.cog },
      { title: "环保用剂", desc: "可降解清洁剂，对老人小孩更友好。", icon: I.leaf },
      { title: "专业设备", desc: "高温蒸汽、强力吸尘，深层去污。", icon: I.bolt },
      { title: "准时上门", desc: "预约即到，迟到必赔不耽误事。", icon: I.clock },
      { title: "不满返工", desc: "验收不满意免费返工，干净才结单。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖各类清洁场景。",
    services: [
      { name: "日常保洁", desc: "按时上门打扫，保持家居整洁清爽。" },
      { name: "深度清洁", desc: "厨卫除油除垢，死角顽渍一网打尽。" },
      { name: "新房开荒", desc: "装修后开荒清运，入住前焕然一新。" },
      { name: "玻璃外墙", desc: "高空擦窗与外立面清洗，明亮通透。" },
    ],
    stats: [
      { value: "8年", label: "保洁经验" },
      { value: "50万+", label: "服务订单" },
      { value: "98%", label: "好评返单" },
      { value: "2h", label: "极速上门" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "王女士", role: "家庭用户", text: "阿姨手脚麻利又仔细，厨房油烟机擦得跟新的一样，下次还约她。" },
      { name: "李先生", role: "新房业主", text: "开荒做得特别到位，玻璃窗框墙角都干干净净，搬家心情都好了。" },
      { name: "赵女士", role: "上班族", text: "周期保洁太省心了，每周回家都是整洁的状态，幸福感拉满。" },
    ],
    ctaTitle: "一键预约上门保洁",
    ctaSubtitle: "新客首单立减，干净生活从现在开始。",
    ctaButton: "立即下单",
    contactPhone: "400-888-3004",
    contactEmail: "hello@cleaning.com",
    contactAddress: "深圳市南山区科技园南路 18 号服务中心",
    footerSlogan: "用专业与细致，守护每个家的洁净。",
  },

  "car-care": {
    heroTitle: "懂车更懂你，养护更安心",
    heroSubtitle: "保养维修 · 美容养护 · 钣金喷漆，做你身边的爱车管家。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家集保养、维修、美容于一体的综合汽车养护中心，配备原厂级检测设备与正品配件供应链，技师均持有专业资质认证。",
      "我们坚持「先检测、后报价、明白消费」的服务原则，用透明的流程与实在的工时价，让每位车主都养得明白、修得放心。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让养车省心又省钱。",
    features: [
      { title: "正品配件", desc: "原厂与品牌正品，杜绝以次充好。", icon: I.shield },
      { title: "透明报价", desc: "先检测后报价，工时配件清清楚楚。", icon: I.chart },
      { title: "资深技师", desc: "认证技师团队，疑难杂症一查到底。", icon: I.cog },
      { title: "快修不等", desc: "常规保养立等可取，不耽误用车。", icon: I.clock },
      { title: "智能检测", desc: "电脑检测全车数据，隐患早发现。", icon: I.bolt },
      { title: "质保承诺", desc: "维修项目质保，售后无后顾之忧。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖爱车全生命周期养护。",
    services: [
      { name: "定期保养", desc: "机油机滤更换、全车检查，省心养护。" },
      { name: "故障维修", desc: "发动机、底盘、电路精准诊断维修。" },
      { name: "汽车美容", desc: "镀晶贴膜、内饰清洗，持久亮丽如新。" },
      { name: "钣金喷漆", desc: "刮蹭凹陷修复，原厂漆色精准还原。" },
    ],
    stats: [
      { value: "15年", label: "从业经验" },
      { value: "10万+", label: "服务车主" },
      { value: "100%", label: "正品配件" },
      { value: "30天", label: "维修质保" },
    ],
    testimonialsTitle: "车主怎么说",
    testimonials: [
      { name: "孙先生", role: "私家车主", text: "报价透明从不乱加项，技师还帮我把潜在隐患提前排了，靠谱。" },
      { name: "马女士", role: "网约车司机", text: "快修效率高，保养立等可取，对我们靠车吃饭的人太重要了。" },
      { name: "周先生", role: "老客户", text: "钣金喷漆补得看不出痕迹，颜色完全一致，手艺没得说。" },
    ],
    ctaTitle: "预约爱车养护",
    ctaSubtitle: "在线预约到店，享免费检测一次。",
    ctaButton: "预约到店",
    contactPhone: "400-888-3005",
    contactEmail: "hello@car-care.com",
    contactAddress: "重庆市渝北区金开大道 66 号汽车养护中心",
    footerSlogan: "专业养护每一公里，安心陪伴每一程。",
  },

  "photo-print": {
    heroTitle: "把美好瞬间，握在手心",
    heroSubtitle: "证件照 · 照片冲印 · 个性相册，快速出片即拍即取。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的快照冲印门店，配备高精度冲印设备与专业修图工位，从证件照、生活照到个性相册礼品，均可现场快速出品。",
      "无论你是赶时间办证，还是想把手机里的回忆做成相册留念，我们都能用专业的色彩管理与细致的修图，让每张照片都呈现最佳质感。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让冲印又快又好。",
    features: [
      { title: "即拍即取", desc: "证件照现场拍摄，几分钟立等可取。", icon: I.clock },
      { title: "专业修图", desc: "肤色发丝精细处理，自然不假面。", icon: I.sparkle },
      { title: "色彩还原", desc: "专业色彩管理，冲印通透不偏色。", icon: I.star },
      { title: "规格齐全", desc: "各类证件尺寸与相纸规格全覆盖。", icon: I.cog },
      { title: "个性定制", desc: "相册、台历、抱枕等周边随心做。", icon: I.heart },
      { title: "云端上传", desc: "手机直传下单，到店或邮寄都方便。", icon: I.globe },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "满足各类冲印与定制需求。",
    services: [
      { name: "证件照拍摄", desc: "各类证件尺寸即拍即取，合格可用。" },
      { name: "照片冲印", desc: "高清相纸冲印，色彩通透长久保存。" },
      { name: "个性相册", desc: "婚礼、旅行、宝宝主题相册定制。" },
      { name: "照片周边", desc: "台历、抱枕、钥匙扣等创意礼品。" },
    ],
    stats: [
      { value: "10年", label: "冲印经验" },
      { value: "5分钟", label: "证件出片" },
      { value: "30+", label: "相纸规格" },
      { value: "99%", label: "一次过审" },
    ],
    testimonialsTitle: "顾客怎么说",
    testimonials: [
      { name: "林女士", role: "上班族", text: "急着办护照，进店几分钟就拿到照片，修得自然又精神，效率太高。" },
      { name: "陈先生", role: "新手爸爸", text: "把宝宝的成长照做成了相册，纸质和装帧都很有质感，全家都喜欢。" },
      { name: "杨小姐", role: "学生", text: "考研报名照一次就过审，价格也公道，强烈推荐。" },
    ],
    ctaTitle: "上传照片立即下单",
    ctaSubtitle: "线上传图、到店速取，美好回忆不久等。",
    ctaButton: "立即下单",
    contactPhone: "400-888-3006",
    contactEmail: "hello@photo-print.com",
    contactAddress: "武汉市江汉区中山大道 360 号快照中心",
    footerSlogan: "用心冲印每一张，珍藏每一份美好。",
  },

  moving: {
    heroTitle: "搬家无忧，一站到位",
    heroSubtitle: "居民搬家 · 长途搬运 · 家具拆装，专业团队稳稳搬。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家正规注册的专业搬家公司，自有标准化车队与训练有素的搬运团队，业务覆盖居民搬家、企业搬迁与长途运输。",
      "从上门勘查、打包保护到拆装复位，我们以明码标价、轻拿轻放、按时送达为承诺，让你告别搬家的兵荒马乱。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大保障，让搬家省心又安全。",
    features: [
      { title: "明码标价", desc: "上门勘查报价，无中途加价套路。", icon: I.chart },
      { title: "专业打包", desc: "易碎品分类包装，全程加固保护。", icon: I.shield },
      { title: "拆装复位", desc: "家具家电拆装到位，复原如初。", icon: I.cog },
      { title: "自有车队", desc: "标准货车多车型，按需匹配不延误。", icon: I.truck },
      { title: "准时上门", desc: "预约准时到达，搬运高效不拖沓。", icon: I.clock },
      { title: "损坏包赔", desc: "物品损坏照价赔付，让你安心交托。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖各类搬运需求。",
    services: [
      { name: "居民搬家", desc: "整屋打包搬运，轻松搬入新居。" },
      { name: "企业搬迁", desc: "办公整体迁移，停业时间最小化。" },
      { name: "长途运输", desc: "跨城运输全程跟踪，安全准时。" },
      { name: "家具拆装", desc: "大件家具专业拆装，复位如新。" },
    ],
    stats: [
      { value: "12年", label: "搬家经验" },
      { value: "30万+", label: "搬家订单" },
      { value: "60+", label: "标准车辆" },
      { value: "98%", label: "准时送达" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "高先生", role: "居民搬家", text: "师傅们干活又快又稳，易碎品包得严严实实，全程没磕碰，值得推荐。" },
      { name: "公司行政部", role: "企业搬迁", text: "周末完成整层办公搬迁，周一照常上班，效率和规划都很专业。" },
      { name: "钱女士", role: "跨城搬家", text: "长途运输全程能查位置，准时送到家，比预想顺利太多。" },
    ],
    ctaTitle: "预约上门勘查报价",
    ctaSubtitle: "在线预约即享免费上门估价。",
    ctaButton: "免费报价",
    contactPhone: "400-888-3007",
    contactEmail: "hello@moving.com",
    contactAddress: "北京市朝阳区广渠路 88 号物流园区",
    footerSlogan: "稳稳搬运每一件，妥妥搬进新生活。",
  },

  pets: {
    heroTitle: "用爱，陪伴每一个毛孩子",
    heroSubtitle: "宠物医疗 · 美容 · 寄养，给它无微不至的呵护。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家集医疗、美容、寄养、用品于一体的综合宠物服务中心，拥有专业兽医团队与温馨明亮的诊疗与寄养环境。",
      "我们把每一只到店的毛孩子都当作家人，用专业与耐心呵护它的健康与情绪，让铲屎官们工作出行都能安心放心。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让毛孩子住得舒心。",
    features: [
      { title: "专业兽医", desc: "执业兽医坐诊，常见病疑难病都能看。", icon: I.shield },
      { title: "温柔美容", desc: "耐心安抚不暴力，造型干净又可爱。", icon: I.heart },
      { title: "独立寄养", desc: "分区独立间，定时遛喂全程可视。", icon: I.users },
      { title: "卫生消毒", desc: "环境每日消杀，杜绝交叉感染。", icon: I.leaf },
      { title: "精选用品", desc: "粮食用品严选正品，吃得用得放心。", icon: I.cart },
      { title: "急诊响应", desc: "突发情况快速处置，守护它的安全。", icon: I.clock },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖毛孩子的全方位需求。",
    services: [
      { name: "宠物医疗", desc: "疫苗驱虫、诊疗手术，健康全程守护。" },
      { name: "宠物美容", desc: "洗澡造型、修毛护甲，焕新颜值。" },
      { name: "宠物寄养", desc: "独立舒适空间，定时遛喂安心出行。" },
      { name: "宠物用品", desc: "主粮零食、玩具用品，正品精选。" },
    ],
    stats: [
      { value: "10年", label: "宠护经验" },
      { value: "5万+", label: "服务毛孩" },
      { value: "12位", label: "执业兽医" },
      { value: "24h", label: "急诊响应" },
    ],
    testimonialsTitle: "铲屎官怎么说",
    testimonials: [
      { name: "徐小姐", role: "猫咪主人", text: "主子在这绝育恢复得特别好，医生术后还主动回访，太负责了。" },
      { name: "韩先生", role: "狗狗主人", text: "出差一周把狗子寄养在这，每天都发照片视频，回来胖了一圈很开心。" },
      { name: "曹女士", role: "回头客", text: "美容师手特别巧，剪完毛干干净净又乖巧，每月都来。" },
    ],
    ctaTitle: "预约到店服务",
    ctaSubtitle: "在线预约医疗、美容或寄养，省去排队等待。",
    ctaButton: "立即预约",
    contactPhone: "400-888-3008",
    contactEmail: "hello@pets.com",
    contactAddress: "南京市鼓楼区中央路 200 号宠物生活馆",
    footerSlogan: "把毛孩子当家人，用爱守护每一天。",
  },

  flowers: {
    heroTitle: "用一束花，传递每一份心意",
    heroSubtitle: "鲜花速递 · 花艺定制 · 绿植订阅，让美好如期而至。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注鲜花花艺的精品花店，每日云南基地直采当季鲜花，由资深花艺师手作设计，门店与同城速递双线服务。",
      "从一束日常小确幸，到求婚、开业、节庆的重要场景，我们用新鲜的花材与用心的搭配，把恰到好处的心意准时送到。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "六大优势，让送花更安心更动人。",
    features: [
      { title: "基地直采", desc: "云南源头每日直采，新鲜看得见。", icon: I.leaf },
      { title: "花艺原创", desc: "资深花艺师手作，搭配自成风格。", icon: I.sparkle },
      { title: "同城速递", desc: "市区两小时达，重要时刻不迟到。", icon: I.clock },
      { title: "保鲜养护", desc: "全程冷链锁鲜，瓶插期更持久。", icon: I.shield },
      { title: "贴心代写", desc: "祝福卡片代笔，心意表达更走心。", icon: I.heart },
      { title: "节庆定制", desc: "婚庆、开业、会场花艺整体承接。", icon: I.award },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖各类送花与花艺需求。",
    services: [
      { name: "鲜花速递", desc: "同城当日达，把心意准时送到。" },
      { name: "花艺定制", desc: "求婚、纪念日主题花束专属设计。" },
      { name: "活动花艺", desc: "婚礼开业、会场布置整体花艺方案。" },
      { name: "绿植订阅", desc: "办公居家绿植定期配送养护。" },
    ],
    stats: [
      { value: "8年", label: "花艺经验" },
      { value: "100万+", label: "鲜花送达" },
      { value: "2h", label: "同城速达" },
      { value: "99%", label: "新鲜好评" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "唐先生", role: "下单顾客", text: "纪念日订的花束惊艳到老婆，花材新鲜搭配高级，准时送达没掉链子。" },
      { name: "冯女士", role: "企业客户", text: "公司开业的花艺布置大气又上镜，宾客拍照打卡停不下来。" },
      { name: "董小姐", role: "订阅用户", text: "每周一束花放在办公桌，整个人的心情都被治愈了，太值。" },
    ],
    ctaTitle: "在线选购心仪花束",
    ctaSubtitle: "下单备注送达时间，让美好如期绽放。",
    ctaButton: "立即订花",
    contactPhone: "400-888-3009",
    contactEmail: "hello@flowers.com",
    contactAddress: "昆明市盘龙区北京路 520 号鲜花生活馆",
    footerSlogan: "以花为礼，把美好与心意准时送达。",
  },
};
