import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「物流/租赁/商业贸易」+「通用行业」全部子类的精修中文文案。
export const LOGISTICS_GENERAL_CONTENT: ContentMap = {
  freight: {
    heroTitle: "货通天下,使命必达",
    heroSubtitle: "覆盖全国的物流网络,整车零担、仓配一体,让每一票货物准时安全抵达。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的货运物流企业,拥有覆盖全国的运输专线与自有车队,提供整车、零担、仓储配送与供应链一体化服务,为企业客户搭建高效稳定的货运通道。",
      "我们依托数字化调度与全程可视化系统,实现订单跟踪、智能配载与时效管控,以诚信经营和稳定时效,成为众多制造、商贸客户长期信赖的物流伙伴。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "网络广、时效稳,六大优势让货运更省心。",
    features: [
      { title: "全国网络", desc: "覆盖全国的专线网络,直达更高效。", icon: I.globe },
      { title: "时效保障", desc: "智能配载与时效管控,准时送达。", icon: I.clock },
      { title: "全程可视", desc: "在途轨迹实时跟踪,货在哪一目了然。", icon: I.chart },
      { title: "安全承运", desc: "规范装载与货物保险,运输更安心。", icon: I.shield },
      { title: "自有车队", desc: "多类型自有车辆,运力充足可调度。", icon: I.truck },
      { title: "仓配一体", desc: "仓储与配送一体化,降本又增效。", icon: I.cog },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖运输、仓储与供应链的一站式物流。",
    services: [
      { name: "整车零担", desc: "全国专线运输,整车零担时效保障。" },
      { name: "仓储配送", desc: "现代仓储管理与城市配送一体化。" },
      { name: "冷链物流", desc: "全程温控冷链,生鲜医药品质无忧。" },
      { name: "供应链方案", desc: "端到端供应链定制,降本增效。" },
    ],
    stats: [
      { value: "18年", label: "物流经验" },
      { value: "300+", label: "运输专线" },
      { value: "99%", label: "准时送达" },
      { value: "24h", label: "全程跟踪" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "陈经理", role: "制造企业", text: "专线时效稳定、轨迹透明,发货再也不用担心货到哪了,很省心。" },
      { name: "刘总", role: "商贸客户", text: "仓配一体方案帮我们降了不少成本,响应也快,合作很愉快。" },
      { name: "周女士", role: "电商卖家", text: "旺季运力也跟得上,破损率低,客户收货体验明显好了。" },
    ],
    ctaTitle: "让物流更省心高效",
    ctaSubtitle: "现在联系我们,获取专属物流方案与报价。",
    ctaButton: "获取报价",
    contactPhone: "400-888-5301",
    contactEmail: "hello@freight.com",
    contactAddress: "广东省广州市白云区物流大道 168 号",
    footerSlogan: "货运物流专家 · 货通天下,使命必达。",
  },

  express: {
    heroTitle: "快人一步,准时送达",
    heroSubtitle: "高效快递配送网络,揽收快、派送准、可追踪,让每一个包裹都安心到家。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注于快递配送的服务企业,布局密集的揽收派送网点与智能分拣中心,为个人与电商客户提供快速、稳定、可追踪的同城与全国快递服务。",
      "我们以科技驱动效率,通过智能分拣、自动化路由与全程信息化追踪,持续缩短时效、降低破损,用专业与速度守护每一个包裹的旅程。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "快、准、稳,六大优势让寄件更安心。",
    features: [
      { title: "极速揽派", desc: "上门快揽、当日发出,寄件不等待。", icon: I.bolt },
      { title: "全程追踪", desc: "实时物流轨迹,包裹动态随时可查。", icon: I.chart },
      { title: "智能分拣", desc: "自动分拣路由,提速又降低差错。", icon: I.cog },
      { title: "安全无损", desc: "规范操作与丢损包赔,寄得放心。", icon: I.shield },
      { title: "广泛覆盖", desc: "网点遍布城乡,偏远地区也能达。", icon: I.globe },
      { title: "贴心客服", desc: "专属客服跟进,异常问题快解决。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖个人寄件与电商发货的快递服务。",
    services: [
      { name: "标准快递", desc: "全国快递寄递,时效稳定可追踪。" },
      { name: "同城急送", desc: "同城当日达,文件物品快速送达。" },
      { name: "电商仓发", desc: "电商订单批量发货与对接服务。" },
      { name: "上门揽收", desc: "预约上门取件,寄件足不出户。" },
    ],
    stats: [
      { value: "12年", label: "快递服务" },
      { value: "5000+", label: "服务网点" },
      { value: "98%", label: "准时妥投" },
      { value: "24h", label: "在线客服" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "小王", role: "电商卖家", text: "揽收快、价格优,旺季也不爆仓,客户收货评价都很好。" },
      { name: "李女士", role: "个人用户", text: "上门取件很方便,物流轨迹清楚,寄重要文件也很放心。" },
      { name: "张老板", role: "网店店主", text: "对接系统批量发货省事多了,异常件客服跟进也及时。" },
    ],
    ctaTitle: "把包裹交给我们",
    ctaSubtitle: "现在下单,体验快人一步的寄递服务。",
    ctaButton: "立即寄件",
    contactPhone: "400-888-5302",
    contactEmail: "hello@express.com",
    contactAddress: "浙江省杭州市余杭区电商物流园 2 号",
    footerSlogan: "快递配送专家 · 快人一步,准时送达。",
  },

  "house-rent": {
    heroTitle: "找个好房子,安心住下来",
    heroSubtitle: "海量真实房源,看房省心、签约规范,让租房从此简单、透明、有保障。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的房屋租赁服务机构,提供整租、合租、公寓等多类型真实房源,所有房源经实勘核验,杜绝虚假信息,让租客看得明白、住得安心。",
      "从找房看房、规范签约到入住管家与售后维修,我们提供一站式租住服务,坚持透明计费、押金保障,致力于打造省心、可信赖的城市租住体验。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "真实又省心,六大保障让租房无忧。",
    features: [
      { title: "真实房源", desc: "实勘核验真房源,拒绝虚假与照骗。", icon: I.shield },
      { title: "透明计费", desc: "房租杂费清清楚楚,无隐形收费。", icon: I.chart },
      { title: "规范签约", desc: "标准合同与押金保障,权益有保护。", icon: I.award },
      { title: "贴心管家", desc: "专属管家服务,入住生活更省心。", icon: I.users },
      { title: "快速维修", desc: "报修快速响应,居住问题及时解决。", icon: I.bolt },
      { title: "房源丰富", desc: "整租合租公寓多选,总有合适的家。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖找房、签约与入住的全流程租住服务。",
    services: [
      { name: "整租房源", desc: "精选整租房源,拎包入住更自在。" },
      { name: "合租优选", desc: "品质合租房,室友筛选更安心。" },
      { name: "品质公寓", desc: "集中式公寓,配套齐全管理规范。" },
      { name: "管家维修", desc: "入住管家与报修服务,居住无忧。" },
    ],
    stats: [
      { value: "10年", label: "租赁服务" },
      { value: "5万+", label: "真实房源" },
      { value: "20万+", label: "服务租客" },
      { value: "98%", label: "满意入住" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "小林", role: "上班族", text: "房源都是真实的,看房不跑空,签约也很规范,租得很放心。" },
      { name: "陈先生", role: "合租租客", text: "管家服务很贴心,报修第二天就修好了,住得很舒心。" },
      { name: "王女士", role: "公寓住户", text: "公寓配套齐全、管理到位,押金退得也痛快,体验很好。" },
    ],
    ctaTitle: "找到属于你的家",
    ctaSubtitle: "现在咨询,海量真实房源等你来挑。",
    ctaButton: "在线找房",
    contactPhone: "400-888-5303",
    contactEmail: "hello@house-rent.com",
    contactAddress: "上海市徐汇区漕河泾租赁服务中心 3 层",
    footerSlogan: "房屋租赁服务 · 找个好房子,安心住下来。",
  },

  "car-rent": {
    heroTitle: "随租随走,出行更自由",
    heroSubtitle: "丰富车型、灵活租期,手续简单、车况安心,让每一次出行都说走就走。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的汽车租赁公司,提供经济、商务、SUV、新能源等多类车型,支持短租、长租与企业用车,满足商务出行、旅游自驾与日常代步等多样需求。",
      "我们坚持车况严检、明码计费与全程保险,门店与送取车服务覆盖广泛,以省心的手续和可靠的车况,为个人与企业客户带来自由便捷的出行体验。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "省心又自由,六大优势让用车无忧。",
    features: [
      { title: "车型丰富", desc: "经济到商务多车型,总有合适的座驾。", icon: I.star },
      { title: "车况严检", desc: "每车归还必检,交车干净安全可靠。", icon: I.shield },
      { title: "灵活租期", desc: "时租日租到长租,租期自由灵活。", icon: I.clock },
      { title: "明码计费", desc: "费用透明无套路,押金退还快捷。", icon: I.chart },
      { title: "全程保险", desc: "保险全覆盖,用车安心无后顾之忧。", icon: I.award },
      { title: "送取上门", desc: "门店广布并支持送取车,取还方便。", icon: I.truck },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖个人与企业的灵活租车服务。",
    services: [
      { name: "短租自驾", desc: "日租周租自驾出行,说走就走。" },
      { name: "商务用车", desc: "商务车型带司机服务,接待体面。" },
      { name: "企业长租", desc: "企业车队长租方案,省心省成本。" },
      { name: "新能源租赁", desc: "新能源车型租赁,经济又环保。" },
    ],
    stats: [
      { value: "12年", label: "租车经验" },
      { value: "3000+", label: "在租车辆" },
      { value: "50+", label: "服务门店" },
      { value: "100%", label: "全程保险" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "赵先生", role: "自驾游客", text: "车况很新、手续简单,送车上门很方便,自驾旅行体验超棒。" },
      { name: "Lucy", role: "企业用户", text: "公司长租了一批车,费用透明、维保到位,用车成本降了不少。" },
      { name: "孙女士", role: "商务出行", text: "商务车干净舒适,司机专业准时,接待客户很有面子。" },
    ],
    ctaTitle: "开启自由出行",
    ctaSubtitle: "现在预订,享受省心可靠的租车服务。",
    ctaButton: "立即租车",
    contactPhone: "400-888-5304",
    contactEmail: "hello@car-rent.com",
    contactAddress: "成都市武侯区天府大道汽车租赁中心 1 层",
    footerSlogan: "汽车租赁服务 · 随租随走,出行更自由。",
  },

  "export-trade": {
    heroTitle: "连接世界,贸易无界",
    heroSubtitle: "专业外贸进出口服务,报关报检、国际物流、跨境结算一站搞定,助力中国制造走向全球。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专业的进出口贸易服务企业,提供进出口代理、报关报检、国际物流与跨境结算等一站式外贸服务,帮助制造商与品牌商高效拓展海外市场。",
      "我们熟悉各国贸易政策与通关流程,拥有成熟的海外渠道与合规风控体系,以专业、稳健、合规的服务,成为客户出海路上值得托付的贸易伙伴。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "专业又合规,六大优势护航出海之路。",
    features: [
      { title: "通关高效", desc: "报关报检熟门熟路,清关快不压货。", icon: I.bolt },
      { title: "全球物流", desc: "海运空运直达,全球时效有保障。", icon: I.globe },
      { title: "合规风控", desc: "贸易合规与单证规范,降低风险。", icon: I.shield },
      { title: "跨境结算", desc: "安全便捷的跨境收付与外汇结算。", icon: I.chart },
      { title: "海外渠道", desc: "成熟海外渠道资源,拓客更高效。", icon: I.users },
      { title: "一站服务", desc: "从订单到收汇全流程一站托管。", icon: I.cog },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖通关、物流与结算的外贸一体化服务。",
    services: [
      { name: "进出口代理", desc: "报关报检与单证处理,一站搞定。" },
      { name: "国际物流", desc: "海运空运拼柜整柜,全球直达。" },
      { name: "跨境结算", desc: "安全合规的跨境收付与外汇服务。" },
      { name: "海外营销获客", desc: "多平台海外推广与渠道拓展。" },
    ],
    stats: [
      { value: "16年", label: "外贸经验" },
      { value: "80+", label: "贸易国家" },
      { value: "5000+", label: "出口订单" },
      { value: "100%", label: "合规通关" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "黄总", role: "制造企业", text: "代理通关效率高、单证规范,出口流程顺畅,出海省了很多心。" },
      { name: "Michael", role: "品牌商", text: "海外渠道与物流方案都很专业,帮我们顺利打开了新市场。" },
      { name: "李经理", role: "外贸新手企业", text: "从报关到收汇全程托管,合规又安心,第一次出口就很顺利。" },
    ],
    ctaTitle: "让生意通向全球",
    ctaSubtitle: "现在咨询,获取一站式外贸进出口方案。",
    ctaButton: "立即咨询",
    contactPhone: "400-888-5305",
    contactEmail: "hello@export-trade.com",
    contactAddress: "广东省深圳市福田区国际贸易中心 28 层",
    footerSlogan: "外贸进出口专家 · 连接世界,贸易无界。",
  },

  enterprise: {
    heroTitle: "专业成就卓越",
    heroSubtitle: "深耕行业多年,以专业实力与诚信经营,赢得每一位客户的长期信赖。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家专注主营业务、稳健经营的现代企业,凭借专业的团队、可靠的品质与持续的创新能力,在行业中树立了良好的口碑与品牌形象。",
      "我们始终坚持以客户为中心、以诚信为根本,不断优化产品与服务,与合作伙伴携手共进,致力于为客户和社会创造更大的价值。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "专业可信赖,六大优势铸就企业实力。",
    features: [
      { title: "专业团队", desc: "资深团队经验丰富,专业可靠。", icon: I.users },
      { title: "品质保障", desc: "严格品控体系,品质值得信赖。", icon: I.shield },
      { title: "诚信经营", desc: "以诚为本透明合规,合作更安心。", icon: I.award },
      { title: "高效服务", desc: "快速响应需求,服务高效贴心。", icon: I.bolt },
      { title: "持续创新", desc: "紧跟趋势不断创新,引领行业。", icon: I.chart },
      { title: "客户为先", desc: "全程一对一跟进,以客户为中心。", icon: I.heart },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "围绕客户需求提供专业可靠的解决方案。",
    services: [
      { name: "核心业务", desc: "专注主营业务,精益求精做到极致。" },
      { name: "方案定制", desc: "按需定制专属方案,贴合实际需求。" },
      { name: "贴心服务", desc: "全流程跟进服务,客户省心放心。" },
      { name: "持续创新", desc: "不断创新升级,引领行业发展。" },
    ],
    stats: [
      { value: "20年", label: "行业深耕" },
      { value: "5000+", label: "服务客户" },
      { value: "98%", label: "客户满意" },
      { value: "24h", label: "贴心响应" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "张先生", role: "企业客户", text: "团队很专业,从沟通到交付都让人放心,合作多年一直很满意。" },
      { name: "李女士", role: "长期合作伙伴", text: "服务态度好、响应快,结果常常超出预期,会一直合作下去。" },
      { name: "王总", role: "回头客", text: "品质过硬、诚信经营,团队靠谱,值得长期信赖,强烈推荐。" },
    ],
    ctaTitle: "开启高效合作",
    ctaSubtitle: "现在联系我们,获取专属方案与报价。",
    ctaButton: "免费咨询",
    contactPhone: "400-888-5306",
    contactEmail: "hello@enterprise.com",
    contactAddress: "北京市朝阳区建国路企业大厦 18 层",
    footerSlogan: "专业企业 · 以专业与诚信,服务每一位客户。",
  },

  mall: {
    heroTitle: "好物臻选,惠购无忧",
    heroSubtitle: "全品类精选好物,正品保障、闪电发货、无忧退换,让网购更省心更划算。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们是一家全品类综合购物商城,精选海内外优质好物,涵盖家居、数码、美妆、食品等多个品类,坚持正品直供与平价好货,让消费者买得放心、用得舒心。",
      "我们以高效的仓储物流与完善的售后体系为支撑,提供闪电发货、无忧退换与贴心客服服务,致力于打造一个值得信赖的一站式购物平台。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "省心又划算,六大保障让购物无忧。",
    features: [
      { title: "正品保障", desc: "品牌直供正品行货,假一赔十。", icon: I.shield },
      { title: "闪电发货", desc: "多仓就近发货,下单当日即发。", icon: I.bolt },
      { title: "无忧退换", desc: "七天无理由退换,售后省心。", icon: I.heart },
      { title: "全球好物", desc: "海内外精选好货,一站购齐。", icon: I.globe },
      { title: "会员权益", desc: "积分折扣专属福利,越买越省。", icon: I.star },
      { title: "贴心客服", desc: "在线客服快速响应,购物无忧。", icon: I.users },
    ],
    servicesTitle: "我们的服务",
    servicesSubtitle: "覆盖选购、配送与售后的一站式购物服务。",
    services: [
      { name: "全球好物", desc: "海内外精选商品,正品直供。" },
      { name: "极速发货", desc: "当日下单次日送达,购物不等待。" },
      { name: "无忧退换", desc: "七天无理由退换,售后无忧。" },
      { name: "会员专享", desc: "积分、折扣与专属福利权益。" },
    ],
    stats: [
      { value: "10万+", label: "在售商品" },
      { value: "1000万+", label: "注册用户" },
      { value: "99%", label: "好评率" },
      { value: "24h", label: "极速发货" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "小美", role: "资深买家", text: "品类全、价格实在,发货特别快,退换也方便,购物体验很好。" },
      { name: "陈先生", role: "会员用户", text: "正品有保障,会员价更划算,客服响应也快,值得信赖。" },
      { name: "王女士", role: "新用户", text: "第一次下单就很顺利,次日就到货,质量不错,会回购。" },
    ],
    ctaTitle: "开启惠购之旅",
    ctaSubtitle: "现在逛逛,海量好物等你挑选。",
    ctaButton: "立即逛逛",
    contactPhone: "400-888-5307",
    contactEmail: "hello@mall.com",
    contactAddress: "广东省广州市天河区电商总部园 A 座",
    footerSlogan: "精选商城 · 好物臻选,惠购无忧。",
  },

  personal: {
    heroTitle: "你好,这是我的世界",
    heroSubtitle: "记录我的作品、经历与思考,在这里遇见一个真实、有趣、不断成长的我。",
    aboutTitle: "关于我",
    aboutBody: [
      "我是一名热爱创作与生活的多面探索者,这里汇集了我的作品集、项目经历与日常随笔,希望通过它让你认识一个立体而真实的我。",
      "从专业技能到兴趣爱好,我相信持续学习与真诚表达的力量。无论你是想了解我的作品,还是寻找合作机会,都欢迎在这里与我连接。",
    ],
    featuresTitle: "关于我的几件事",
    featuresSubtitle: "用六个关键词,认识真实的我。",
    features: [
      { title: "专业能力", desc: "在专业领域持续深耕,作品经得起检验。", icon: I.award },
      { title: "创意表达", desc: "热爱创作,用作品表达想法与审美。", icon: I.sparkle },
      { title: "持续成长", desc: "保持学习与好奇,不断突破自己。", icon: I.chart },
      { title: "真诚靠谱", desc: "做事认真负责,合作让人安心。", icon: I.heart },
      { title: "热爱生活", desc: "在生活中寻找灵感,记录美好点滴。", icon: I.leaf },
      { title: "开放连接", desc: "乐于交流与协作,期待遇见同频的你。", icon: I.users },
    ],
    servicesTitle: "我能提供什么",
    servicesSubtitle: "如果我们有机会合作,这些是我擅长的。",
    services: [
      { name: "作品展示", desc: "精选个人作品与项目案例集中呈现。" },
      { name: "经历分享", desc: "学习、工作与成长经历的真实记录。" },
      { name: "随笔思考", desc: "对生活与专业的观察、思考与表达。" },
      { name: "合作洽谈", desc: "开放合作与交流,欢迎随时联系我。" },
    ],
    stats: [
      { value: "8年", label: "专业积累" },
      { value: "50+", label: "作品案例" },
      { value: "20+", label: "合作伙伴" },
      { value: "100%", label: "用心投入" },
    ],
    testimonialsTitle: "他们这样评价我",
    testimonials: [
      { name: "老友阿楠", role: "多年好友", text: "认真又靠谱,交给他的事总能放心,而且做出来还常常有惊喜。" },
      { name: "合作方林姐", role: "项目伙伴", text: "沟通顺畅、专业到位,作品质量很高,合作体验非常好。" },
      { name: "读者小溪", role: "博客读者", text: "文字真诚有温度,作品也很有想法,默默关注了好久。" },
    ],
    ctaTitle: "一起聊聊吧",
    ctaSubtitle: "无论是合作还是交流,都欢迎随时联系我。",
    ctaButton: "联系我",
    contactPhone: "400-888-5308",
    contactEmail: "hello@personal.com",
    contactAddress: "杭州市西湖区文创园创意工坊 7 号",
    footerSlogan: "个人主页 · 记录成长,遇见真实的我。",
  },

  landing: {
    heroTitle: "限时活动,精彩即将开启",
    heroSubtitle: "聚焦一个核心目标,一页讲清亮点与福利,引导你立即行动、不容错过。",
    aboutTitle: "活动介绍",
    aboutBody: [
      "这是一场精心策划的限时活动,我们将最核心的亮点、福利与玩法浓缩在这一页,让你在最短时间内了解全部精彩,轻松完成报名或下单。",
      "无论是新品发布、促销特惠还是报名招募,本页都为「立即行动」而生——清晰的卖点、有力的引导与简洁的流程,只为让你不错过这次机会。",
    ],
    featuresTitle: "为什么不容错过",
    featuresSubtitle: "六个理由,让你现在就行动。",
    features: [
      { title: "限时专享", desc: "活动限时限量,错过就要再等一年。", icon: I.clock },
      { title: "超值福利", desc: "专属优惠与好礼,参与即享实惠。", icon: I.star },
      { title: "亮点突出", desc: "核心卖点一目了然,快速看懂价值。", icon: I.sparkle },
      { title: "一键参与", desc: "流程极简,报名下单一步搞定。", icon: I.bolt },
      { title: "真实保障", desc: "活动规则透明,权益兑现有保障。", icon: I.shield },
      { title: "口碑见证", desc: "众多用户已参与,好评有目共睹。", icon: I.users },
    ],
    servicesTitle: "活动亮点",
    servicesSubtitle: "这场活动,为你准备了这些。",
    services: [
      { name: "限时优惠", desc: "活动期间专享价格,优惠力度空前。" },
      { name: "好礼相送", desc: "参与即有礼,下单更有惊喜赠品。" },
      { name: "名额有限", desc: "限量名额先到先得,手慢则无。" },
      { name: "便捷报名", desc: "在线一键报名下单,流程超简单。" },
    ],
    stats: [
      { value: "限时", label: "活动专享" },
      { value: "5折起", label: "超值优惠" },
      { value: "10000+", label: "已参与" },
      { value: "100%", label: "好礼保障" },
    ],
    testimonialsTitle: "参与者怎么说",
    testimonials: [
      { name: "小琪", role: "活动用户", text: "优惠力度很大,报名也方便,这波福利真的太香了,果断参与。" },
      { name: "阿强", role: "下单用户", text: "页面把活动讲得很清楚,看完直接就下单了,赠品也很实在。" },
      { name: "Cindy", role: "回头客", text: "上次活动就薅到羊毛了,这次又来,这福利谁顶得住啊。" },
    ],
    ctaTitle: "机会有限,立即参与",
    ctaSubtitle: "活动名额有限,现在就行动,别让机会溜走。",
    ctaButton: "立即参与",
    contactPhone: "400-888-5309",
    contactEmail: "hello@landing.com",
    contactAddress: "上海市黄浦区南京东路活动运营中心 5 层",
    footerSlogan: "活动单页 · 限时精彩,立即行动。",
  },

  others: {
    heroTitle: "更多可能,从这里开始",
    heroSubtitle: "灵活通用的内容框架,适配各类场景与行业,帮你快速搭建专属在线门面。",
    aboutTitle: "关于我们",
    aboutBody: [
      "我们提供灵活通用的网站内容方案,无论你身处哪个行业、有着怎样独特的需求,都能在这里找到一个简洁、专业、易于定制的起点。",
      "我们相信每一份事业都值得被认真呈现。以清晰的结构与得体的表达,帮助你快速搭建属于自己的在线门面,让更多人了解你、信任你、选择你。",
    ],
    featuresTitle: "为什么选择我们",
    featuresSubtitle: "通用而不将就,六大优势灵活适配。",
    features: [
      { title: "灵活适配", desc: "适配多行业多场景,内容随需而变。", icon: I.cog },
      { title: "简洁专业", desc: "结构清晰、表达得体,呈现更专业。", icon: I.award },
      { title: "快速上线", desc: "模板化搭建,分钟级即可上线发布。", icon: I.bolt },
      { title: "易于定制", desc: "文案配色自由替换,打造专属风格。", icon: I.sparkle },
      { title: "稳定可靠", desc: "成熟框架支撑,访问稳定有保障。", icon: I.shield },
      { title: "贴心支持", desc: "搭建与使用全程答疑,省心无忧。", icon: I.users },
    ],
    servicesTitle: "我们能做什么",
    servicesSubtitle: "为各类需求提供通用而可靠的内容方案。",
    services: [
      { name: "通用展示", desc: "适配多行业的企业与个人展示页面。" },
      { name: "内容定制", desc: "文案、栏目按需调整,贴合实际。" },
      { name: "快速建站", desc: "模板化搭建,快速拥有在线门面。" },
      { name: "持续优化", desc: "根据需求持续迭代,常用常新。" },
    ],
    stats: [
      { value: "100+", label: "适配场景" },
      { value: "5分钟", label: "快速上线" },
      { value: "1万+", label: "成功案例" },
      { value: "98%", label: "用户满意" },
    ],
    testimonialsTitle: "客户怎么说",
    testimonials: [
      { name: "周先生", role: "创业者", text: "需求比较特别,这套通用方案改改就很合适,上线也快,很省事。" },
      { name: "李女士", role: "工作室主理人", text: "结构清晰、定制方便,不懂技术也能搭出像样的站,很实用。" },
      { name: "王经理", role: "小微企业主", text: "灵活又稳定,花很少的成本就有了专业门面,性价比很高。" },
    ],
    ctaTitle: "搭建你的专属门面",
    ctaSubtitle: "现在开始,几步即可拥有专业在线展示。",
    ctaButton: "立即开始",
    contactPhone: "400-888-5310",
    contactEmail: "hello@others.com",
    contactAddress: "深圳市南山区科技园通用服务中心 9 层",
    footerSlogan: "通用方案 · 更多可能,从这里开始。",
  },
};
