import type { ContentMap } from "./_types";
import { I } from "./_types";

export const MEDIA_CONTENT: ContentMap = {
  "culture-media": {
    heroTitle: "讲好每一个品牌故事",
    heroSubtitle: "文化传媒 · 内容策划 · 全案传播，让你的声音被世界听见。",
    aboutBody: [
      "我们是一支由策划、设计、影像与公关专家组成的文化传媒团队，深耕品牌内容十余年，服务过快消、科技、文旅等多个行业的头部客户。",
      "从一条短视频到一场城市级营销战役，我们用专业的内容生产能力与媒介资源，帮品牌穿越信息噪音、直达人心，把每一次曝光都转化为真实的认同与增长。",
    ],
    features: [
      { title: "专业团队", desc: "策划、文案、设计、影像一体化班底，懂内容更懂传播。", icon: I.users },
      { title: "创意驱动", desc: "以洞察打底，用创意破圈，让每个作品都自带话题。", icon: I.sparkle },
      { title: "全案执行", desc: "从策略到落地一站式交付，省去你的多方对接成本。", icon: I.bolt },
      { title: "数据复盘", desc: "全链路数据监测，用效果说话，持续优化投放。", icon: I.chart },
      { title: "资源整合", desc: "覆盖主流平台与媒体矩阵，资源精准触达目标人群。", icon: I.globe },
      { title: "长期陪伴", desc: "不止做一次刷屏，更陪品牌走过每个增长阶段。", icon: I.heart },
    ],
    services: [
      { name: "品牌内容策划", desc: "洞察、定位、内容矩阵，一站式内容战略规划。" },
      { name: "影视广告制作", desc: "TVC、短视频、纪录片，全流程拍摄与后期制作。" },
      { name: "新媒体代运营", desc: "全平台账号运营，涨粉与转化双驱动。" },
      { name: "整合营销传播", desc: "线上线下联动，制造现象级传播事件。" },
    ],
    stats: [
      { value: "12年", label: "行业深耕" },
      { value: "2000+", label: "服务客户" },
      { value: "98%", label: "客户满意" },
      { value: "24h", label: "贴心响应" },
    ],
    testimonials: [
      { name: "张先生", role: "品牌负责人", text: "他们把我们一个新品牌做成了行业话题，内容质感和执行力都让人惊喜。" },
      { name: "李女士", role: "市场总监", text: "从策略到落地全程省心，数据复盘很扎实，预算花得明明白白。" },
      { name: "王总", role: "创始人", text: "一条短视频帮我们带来了百万级曝光，团队很懂年轻人的表达。" },
    ],
    ctaTitle: "让你的品牌被看见",
    ctaSubtitle: "现在就联系我们，获取专属内容营销方案。",
    contactPhone: "400-888-1001",
    contactEmail: "hello@culture-media.com",
    contactAddress: "上海市徐汇区漕溪北路 88 号",
    footerSlogan: "用内容连接人心，用创意成就品牌。",
  },

  "ad-design": {
    heroTitle: "好创意，让生意被看见",
    heroSubtitle: "广告设计 · 视觉创意 · 品牌升级，用设计驱动增长。",
    aboutBody: [
      "我们是一家专注商业视觉的广告设计公司，团队由资深美术指导与品牌设计师组成，擅长把抽象的品牌理念转化为打动人心的视觉表达。",
      "无论是一张海报、一套 VI，还是一场户外大刊投放，我们都坚持创意与商业的平衡——既要好看，更要能卖货、能让品牌被记住。",
    ],
    features: [
      { title: "原创设计", desc: "拒绝套模板，每个方案都为品牌量身原创。", icon: I.sparkle },
      { title: "美术指导", desc: "资深 AD 把控调性，视觉统一不跑偏。", icon: I.star },
      { title: "快速出稿", desc: "标准化流程提效，急稿也能按时交付。", icon: I.bolt },
      { title: "商业洞察", desc: "懂市场更懂转化，设计服务于生意目标。", icon: I.chart },
      { title: "全媒介适配", desc: "线上线下、大屏小屏，一套视觉全场景落地。", icon: I.globe },
      { title: "无限修改", desc: "项目周期内合理修改不限次，改到满意为止。", icon: I.cog },
    ],
    services: [
      { name: "平面广告设计", desc: "海报、画册、包装，专业视觉表达。" },
      { name: "品牌 VI 设计", desc: "Logo、规范、应用，建立统一识别。" },
      { name: "户外广告投放", desc: "楼宇、地铁、机场，精准触达人群。" },
      { name: "创意 H5 / 互动", desc: "互动营销页面，提升参与与转化。" },
    ],
    stats: [
      { value: "10年", label: "设计经验" },
      { value: "5000+", label: "成功案例" },
      { value: "300+", label: "合作品牌" },
      { value: "99%", label: "好评返单" },
    ],
    testimonials: [
      { name: "陈先生", role: "电商运营", text: "他们设计的主图点击率明显上涨，转化数据骗不了人。" },
      { name: "赵女士", role: "品牌经理", text: "新 VI 一上线整个品牌气质都变高级了，团队审美在线。" },
      { name: "孙总", role: "门店老板", text: "户外大牌做得特别抢眼，路过的人都忍不住多看两眼。" },
    ],
    ctaTitle: "用设计放大你的生意",
    ctaSubtitle: "留下需求，资深设计师 24 小时内为你出具创意方案。",
    contactPhone: "400-888-1002",
    contactEmail: "hello@ad-design.com",
    contactAddress: "广州市天河区珠江新城华夏路 18 号",
    footerSlogan: "以设计之名，让每一个品牌都被看见。",
  },

  "pr-consulting": {
    heroTitle: "关键时刻，做对的发声",
    heroSubtitle: "公关顾问 · 声誉管理 · 危机应对，为品牌守好每一道关。",
    aboutBody: [
      "我们是一家专业的公关顾问机构，团队成员多来自资深媒体与头部公关公司，深谙舆论生态与传播规律，擅长在复杂局面中为客户找到最稳妥的发声方式。",
      "从日常品牌声誉建设到突发危机的快速处置，我们用专业判断和媒体资源，帮客户把风险降到最低、把价值放到最大，做企业最值得信赖的外脑。",
    ],
    features: [
      { title: "舆情监测", desc: "7×24 全网监测，第一时间捕捉风险信号。", icon: I.shield },
      { title: "危机应对", desc: "成熟预案与快速响应，关键时刻稳住大局。", icon: I.bolt },
      { title: "媒体关系", desc: "深耕主流媒体资源，沟通顺畅、发声有力。", icon: I.globe },
      { title: "声誉管理", desc: "长期品牌形象经营，化被动为主动。", icon: I.star },
      { title: "专业团队", desc: "媒体人与公关专家组队，经验与判断并重。", icon: I.users },
      { title: "效果评估", desc: "传播效果量化复盘，让每分预算有迹可循。", icon: I.chart },
    ],
    services: [
      { name: "企业公关顾问", desc: "常年公关咨询，护航品牌声誉建设。" },
      { name: "危机公关处理", desc: "突发事件预案、响应与舆论引导。" },
      { name: "媒体关系维护", desc: "媒体沟通、专访安排与稿件发布。" },
      { name: "品牌发布会", desc: "新品/活动发布会策划与全程执行。" },
    ],
    stats: [
      { value: "15年", label: "公关经验" },
      { value: "500+", label: "服务企业" },
      { value: "1000+", label: "媒体资源" },
      { value: "1h", label: "危机响应" },
    ],
    testimonials: [
      { name: "林总", role: "上市公司董秘", text: "一次突发舆情他们一小时就给出预案，处置专业、稳住了局面。" },
      { name: "周女士", role: "公关总监", text: "媒体资源扎实，发声节奏把控得很准，是值得长期合作的外脑。" },
      { name: "吴先生", role: "企业创始人", text: "发布会从策划到落地滴水不漏，现场传播效果远超预期。" },
    ],
    ctaTitle: "为品牌请一位专业外脑",
    ctaSubtitle: "无论日常声誉还是突发危机，我们都准备好与你同行。",
    contactPhone: "400-888-1003",
    contactEmail: "hello@pr-consulting.com",
    contactAddress: "北京市朝阳区建国路 89 号华贸中心",
    footerSlogan: "专业发声，守护每一份品牌信任。",
  },

  "brand-planning": {
    heroTitle: "让品牌，从此与众不同",
    heroSubtitle: "品牌策划 · 战略定位 · 形象升级，为企业打造长期增长引擎。",
    aboutBody: [
      "我们是一家专注品牌战略的策划机构，从品牌的顶层设计出发，帮企业理清「我是谁、为谁服务、凭什么被选择」这三个根本问题。",
      "我们相信品牌不是一句口号，而是一套可被持续经营的资产。从定位、命名到视觉与话语体系，我们为客户构建清晰、独特、能穿越周期的品牌系统。",
    ],
    features: [
      { title: "战略定位", desc: "找准差异化坐标，让品牌一句话说清自己。", icon: I.star },
      { title: "市场调研", desc: "用户与竞品深度洞察，决策有据可依。", icon: I.chart },
      { title: "品牌命名", desc: "好记、好传、好注册，名字就是第一资产。", icon: I.sparkle },
      { title: "形象体系", desc: "视觉与话语一体化设计，对内对外都统一。", icon: I.cog },
      { title: "增长陪跑", desc: "从策划到落地长期陪伴，品牌持续生长。", icon: I.heart },
      { title: "全案交付", desc: "策略、设计、内容打通，一个团队搞定。", icon: I.bolt },
    ],
    services: [
      { name: "品牌战略定位", desc: "市场洞察与差异化定位，明确品牌方向。" },
      { name: "品牌命名与口号", desc: "原创命名、Slogan 与品牌话语体系。" },
      { name: "品牌形象设计", desc: "Logo、VI 与品牌视觉资产全套打造。" },
      { name: "品牌升级焕新", desc: "老品牌诊断、重塑与全面焕新升级。" },
    ],
    stats: [
      { value: "14年", label: "策划经验" },
      { value: "600+", label: "操盘品牌" },
      { value: "40+", label: "行业覆盖" },
      { value: "95%", label: "续约客户" },
    ],
    testimonials: [
      { name: "黄总", role: "连锁品牌创始人", text: "一次定位调整就帮我们打开了新市场，方向对了一切都顺了。" },
      { name: "郑女士", role: "品牌负责人", text: "他们做的品牌系统逻辑特别清晰，全公司用起来都不跑偏。" },
      { name: "何先生", role: "投资人", text: "被投企业经他们重塑后估值明显提升，专业度毋庸置疑。" },
    ],
    ctaTitle: "为品牌找到长期增长的支点",
    ctaSubtitle: "预约一次品牌诊断，看看你的品牌还有多大潜力。",
    contactPhone: "400-888-1004",
    contactEmail: "hello@brand-planning.com",
    contactAddress: "深圳市南山区科技园南区高新南一道 9 号",
    footerSlogan: "以战略之眼，铸长青之牌。",
  },

  "gift-custom": {
    heroTitle: "心意，值得被定制",
    heroSubtitle: "礼品定制 · 企业伴手礼 · 文创周边，让每份礼物都有专属温度。",
    aboutBody: [
      "我们是一家专注礼品定制的创意供应商，拥有自有设计团队与稳定的供应链工厂，从创意打样到批量生产全程可控，让企业送礼既有面子又有里子。",
      "无论是商务伴手礼、员工福利还是节日营销周边，我们都坚持原创设计与品质把控，把品牌的心意妥帖地装进每一份礼物里。",
    ],
    features: [
      { title: "原创设计", desc: "专属设计团队，礼品自带品牌印记。", icon: I.sparkle },
      { title: "自有工厂", desc: "源头生产成本透明，品质交期可控。", icon: I.cog },
      { title: "海量品类", desc: "数码、文创、家居全覆盖，总有合适的。", icon: I.cart },
      { title: "快速打样", desc: "三天出样、确认即产，效率有保障。", icon: I.bolt },
      { title: "品质把控", desc: "出货前全检，杜绝瑕疵流到客户手上。", icon: I.shield },
      { title: "全国配送", desc: "支持多地址分发，福利直达每位员工。", icon: I.truck },
    ],
    services: [
      { name: "企业商务礼品", desc: "高端商务伴手礼定制，彰显品牌品位。" },
      { name: "员工福利礼盒", desc: "节日福利与入职礼盒一站式定制。" },
      { name: "文创周边定制", desc: "原创 IP 周边、活动赠品创意设计。" },
      { name: "礼品包装设计", desc: "礼盒结构与视觉设计，提升开箱体验。" },
    ],
    stats: [
      { value: "11年", label: "定制经验" },
      { value: "8000+", label: "定制案例" },
      { value: "3天", label: "极速打样" },
      { value: "100%", label: "出货全检" },
    ],
    testimonials: [
      { name: "刘女士", role: "行政经理", text: "中秋礼盒同事们都说好看好用，公司形象都跟着加分了。" },
      { name: "杨先生", role: "市场负责人", text: "活动周边设计很出彩，打样快、交期准，合作很省心。" },
      { name: "马总", role: "企业采购", text: "源头工厂价格实在，品控也到位，已经连续三年合作。" },
    ],
    ctaTitle: "把心意，定制成礼物",
    ctaSubtitle: "告诉我们你的预算与场景，专属礼品方案马上奉上。",
    contactPhone: "400-888-1005",
    contactEmail: "hello@gift-custom.com",
    contactAddress: "杭州市余杭区文一西路 1218 号",
    footerSlogan: "用心定制每一份礼物，传递每一份心意。",
  },

  exhibition: {
    heroTitle: "一场展，让品牌闪耀全场",
    heroSubtitle: "展会服务 · 展台搭建 · 活动执行，从设计到落地一站搞定。",
    aboutBody: [
      "我们是一家专业的展会综合服务商，拥有资深的展台设计师与自有搭建工程团队，业务覆盖国内外各类大型展会、行业峰会与品牌发布活动。",
      "从展位创意设计、工厂化制作到现场搭建与活动统筹，我们用一体化的服务和严格的现场管控，让客户在每一场展会上都能从容亮相、脱颖而出。",
    ],
    features: [
      { title: "创意设计", desc: "结合品牌调性的展台设计，吸睛又留人。", icon: I.sparkle },
      { title: "自有工厂", desc: "标准化生产，成本可控、品质稳定。", icon: I.cog },
      { title: "全国搭建", desc: "覆盖各大会展中心，异地办展无忧。", icon: I.globe },
      { title: "现场统筹", desc: "专业项目经理驻场，全程协调不掉链子。", icon: I.users },
      { title: "工期保障", desc: "严控搭建节点，保证开展前完美交付。", icon: I.clock },
      { title: "安全规范", desc: "结构与用电严格合规，现场安全有保障。", icon: I.shield },
    ],
    services: [
      { name: "展台设计搭建", desc: "特装展台创意设计与现场施工搭建。" },
      { name: "展会活动策划", desc: "展期活动、发布会与现场互动策划。" },
      { name: "会议会务执行", desc: "行业峰会、年会的全流程会务统筹。" },
      { name: "展具租赁服务", desc: "标准展具、家具与设备一站式租赁。" },
    ],
    stats: [
      { value: "13年", label: "办展经验" },
      { value: "3000+", label: "搭建案例" },
      { value: "50+", label: "覆盖城市" },
      { value: "零", label: "安全事故" },
    ],
    testimonials: [
      { name: "高总", role: "参展企业负责人", text: "展台设计太抢眼了，开展第一天我们的展位就被围得水泄不通。" },
      { name: "罗女士", role: "会展执行", text: "项目经理特别靠谱，搭建到撤展全程操心，我们只管接待客户。" },
      { name: "彭先生", role: "品牌市场", text: "异地办展他们也能完美落地，工期卡得准，现场零失误。" },
    ],
    ctaTitle: "让下一场展会成为焦点",
    ctaSubtitle: "把展位面积和参展目标告诉我们，专属展台方案立等可取。",
    contactPhone: "400-888-1006",
    contactEmail: "hello@exhibition.com",
    contactAddress: "上海市青浦区诸光路 1888 号国家会展中心旁",
    footerSlogan: "用心搭建每一场展，让品牌闪耀每一刻。",
  },

  printing: {
    heroTitle: "好印象，从一张好印刷开始",
    heroSubtitle: "印刷包装 · 画册彩印 · 礼盒定制，品质与交期双双在线。",
    aboutBody: [
      "我们是一家集设计、印刷与包装于一体的综合印务企业，配备全套进口印刷与后道加工设备，从名片到精装画册、从纸盒到礼盒，都能高品质交付。",
      "我们深知印刷是品牌的「第一触点」，因此在色彩管理、材质选择与工艺细节上精益求精，用看得见的品质，帮客户传递看不见的专业与诚意。",
    ],
    features: [
      { title: "进口设备", desc: "全套海德堡印刷设备，色彩还原精准。", icon: I.cog },
      { title: "色彩管理", desc: "专业打样校色，所见即所得不偏色。", icon: I.star },
      { title: "工艺齐全", desc: "烫金、UV、压纹等后道工艺一应俱全。", icon: I.sparkle },
      { title: "环保材料", desc: "可选环保纸张与油墨，绿色印刷更安心。", icon: I.leaf },
      { title: "快速交付", desc: "标准品当天上机，急单也能准时出货。", icon: I.bolt },
      { title: "品质承诺", desc: "出货严格质检，瑕疵免费返工重印。", icon: I.shield },
    ],
    services: [
      { name: "画册书刊印刷", desc: "企业画册、宣传册与书刊精印。" },
      { name: "包装礼盒定制", desc: "纸盒、礼盒结构设计与生产制作。" },
      { name: "商务办公印品", desc: "名片、信封、单据等办公用品印制。" },
      { name: "海报展架制作", desc: "海报、易拉宝、展架等广告物料印制。" },
    ],
    stats: [
      { value: "16年", label: "印刷经验" },
      { value: "10000+", label: "服务客户" },
      { value: "48h", label: "快单交付" },
      { value: "99.5%", label: "出货合格" },
    ],
    testimonials: [
      { name: "曾女士", role: "品牌设计师", text: "色彩还原非常到位，烫金压纹的工艺细节让画册质感拉满。" },
      { name: "徐先生", role: "采购主管", text: "急单他们也能按时交，品质稳定，是我们长期的印刷供应商。" },
      { name: "韩总", role: "电商品牌主", text: "包装礼盒做得很高级，客户开箱体验好了，复购都跟着涨。" },
    ],
    ctaTitle: "把品质，印在每一份印品上",
    ctaSubtitle: "上传你的文件或需求，我们马上为你报价与排期。",
    contactPhone: "400-888-1007",
    contactEmail: "hello@printing.com",
    contactAddress: "东莞市长安镇振安中路 56 号",
    footerSlogan: "以匠心印刷，传递每一份专业与诚意。",
  },
};
