import type { ContentMap } from "./_types";
import { I } from "./_types";

// 行业「教育/政府/组织机构」+「IT/互联网/科技行业」各子类的精修中文文案。
export const ORG_TECH_CONTENT: ContentMap = {
  school: {
    brand: "明德实验学校",
    heroTitle: "启迪智慧，成就未来",
    heroSubtitle: "以德育人 · 以智启航，为每个孩子点亮人生方向。",
    aboutTitle: "关于明德",
    aboutBody: [
      "明德实验学校秉持「立德树人」的办学宗旨，坚持五育并举、全面发展。多年来，我们以严谨的教风与温暖的师爱，陪伴一届届学子健康成长、学有所成。",
      "学校拥有现代化的教学设施与一支师德高尚、业务精湛的教师队伍。我们既重视学业根基，也关注品格养成，努力让每个孩子都能找到属于自己的成长舞台。",
    ],
    featuresTitle: "我们的办学优势",
    featuresSubtitle: "好的教育，是点燃，而非灌输。",
    features: [
      { title: "名师执教", desc: "骨干教师领衔，因材施教用心育人。", icon: I.users },
      { title: "特色课程", desc: "多元课程体系，发掘每个孩子的潜能。", icon: I.star },
      { title: "五育并举", desc: "德智体美劳全面发展，健康成长。", icon: I.heart },
      { title: "智慧校园", desc: "现代化教学设施，赋能高效课堂。", icon: I.bolt },
      { title: "家校共育", desc: "畅通家校沟通，携手护航成长。", icon: I.shield },
      { title: "生涯规划", desc: "专业升学与生涯指导，志存高远。", icon: I.chart },
    ],
    servicesTitle: "教育板块",
    servicesSubtitle: "从课堂到舞台，给孩子完整的成长。",
    services: [
      { name: "特色课程", desc: "多元化课程体系，因材施教。" },
      { name: "名师团队", desc: "资深教师，潜心教学育人。" },
      { name: "校园生活", desc: "丰富社团活动，全面发展。" },
      { name: "升学指导", desc: "专业升学规划与生涯指导。" },
    ],
    stats: [
      { value: "30年", label: "办学历史" },
      { value: "200+", label: "专任教师" },
      { value: "5000+", label: "在校学子" },
      { value: "98%", label: "升学率" },
    ],
    testimonialsTitle: "家长与学子的声音",
    testimonials: [
      { name: "王女士", role: "学生家长", text: "孩子在这里不仅成绩进步，更懂事自信了，很感谢老师。" },
      { name: "李同学", role: "毕业生", text: "母校的社团和老师让我找到了方向，受益终身。" },
      { name: "张先生", role: "家委会成员", text: "学校管理规范，家校沟通顺畅，把孩子交给他们很放心。" },
    ],
    ctaTitle: "为孩子选择一所好学校",
    ctaSubtitle: "欢迎预约校园开放日，实地感受明德氛围。",
    ctaButton: "预约参观",
    contactPhone: "400-888-3001",
    contactEmail: "hello@school.com",
    contactAddress: "北京市海淀区中关村南大街 18 号",
    footerSlogan: "明德实验学校 · 以德启智，静待花开。",
  },

  training: {
    brand: "卓越教育培训",
    heroTitle: "学有所成，未来可期",
    heroSubtitle: "专业培训机构，助你掌握真本领、赢得新机会。",
    aboutTitle: "关于卓越",
    aboutBody: [
      "卓越教育培训专注职业技能与素养提升，以「学得会、用得上」为教学准则。我们用实战导向的课程与负责到底的教学服务，帮助学员真正学有所获、学有所成。",
      "机构拥有经验丰富的师资团队与完善的教研体系，课程紧贴行业需求持续更新。无论你是想提升技能、考取证书还是培养兴趣，这里都有适合你的成长路径。",
    ],
    featuresTitle: "为什么选择卓越",
    featuresSubtitle: "选对培训，少走弯路，事半功倍。",
    features: [
      { title: "实战教学", desc: "案例驱动学完即用，拒绝纸上谈兵。", icon: I.bolt },
      { title: "名师授课", desc: "行业资深讲师，把复杂讲得透彻。", icon: I.users },
      { title: "高通过率", desc: "考点精讲题库押题，提分更高效。", icon: I.chart },
      { title: "小班教学", desc: "小班互动答疑，老师顾得过来每个人。", icon: I.star },
      { title: "灵活上课", desc: "线上线下结合，工作学习两不误。", icon: I.clock },
      { title: "学习保障", desc: "学不会可重修，全程跟踪不掉队。", icon: I.shield },
    ],
    servicesTitle: "课程方向",
    servicesSubtitle: "技能、证书、素养，总有一门适合你。",
    services: [
      { name: "职业技能", desc: "实战导向，学完即可上手就业。" },
      { name: "考证辅导", desc: "高通过率，名师精讲押重点。" },
      { name: "兴趣素养", desc: "艺术、语言、思维全面提升。" },
      { name: "企业内训", desc: "定制化团队能力提升方案。" },
    ],
    stats: [
      { value: "15年", label: "教学积累" },
      { value: "300+", label: "金牌讲师" },
      { value: "10万+", label: "结业学员" },
      { value: "92%", label: "考证通过率" },
    ],
    testimonialsTitle: "学员评价",
    testimonials: [
      { name: "小赵", role: "应届毕业生", text: "课程很实战，结业后顺利拿到 offer，性价比很高。" },
      { name: "陈女士", role: "在职考证", text: "老师押题很准，一次通过考试，复习节奏安排得很好。" },
      { name: "刘先生", role: "企业 HR", text: "给团队定制的内训很落地，员工反馈都说有收获。" },
    ],
    ctaTitle: "开始你的能力进阶之路",
    ctaSubtitle: "预约免费试听课，先体验再决定。",
    ctaButton: "免费试听",
    contactPhone: "400-888-3002",
    contactEmail: "hello@training.com",
    contactAddress: "广州市天河区天河路 230 号教育大厦 9 楼",
    footerSlogan: "卓越教育 · 让每一次学习都有回报。",
  },

  government: {
    brand: "便民政务服务中心",
    heroTitle: "为民服务，办实事解难题",
    heroSubtitle: "规范 · 透明 · 高效，让每一项服务都暖到群众心坎里。",
    aboutTitle: "中心简介",
    aboutBody: [
      "本服务中心坚持以人民为中心的服务理念，全面推行「一网通办、一窗受理、最多跑一次」改革，努力让数据多跑路、群众少跑腿，不断提升群众办事的便利度与满意度。",
      "我们持续优化办事流程、公开办事指南、畅通监督渠道，自觉接受社会监督。以规范的作风、廉洁的形象和高效的服务，做好群众和企业身边的贴心人。",
    ],
    featuresTitle: "服务特色",
    featuresSubtitle: "把方便留给群众，把责任留给自己。",
    features: [
      { title: "一网通办", desc: "线上线下融合，事项掌上即可办理。", icon: I.globe },
      { title: "一窗受理", desc: "综合窗口集成受理，告别来回奔波。", icon: I.users },
      { title: "信息公开", desc: "办事指南政务信息公开透明可查。", icon: I.chart },
      { title: "高效办理", desc: "压缩办理时限，常规事项立等可取。", icon: I.bolt },
      { title: "廉洁规范", desc: "全程留痕规范办理，自觉接受监督。", icon: I.shield },
      { title: "贴心帮办", desc: "提供导办帮办，特殊群体上门服务。", icon: I.heart },
    ],
    servicesTitle: "服务事项",
    servicesSubtitle: "群众办事的常见需求，这里都能办。",
    services: [
      { name: "证照办理", desc: "规范流程，高效办理各类证照。" },
      { name: "信息公开", desc: "公开透明，主动接受社会监督。" },
      { name: "在线办事", desc: "一网通办，便民利企掌上办。" },
      { name: "互动交流", desc: "畅通渠道，倾听并回应民意诉求。" },
    ],
    stats: [
      { value: "500+", label: "可办事项" },
      { value: "90%", label: "网上可办率" },
      { value: "1窗", label: "综合受理" },
      { value: "98%", label: "群众满意度" },
    ],
    testimonialsTitle: "群众反馈",
    testimonials: [
      { name: "周先生", role: "办事群众", text: "网上预约线下取号，没排多久就办好了，效率真高。" },
      { name: "孙女士", role: "个体经营者", text: "开店证照一窗就办齐了，工作人员讲解很耐心。" },
      { name: "吴大爷", role: "退休居民", text: "腿脚不便还能帮办上门，服务真是想到群众心里去了。" },
    ],
    ctaTitle: "办事更省心，从这里开始",
    ctaSubtitle: "登录政务服务平台，足不出户即可在线办理。",
    ctaButton: "在线办事",
    contactPhone: "400-888-3003",
    contactEmail: "hello@government.com",
    contactAddress: "南京市玄武区为民路 1 号政务服务中心",
    footerSlogan: "便民政务服务中心 · 用心服务，为民解忧。",
  },

  association: {
    brand: "行业协会",
    heroTitle: "凝聚行业力量，共谋发展",
    heroSubtitle: "服务会员 · 规范行业 · 桥梁纽带，推动行业健康发展。",
    aboutTitle: "协会简介",
    aboutBody: [
      "本协会是经民政部门登记成立的行业性、非营利性社会组织，由本行业企业、机构与从业者自愿组成。我们致力于服务会员、规范行业、反映诉求，做好政府与企业之间的桥梁纽带。",
      "协会秉持「自律、服务、协调、发展」的宗旨，通过制定行业标准、组织交流培训、维护行业权益等方式，团结引导会员单位诚信经营，共同推动行业持续健康发展。",
    ],
    featuresTitle: "协会职能",
    featuresSubtitle: "为会员办实事，为行业谋长远。",
    features: [
      { title: "桥梁纽带", desc: "上传下达政企互通，反映行业诉求。", icon: I.globe },
      { title: "行业自律", desc: "制定公约标准，引导诚信规范经营。", icon: I.shield },
      { title: "会员服务", desc: "政策解读、资源对接，为会员赋能。", icon: I.users },
      { title: "交流培训", desc: "组织论坛展会与培训，促进交流。", icon: I.star },
      { title: "权益维护", desc: "依法维护行业与会员合法权益。", icon: I.heart },
      { title: "调研建言", desc: "开展行业调研，为决策建言献策。", icon: I.chart },
    ],
    servicesTitle: "会员服务",
    servicesSubtitle: "入会即享多项权益，与同行共成长。",
    services: [
      { name: "政策对接", desc: "及时传达解读，对接政策资源。" },
      { name: "标准制定", desc: "牵头行业标准，规范市场秩序。" },
      { name: "培训交流", desc: "组织论坛、展会与专业培训。" },
      { name: "权益维护", desc: "反映会员诉求，依法维护权益。" },
    ],
    stats: [
      { value: "20年", label: "成立历程" },
      { value: "800+", label: "会员单位" },
      { value: "50+", label: "年度活动" },
      { value: "30+", label: "行业标准" },
    ],
    testimonialsTitle: "会员心声",
    testimonials: [
      { name: "某企业负责人", role: "理事单位", text: "协会的政策解读很及时，组织的对接活动帮我们找到了客户。" },
      { name: "某机构代表", role: "会员单位", text: "行业培训含金量高，结识了不少同行，受益匪浅。" },
      { name: "某从业者", role: "个人会员", text: "遇到权益问题协会出面协调，让我们感受到组织的温暖。" },
    ],
    ctaTitle: "加入我们，共筑行业未来",
    ctaSubtitle: "欢迎本行业企业与从业者申请入会，共享平台资源。",
    ctaButton: "申请入会",
    contactPhone: "400-888-3004",
    contactEmail: "hello@association.com",
    contactAddress: "上海市黄浦区人民大道 200 号社团活动中心",
    footerSlogan: "行业协会 · 凝聚同行，共促发展。",
  },

  chamber: {
    brand: "企业家商会",
    heroTitle: "汇聚商界精英，共创共赢",
    heroSubtitle: "资源对接 · 抱团发展 · 商企之家，让生意做得更大更远。",
    aboutTitle: "商会简介",
    aboutBody: [
      "本商会由一批有责任、有担当的企业家自愿发起组建，是会员之间互助合作、资源共享的平台。我们以「团结、互助、诚信、共赢」为宗旨，致力于打造温暖而有力量的企业家之家。",
      "商会积极搭建政企沟通、产业对接、投融资合作的桥梁，组织丰富的考察、论坛与联谊活动，帮助会员企业开拓市场、链接资源、共担风雨，实现抱团发展、合作共赢。",
    ],
    featuresTitle: "商会价值",
    featuresSubtitle: "一个人走得快，一群人走得远。",
    features: [
      { title: "资源对接", desc: "搭建产业与项目对接平台，互通有无。", icon: I.globe },
      { title: "抱团发展", desc: "整合会员资源，合作共赢谋长远。", icon: I.users },
      { title: "投融资服务", desc: "对接资本与项目，助力企业成长。", icon: I.chart },
      { title: "政企桥梁", desc: "传递政策信息，反映企业心声。", icon: I.shield },
      { title: "高端交流", desc: "论坛、考察、联谊，结识同频伙伴。", icon: I.star },
      { title: "公益担当", desc: "组织会员回馈社会，践行社会责任。", icon: I.heart },
    ],
    servicesTitle: "会员权益",
    servicesSubtitle: "入会即融入一个互助共赢的企业家圈层。",
    services: [
      { name: "商务对接", desc: "撮合会员合作，拓展商业机会。" },
      { name: "投融资服务", desc: "对接资本资源，助力项目落地。" },
      { name: "学习考察", desc: "标杆企业参访与高端论坛交流。" },
      { name: "联谊互助", desc: "定期联谊活动，深化会员情谊。" },
    ],
    stats: [
      { value: "15年", label: "商会历程" },
      { value: "600+", label: "会员企业" },
      { value: "100+", label: "年度活动" },
      { value: "千亿", label: "会员产值" },
    ],
    testimonialsTitle: "会员分享",
    testimonials: [
      { name: "某董事长", role: "常务副会长单位", text: "在商会认识了上下游伙伴，促成了好几笔合作，值了。" },
      { name: "某创始人", role: "会员企业", text: "投融资对接很务实，帮我们对接到了合适的投资方。" },
      { name: "某总经理", role: "会员企业", text: "考察学习长见识，会员之间互相帮衬，氛围特别好。" },
    ],
    ctaTitle: "加入商会，链接更大的世界",
    ctaSubtitle: "诚邀优秀企业家加入，共享平台资源与人脉。",
    ctaButton: "申请加入",
    contactPhone: "400-888-3005",
    contactEmail: "hello@chamber.com",
    contactAddress: "深圳市福田区中心商务区会展中心 28 楼",
    footerSlogan: "企业家商会 · 抱团取暖，共创未来。",
  },

  "web-build": {
    brand: "速建网站建设",
    heroTitle: "建站，从此无需从零开始",
    heroSubtitle: "上千套行业模板，任意选用、自由更换，一键上线你的官网。",
    aboutTitle: "关于速建",
    aboutBody: [
      "速建是一站式网站建设与品牌上线服务商，提供从模板建站、定制开发到域名主机、SEO 优化的全链路服务。无论你是初创团队还是成熟企业，都能在这里快速拥有专属官网。",
      "我们沉淀了上千套覆盖各行各业的精美模板，配合可视化编辑与专业建站团队，让没有技术背景的你也能轻松上线一个好看、好用、能获客的网站。",
    ],
    featuresTitle: "为什么选择速建",
    featuresSubtitle: "好网站，是企业在线上的第一张名片。",
    features: [
      { title: "海量模板", desc: "上千套行业模板，任意切换分钟级上线。", icon: I.globe },
      { title: "可视化编辑", desc: "拖拽即改所见即所得，无需懂代码。", icon: I.sparkle },
      { title: "定制开发", desc: "官网商城小程序，专业团队全包。", icon: I.cog },
      { title: "响应式适配", desc: "电脑手机自动适配，多端体验一致。", icon: I.bolt },
      { title: "SEO 优化", desc: "搜索引擎友好，自然流量持续增长。", icon: I.chart },
      { title: "安全稳定", desc: "云主机加固防护，网站稳定不掉线。", icon: I.shield },
    ],
    servicesTitle: "建站服务",
    servicesSubtitle: "从模板到定制，从上线到运营，一站搞定。",
    services: [
      { name: "模板建站", desc: "海量精美模板，分钟级快速上线。" },
      { name: "定制开发", desc: "品牌官网、商城、小程序全包。" },
      { name: "域名主机", desc: "一站式域名注册与云主机服务。" },
      { name: "SEO 优化", desc: "搜索引擎优化，提升自然流量。" },
    ],
    stats: [
      { value: "12年", label: "建站经验" },
      { value: "1000+", label: "行业模板" },
      { value: "8万+", label: "上线网站" },
      { value: "99.9%", label: "稳定运行" },
    ],
    testimonialsTitle: "客户口碑",
    testimonials: [
      { name: "某店主", role: "初创创业者", text: "套模板半天就上线了，不用懂代码，价格也很实在。" },
      { name: "某市场总监", role: "中型企业", text: "定制官网做得很专业，SEO 上来后询盘明显多了。" },
      { name: "某负责人", role: "连锁品牌", text: "多个站点统一管理很方便，售后响应也快，省心。" },
    ],
    ctaTitle: "今天就拥有你的官方网站",
    ctaSubtitle: "免费体验在线建站，满意再付费上线。",
    ctaButton: "免费建站",
    contactPhone: "400-888-3006",
    contactEmail: "hello@web-build.com",
    contactAddress: "杭州市西湖区文三路数字产业园 5 号楼",
    footerSlogan: "速建网站建设 · 让每家企业都有好官网。",
  },

  internet: {
    brand: "联众互联网",
    heroTitle: "连接价值，定义在线体验",
    heroSubtitle: "产品 · 运营 · 增长，用互联网思维重塑你的业务。",
    aboutTitle: "关于联众",
    aboutBody: [
      "联众是一家以用户价值为核心的互联网公司，业务涵盖平台运营、产品研发与数字化增长服务。我们用敏捷的迭代节奏和数据驱动的方法，帮助业务持续创造在线价值。",
      "团队汇聚了产品、技术、运营与数据分析的复合型人才，深谙流量获取、用户留存与商业变现的全链路打法。我们相信，好的互联网产品，是用心打磨出来的。",
    ],
    featuresTitle: "我们的能力",
    featuresSubtitle: "从 0 到 1，再从 1 到 100。",
    features: [
      { title: "产品驱动", desc: "以用户为中心，打磨极致产品体验。", icon: I.sparkle },
      { title: "数据增长", desc: "数据驱动决策，精细化运营提效。", icon: I.chart },
      { title: "敏捷迭代", desc: "小步快跑快速试错，迭代不停步。", icon: I.bolt },
      { title: "流量获客", desc: "全渠道获客投放，降本提升转化。", icon: I.globe },
      { title: "用户运营", desc: "拉新促活留存，构建用户增长闭环。", icon: I.users },
      { title: "商业变现", desc: "多元变现模式，让流量产生价值。", icon: I.award },
    ],
    servicesTitle: "业务板块",
    servicesSubtitle: "陪企业走完互联网化的每一步。",
    services: [
      { name: "平台运营", desc: "内容与社区运营，激活用户活跃。" },
      { name: "产品研发", desc: "App 与小程序研发，体验为先。" },
      { name: "增长营销", desc: "全域投放与转化，驱动业务增长。" },
      { name: "数据分析", desc: "用户行为洞察，赋能精细化决策。" },
    ],
    stats: [
      { value: "10年", label: "深耕互联网" },
      { value: "5000万+", label: "累计用户" },
      { value: "300+", label: "服务客户" },
      { value: "7×24", label: "运维保障" },
    ],
    testimonialsTitle: "合作伙伴评价",
    testimonials: [
      { name: "某创始人", role: "消费品牌", text: "他们的增长打法很扎实，三个月帮我们把转化率翻了倍。" },
      { name: "某运营负责人", role: "在线平台", text: "用户运营做得很细，留存数据明显改善，专业靠谱。" },
      { name: "某 CTO", role: "科技公司", text: "产品迭代节奏快、质量高，是值得长期合作的团队。" },
    ],
    ctaTitle: "用互联网的方式，把业务做大",
    ctaSubtitle: "预约免费增长诊断，给你一份可落地的方案。",
    ctaButton: "免费诊断",
    contactPhone: "400-888-3007",
    contactEmail: "hello@internet.com",
    contactAddress: "北京市朝阳区望京 SOHO T1 座 18 层",
    footerSlogan: "联众互联网 · 连接价值，驱动增长。",
  },

  "tech-company": {
    brand: "智核科技",
    heroTitle: "用科技定义未来",
    heroSubtitle: "前沿技术 · 极致产品，为千行百业注入数字动力。",
    aboutTitle: "关于智核",
    aboutBody: [
      "智核科技是一家专注前沿技术研发与产业落地的高新技术企业，业务覆盖软件研发、云计算、人工智能与数据中台。我们以技术为内核，致力于成为企业数字化转型的可靠引擎。",
      "公司汇聚了一支高水平的研发团队，持续投入自主创新并拥有多项核心技术与软件著作权。我们相信，真正有价值的科技，是能切实解决行业问题、创造长期价值的科技。",
    ],
    featuresTitle: "技术实力",
    featuresSubtitle: "把复杂的技术，变成简单好用的能力。",
    features: [
      { title: "自主研发", desc: "核心技术自研可控，掌握关键能力。", icon: I.cog },
      { title: "AI 赋能", desc: "大模型与算法落地，赋能业务场景。", icon: I.sparkle },
      { title: "云原生架构", desc: "弹性云架构，安全稳定可弹性扩展。", icon: I.globe },
      { title: "数据驱动", desc: "数据中台释放数据价值，辅助决策。", icon: I.chart },
      { title: "极速交付", desc: "敏捷研发快速交付，按时高质上线。", icon: I.bolt },
      { title: "安全可信", desc: "全链路安全防护，数据加密合规。", icon: I.shield },
    ],
    servicesTitle: "产品与服务",
    servicesSubtitle: "从底层架构到上层应用，一体化交付。",
    services: [
      { name: "软件研发", desc: "定制化软件与系统开发，贴合业务。" },
      { name: "云计算", desc: "弹性云架构，安全可靠可扩展。" },
      { name: "人工智能", desc: "AI 大模型赋能千行百业场景。" },
      { name: "数据中台", desc: "数据驱动决策，释放数据价值。" },
    ],
    stats: [
      { value: "11年", label: "技术深耕" },
      { value: "60+", label: "核心专利" },
      { value: "400+", label: "企业客户" },
      { value: "99.99%", label: "系统可用性" },
    ],
    testimonialsTitle: "客户评价",
    testimonials: [
      { name: "某信息总监", role: "制造企业", text: "他们的中台方案帮我们打通了数据孤岛，决策效率高了很多。" },
      { name: "某负责人", role: "零售集团", text: "AI 选品和预测很准，库存周转明显改善，技术很硬。" },
      { name: "某 CTO", role: "金融机构", text: "系统稳定、安全合规，交付按时高质，值得信赖。" },
    ],
    ctaTitle: "让科技，成为你的增长引擎",
    ctaSubtitle: "预约技术专家咨询，定制你的数字化方案。",
    ctaButton: "预约咨询",
    contactPhone: "400-888-3008",
    contactEmail: "hello@tech-company.com",
    contactAddress: "深圳市南山区科技园高新南一道 9 号科创大厦",
    footerSlogan: "智核科技 · 以技术为核，驱动产业向前。",
  },
};
