"use client";

// ============================================================================
// asset —— 素材库(MaterialLibrary)数据（宗旨 v21，自动生成）
// ----------------------------------------------------------------------------
// 由 scripts/gen-oceanleo-template-materials.mjs 生成：素材 = asset.oceanleo.com 的**可打开成品
// 模板**（design 编辑器深链，放大态 iframe 预览 + 套用）+ 可选真实图片（如数据图表）。
// 按 app 输出类型选物料：文档站→文档/简历/书封模板，设计站→海报/名片，数据站→图表。
// 分类（顶部 chips）：方形海报 / 名片 / LOGO / 简历 / 书籍封面
// ============================================================================

import type { MaterialItem } from "@oceanleo/ui/shell";

export const MATERIALS: MaterialItem[] = [
  { id: "tpl-edu-recruit-teacher", title: "教师招募", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-recruit-teacher.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-recruit-teacher.webp?v=202607040933", categories: ["方形海报"], desc: "方形海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-recruit-teacher.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-edu-promo-class", title: "暑期班抢先报名", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-promo-class.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-promo-class.webp?v=202607040933", categories: ["方形海报"], desc: "方形海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-promo-class.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-edu-quote-study", title: "今天的努力是明天的底气", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-quote-study.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/edu-quote-study.webp?v=202607040933", categories: ["方形海报"], desc: "方形海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fedu-quote-study.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-retail-promo-midyear", title: "年中大促全场狂欢", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-promo-midyear.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-promo-midyear.webp?v=202607040933", categories: ["方形海报"], desc: "方形海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fretail-promo-midyear.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-retail-coupon-newstore", title: "满199减50", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-coupon-newstore.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/retail-coupon-newstore.webp?v=202607040933", categories: ["方形海报"], desc: "方形海报 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fretail-coupon-newstore.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-01", title: "陈嘉树", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-01.webp?v=202607040933", categories: ["名片"], desc: "名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-02", title: "李思远", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-02.webp?v=202607040933", categories: ["名片"], desc: "名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-03", title: "王泊宁", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-03.webp?v=202607040933", categories: ["名片"], desc: "名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-namecard-04", title: "赵明轩", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-namecard-04.webp?v=202607040933", categories: ["名片"], desc: "名片 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-namecard-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-logo-01", title: "海豚咖啡", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-01.webp?v=202607040933", categories: ["LOGO"], desc: "LOGO · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-logo-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-logo-02", title: "沁茶研究所", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-02.webp?v=202607040933", categories: ["LOGO"], desc: "LOGO · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-logo-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-logo-03", title: "麦禾烘焙坊", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-03.webp?v=202607040933", categories: ["LOGO"], desc: "LOGO · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-logo-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-logo-04", title: "云顶食府", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-logo-04.webp?v=202607040933", categories: ["LOGO"], desc: "LOGO · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-logo-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-resume-01", title: "陈昊 · 高级产品经理", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-01.webp?v=202607040933", categories: ["简历"], desc: "简历 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-resume-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-resume-02", title: "林晚 · UI设计师", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-02.webp?v=202607040933", categories: ["简历"], desc: "简历 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-resume-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-resume-03", title: "苏铭 · 平面设计师", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-03.webp?v=202607040933", categories: ["简历"], desc: "简历 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-resume-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-resume-04", title: "郑毅 · 前端工程师", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-resume-04.webp?v=202607040933", categories: ["简历"], desc: "简历 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-resume-04.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-novel-01", title: "余生请多指教", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-01.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-01.webp?v=202607040933", categories: ["书籍封面"], desc: "书籍封面 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-novel-01.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-novel-02", title: "深夜来电", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-02.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-02.webp?v=202607040933", categories: ["书籍封面"], desc: "书籍封面 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-novel-02.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-novel-03", title: "海边的旧时光", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-03.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-03.webp?v=202607040933", categories: ["书籍封面"], desc: "书籍封面 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-novel-03.json", openLabel: "套用此模板", kind: "web" },
  { id: "tpl-mc-novel-04", title: "偷偷喜欢你", thumb: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-04.webp?v=202607040933", preview: "https://oceanleo-assets.oss-cn-guangzhou.aliyuncs.com/assets/design-preview/mc-novel-04.webp?v=202607040933", categories: ["书籍封面"], desc: "书籍封面 · 点开可套用", openUrl: "https://design.oceanleo.com/workspace?fn=editor&tplDoc=https%3A%2F%2Fasset.oceanleo.com%2Fdesign-templates%2Fdoc%2Fmc-novel-04.json", openLabel: "套用此模板", kind: "web" },
];

/** 某成品 app 的素材（默认全量；站点可按 app.id 细分后覆写本函数）。 */
export function materialsForApp(appId: string): MaterialItem[] {
  void appId; // 保留按 app 细分的兼容签名；当前所有 app 共用同一素材全集。
  return MATERIALS;
}
